<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component
Statistics Tracker

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
define('__ABI',1);
include(dirname(__FILE__).'/../../ozinviter.php');

$url = $_REQUEST['url'];
$record_id = isset($_REQUEST['id']) ? $_REQUEST['id'] : '';
$token = isset($_REQUEST['token']) ? $_REQUEST['token'] : NULL;
$referrer = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : NULL;

//Save stats to DB? Disable errors, otherwise redirect may fail if errors are printed
//error_reporting(0);
@ozi_stats_record_click($url,$record_id,$token,$referrer);

//Redirect to destination url
header('Location: '.$url);
?>