<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Daum.net contacts importer.

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['daumnet'] = array('type'=>'abi', 'label'=>'Daum.net', 'class'=>'DaumNetImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//DaumNetImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class DaumNetImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'daum');
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$this->setOwnerEmail($loginemail);
		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		$domain = $parts[1];

		oz_set_domain($domain);

		$form = new HttpForm;
		$form->addField("id", $login);
		$form->addField("enpw", $password);
		$form->addField("pw", $password);
		$form->addField("url", "http://addrbook.daum.net");
		$form->addField("relative", "");
		$form->addField("brand", "");
		$form->addField("webmsg", "");
		$postData = $form->buildPostData();
		$html = $this->httpPost("https://logins.daum.net/Mail-bin/login.cgi?dummy=".time(), $postData,"euc-kr");
		$s = $this->getResponseHeader ('X-DaumLogin-Error');
		if (($s != null && strpos($s,"Auth Error")!==FALSE) || strpos($html,"id=\"errorMsg\"")!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		$form = new HttpForm;
		$form->addField("type", 'OUTLOOK');
		$postData = $form->buildPostData();
		$html = $this->httpPost('http://addrbook.daum.net/plus/export.do', $postData,"euc-kr");

		$reader = new OzCsvReader($html);
		$cols = $reader->nextRow();
		if ($cols==null || count($cols)<=3) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find CSV');
		}
		$cl = array();
		while (true) {
			$cols = $reader->nextRow();
			if ($cols==null || count($cols)<=0) break;
			if (count($cols)>=2) {
				$name = $cols[0];
				$email = trim($cols[1]);
				if (abi_valid_email($email)) {
					$cl[] = new Contact($name,$email);
				}
			}
		}
		return $cl;
	}
}

//daum.net
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["daum.net"] = 'DaumNetImporter';
