<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Interia.pl contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['interia'] = array('type'=>'abi', 'label'=>'Interia.pl', 'class'=>'InteriaImporter');

define('InteriaImporter_CONTACT2_REGEX',"/<div class=\"twp\">\\s*&nbsp;\\s*<\/div>&nbsp;(.*?)<\/td>.*?<td[^>]*class=\"akt2\"[^>]*>\\s*&nbsp;(.*?)\\s*<\/td>/ims");


/////////////////////////////////////////////////////////////////////////////////////////
//InteriaImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class InteriaImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'interia');
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		$domain = $parts[1];

		$this->setOwnerEmail($loginemail);
		oz_set_domain($domain);

		$form = new HttpForm;
		$form->addField("referer", "http://poczta.interia.pl/");
		$form->addField("login", $login);
		$form->addField("domain", $domain);
		$form->addField("pass", $password);
		$form->addField("formSubmit.x", "57");
		$form->addField("formSubmit.y", "4");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$form->addField("oldMail", "on");
		$this->cookiejar->addCookie(new OzCookie("poczta=nowa; DOMAIN=interia.pl; PATH=/","http://interia.pl/"));
		$postData = $form->buildPostData();
		$html = $this->httpPost("http://ssl.interia.pl/login.html?oldMail=1", $postData);
		if (strpos($html, '"<div id=\"errorMsg\">"')!=false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

/*
		$html = $this->httpPost("http://poczta.interia.pl/poczta/ksiazka_adresowa/");

		/////////////////////////////////////////////////////
		//EXTRACT!
		/////////////////////////////////////////////////////
		$al = array();
		preg_match_all($this->CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			//#1 is the lastname,firstname
			$email = oz_jsdecode(trim($val[2]));
			$name = oz_jsdecode(trim($val[3]));
			if (!empty($email)) {
				if (empty($name)) $name=$email;
				$contact = new Contact($name, $email);
				$al[] = $contact;
			}
		}
		*/

		$html = $this->httpPost("/organizer/popup/adresses/mid.html");

		/////////////////////////////////////////////////////
		//EXTRACT!
		/////////////////////////////////////////////////////
		$al = array();
		preg_match_all(InteriaImporter_CONTACT2_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			//#1 is the lastname,firstname
			$name = htmlentities2utf8(trim($val[1]));
			$name = $this->extractText($name);
			$email = htmlentities2utf8(trim($val[2]));
			if (!empty($email)) {
				$contact = new Contact($name, $email);
				$al[] = $contact;
			}
		}


		$this->close();
		return $al;
	}
}

// interia.pl
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["interia.eu"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["interia.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["poczta.fm"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["1gb.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["2gb.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["vip.interia.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["czateria.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["akcja.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["serwus.pl"] = 'InteriaImporter';
$_DOMAIN_IMPORTERS["znajomi.pl"] = 'InteriaImporter';
