<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Orkut contacts importer.

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['orkut'] = array('type'=>'abi', 'label'=>'Orkut', 'class'=>'OrkutImporter');


define('OrkutImporter_REDIRECT2_REGEX',"/(https:\/\/www.google.com\/accounts\/(?:CheckCookie|TokenAuth)[^\"]*)\"/i");
define('OrkutImporter_CONTACTHTML_REGEX',"/<div id=\"f\\d+\">(.*?)(?:<div class=\"listdivi\">|<\/form>)/ims");
define('OrkutImporter_CONTACTEMAIL_REGEX',"/onclick=\"_editUser\\('[^']*',\\s*'([^']*)'/ims");
define('OrkutImporter_CONTACTNAME_REGEX',"/<h3\\s+class=\"smller\"[^>]*>.*?<a\\s+href=\"\/Main#Profile\\?uid=\\d+\"\\s*>([^<]*)<\/a>/ims");
define('OrkutImporter_NEXTPAGE2_REGEX',"/<a\\s+href=\"(\/ShowFriends\\.aspx\\?show=all&pno=\\d+)\"[^>]*>[^<]+?&gt;<\/a>/ims");

/////////////////////////////////////////////////////////////////////////////////////////
//OrkutImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class OrkutImporter extends WebRequestor {

	//@api
	function login ($loginemail, $password) {
		$loginemail = preg_replace("/^(.*?)(\.orkut)$/ims", '${1}', $loginemail);

		$html = $this->httpGet('http://www.orkut.com');
		$form = oz_extract_form_by_id($html,'gaia_loginform');
		$form->setField("hl", "en-US");
		$form->setField("Email", $loginemail);
		$form->setField("Passwd", $password);
		$form->setField("signIn", "Sign in");
		$postData = $form->buildPostData();
		$html = $this->httpPost($form->action, $postData);
		if (strpos($html, '"errormsg"')!==FALSE ||
			strpos($html, 'Username and password do not match')!==FALSE ||
			strpos($html, 'service is currently not available')!==FALSE) {
			$this->close();
			return _ABI_AUTHENTICATION_FAILED;
		}

		if (preg_match(OrkutImporter_REDIRECT2_REGEX,$html,$matches)!=0) {
			$location = htmlentities2utf8($matches[1]);
			$html = $this->httpGet($location);
		}

		$location = oz_get_refresh_url($html);
		if ($location!=null)
			$html = $this->httpGet($location);
		return abi_set_success();
	}

	//@api
	function logout() {
		$this->httpGet("/GLogin?cmd=logout");
	}

	//@api
	function fetchContacts ($loginemail=NULL, $password=NULL) {
		if (!empty($loginemail)) {
			$res = $this->login($loginemail,$password);
			if ($res!=_ABI_SUCCESS) return $res;
		}

		$maxPages = 50;
		$html = $this->httpGet("/ShowFriends.aspx?show=all&pno=1");
		
		if (strpos($this->lastUrl, "SMSCaptcha")!==FALSE) {
			return abi_set_error(_ABI_BLOCKED,'Profile locked. SMS verification needed');
		}
		
		$al = array();
		for ($i=0; $i<$maxPages; ++$i) {

		//Extract contacts on page
		preg_match_all(OrkutImporter_CONTACTHTML_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			$chtml = $val[1];
			$name = preg_match(OrkutImporter_CONTACTNAME_REGEX,$chtml,$matches2)!=0 ? htmlentities2utf8(trim($matches2[1])) : null;
			$email = preg_match(OrkutImporter_CONTACTEMAIL_REGEX,$chtml,$matches2)!=0 ? htmlentities2utf8(trim($matches2[1])) : null;
			if (abi_valid_email($email))
				$al[] = new Contact($name,$email);
		}
		if ($i+1>=$maxPages) break;

		//Get next page uri to jump to
		$nextPageUri = null;
		if (preg_match(OrkutImporter_NEXTPAGE2_REGEX,$html,$matches)) {
			$nextPageUri = htmlentities2utf8($matches[1]);
			$nextPageUri = $this->makeAbsolute($this->lastUrl, $nextPageUri);
		}
		//If we're at the last/only page, then exit
		if (empty($nextPageUri)) {
			break;
		}
		$html = $this->httpGet($nextPageUri);
	}
	return $al;
	}
}

//naver.com
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["orkut"] = 'OrkutImporter';
