<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Yandex.ru contacts importer.

Note that mail.ru returns characters encoded in windows-1251 encoding.
This script tries to perform the conversion to utf-8 if iconv library is available,
but does not perform any encoding if the library is not available.

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['yandex'] = array('type'=>'abi', 'label'=>'Yandex', 'class'=>'YandexImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//YandexImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class YandexImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'yandex');
	}

	//@api
	function logout()  {
		$this->httpGet("http://passport.yandex.ru/passport?mode=logout&retpath=http%3A%2F%2Fwww.yandex.ru%2F");
	}

	//@api
	function login ($loginemail, $password) {
		$this->setOwnerEmail($loginemail);
		oz_set_domain(oz_get_email_domain($loginemail));

		//$parts = $this->getEmailParts ($loginemail);
		//$login = $parts[0];
		//$domain = $parts[1];

		$html = $this->httpGet("http://passport.yandex.ru/passport?mode=auth&retpath=http%3A%2F%2Fmail%2Eyandex%2Eru%2Fclassic%2Fabook%5Fexport");
		$form = oz_extract_form_by_name($html,"MainLogin");
		if ($form == null) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find login form');
		}
		$form->setField("login", $loginemail);
		$form->setField("passwd", $password);
		$form->setField("In", "1"); // Some russian text
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$html = $this->postForm($form);
        if (strpos($this->lastUrl,'/passport?mode=auth')!==FALSE || strpos($html,"class=\"b-error")!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		$form = oz_extract_form_by_name($html,"bigform");
		if ($form!==NULL) {
			$form->setField("timestamp",time().'000');
			$form->setField("yes","1");
			$html = $this->postForm($form);
		}

		return abi_set_success();
	}
	
	function _fetchCsv () {
		
		$form = new HttpForm;
		// 0=Outlook Express
		// 1=Microsoft Outlook
		// 2=Mozilla Thunderbird
		$form->addField("tp", "1");
		// 1=russian
		// 0=english
		$form->addField("rus", "0");
		$postData = $form->buildPostData();
		$form->action = '/classic/action_abook_export';
		$html = $this->postForm($form,'CP1251');
		
		//Workaround Yandex bug
		$html = str_replace('\"','""',$html);
		
		return $html;
	}

	//@api
	function fetchContacts ($loginemail=NULL, $password=NULL) {

		if ($loginemail!==NULL || $password!==NULL) {
			$res = $this->login($loginemail,$password);
			if ($res!=_ABI_SUCCESS) return $res;
		}

		$csv = $this->_fetchCsv();
		
		$res = abi_extract_outlook_csv($csv);
		return $res;
	}
}


// yandex.ru
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["yandex.ru"] = 'YandexImporter';
$_DOMAIN_IMPORTERS["ya.ru"] = 'YandexImporter';
