<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

CSV Parser & Extractor
You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/

//--------MAPPING START--------
global $_ABI_FIELDMAPS;
global $_ABI_LFIELDMAPS;
$_ABI_FIELDMAPS = array();
$_ABI_LFIELDMAPS = array();
$_ABI_FIELDMAPS["display name"]="DisplayName";
$_ABI_FIELDMAPS["firstname"]="FirstName";
$_ABI_FIELDMAPS["lastname"]="LastName";
$_ABI_FIELDMAPS["middlename"]="MiddleName";
$_ABI_FIELDMAPS["displayname"]="DisplayName";
$_ABI_FIELDMAPS["nickname"]="NickName";
$_ABI_FIELDMAPS["nick name"]="NickName";
$_ABI_FIELDMAPS["name"]="DisplayName";
$_ABI_FIELDMAPS["email"]="EmailAddress";
$_ABI_FIELDMAPS["spitzname"]="NickName";
$_ABI_FIELDMAPS["spitz name"]="NickName";
$_ABI_FIELDMAPS["primary email"]="EmailAddress";
$_ABI_FIELDMAPS["secondary email"]="Email2Address";
$_ABI_FIELDMAPS["first name"]="FirstName";
$_ABI_FIELDMAPS["last name"]="LastName";
$_ABI_FIELDMAPS["middle name"]="MiddleName";
$_ABI_FIELDMAPS["name"]="DisplayName";
$_ABI_FIELDMAPS["nickname"]="NickName";
$_ABI_FIELDMAPS["e-mail address"]="EmailAddress";
$_ABI_FIELDMAPS["email address"]="EmailAddress";
$_ABI_FIELDMAPS["home street"]="HomeStreet";
$_ABI_FIELDMAPS["home city"]="HomeCity";
$_ABI_FIELDMAPS["home postal code"]="HomePostalCode";
$_ABI_FIELDMAPS["home state"]="HomeState";
$_ABI_FIELDMAPS["home country/region"]="HomeCountry";
$_ABI_FIELDMAPS["home phone"]="HomePhone";
$_ABI_FIELDMAPS["home fax"]="HomeFax";
$_ABI_FIELDMAPS["mobile phone"]="MobilePhone";
$_ABI_FIELDMAPS["personal web page"]="PersonalWebSite";
$_ABI_FIELDMAPS["business street"]="BusinessStreet";
$_ABI_FIELDMAPS["business city"]="BusinessCity";
$_ABI_FIELDMAPS["business postal code"]="BusinessPostalCode";
$_ABI_FIELDMAPS["business state"]="BusinessState";
$_ABI_FIELDMAPS["business country/region"]="BusinessCountry";
$_ABI_FIELDMAPS["business web page"]="BusinessWebSite";
$_ABI_FIELDMAPS["business phone"]="BusinessPhone";
$_ABI_FIELDMAPS["business fax"]="BusinessFax";
$_ABI_FIELDMAPS["pager"]="Pager";
$_ABI_FIELDMAPS["company"]="Company";
$_ABI_FIELDMAPS["job title"]="JobTitle";
$_ABI_FIELDMAPS["department"]="Department";
$_ABI_FIELDMAPS["office location"]="OfficeLocation";
$_ABI_FIELDMAPS["notes"]="Notes";
$_ABI_FIELDMAPS["title"]="Title";
$_ABI_FIELDMAPS["first name"]="FirstName";
$_ABI_FIELDMAPS["middle name"]="MiddleName";
$_ABI_FIELDMAPS["last name"]="LastName";
$_ABI_FIELDMAPS["suffix"]="Suffix";
$_ABI_FIELDMAPS["company"]="Company";
$_ABI_FIELDMAPS["department"]="Department";
$_ABI_FIELDMAPS["job title"]="JobTitle";
$_ABI_FIELDMAPS["business street"]="BusinessStreet";
$_ABI_FIELDMAPS["business street 2"]="BusinessStreet2";
$_ABI_FIELDMAPS["business street 3"]="BusinessStreet3";
$_ABI_FIELDMAPS["business city"]="BusinessCity";
$_ABI_FIELDMAPS["business state"]="BusinessState";
$_ABI_FIELDMAPS["business postal code"]="BusinessPostalCode";
$_ABI_FIELDMAPS["business country"]="BusinessCountry";
$_ABI_FIELDMAPS["home street"]="HomeStreet";
$_ABI_FIELDMAPS["home street 2"]="HomeStreet2";
$_ABI_FIELDMAPS["home street 3"]="HomeStreet3";
$_ABI_FIELDMAPS["home city"]="HomeCity";
$_ABI_FIELDMAPS["home state"]="HomeState";
$_ABI_FIELDMAPS["home postal code"]="HomePostalCode";
$_ABI_FIELDMAPS["home country"]="HomeCountry";
$_ABI_FIELDMAPS["other street"]="OtherStreet";
$_ABI_FIELDMAPS["other street 2"]="OtherStreet2";
$_ABI_FIELDMAPS["other street 3"]="OtherStreet3";
$_ABI_FIELDMAPS["other city"]="OtherCity";
$_ABI_FIELDMAPS["other state"]="OtherState";
$_ABI_FIELDMAPS["other postal code"]="OtherPostalCode";
$_ABI_FIELDMAPS["other country"]="OtherCountry";
$_ABI_FIELDMAPS["assistant's phone"]="AssistantPhone";
$_ABI_FIELDMAPS["business fax"]="BusinessFax";
$_ABI_FIELDMAPS["business phone"]="BusinessPhone";
$_ABI_FIELDMAPS["business phone 2"]="BusinessPhone2";
$_ABI_FIELDMAPS["callback"]="Callback";
$_ABI_FIELDMAPS["car phone"]="CarPhone";
$_ABI_FIELDMAPS["company main phone"]="CompanyMainPhone";
$_ABI_FIELDMAPS["home fax"]="HomeFax";
$_ABI_FIELDMAPS["home phone"]="HomePhone";
$_ABI_FIELDMAPS["home phone 2"]="HomePhone2";
$_ABI_FIELDMAPS["isdn"]="ISDN";
$_ABI_FIELDMAPS["mobile phone"]="MobilePhone";
$_ABI_FIELDMAPS["other fax"]="OtherFax";
$_ABI_FIELDMAPS["other phone"]="OtherPhone";
$_ABI_FIELDMAPS["pager"]="Pager";
$_ABI_FIELDMAPS["primary phone"]="PrimaryPhone";
$_ABI_FIELDMAPS["radio phone"]="RadioPhone";
$_ABI_FIELDMAPS["tty/tdd phone"]="TTYTDDPhone";
$_ABI_FIELDMAPS["telex"]="Telex";
$_ABI_FIELDMAPS["account"]="Account";
$_ABI_FIELDMAPS["anniversary"]="Anniversary";
$_ABI_FIELDMAPS["assistant's name"]="AssistantName";
$_ABI_FIELDMAPS["billing information"]="BillingInformation";
$_ABI_FIELDMAPS["birthday"]="Birthday";
$_ABI_FIELDMAPS["business address po box"]="BusinessAddressPOBox";
$_ABI_FIELDMAPS["categories"]="Categories";
$_ABI_FIELDMAPS["children"]="Children";
$_ABI_FIELDMAPS["directory server"]="DirectoryServer";
$_ABI_FIELDMAPS["e-mail address"]="EmailAddress";
$_ABI_FIELDMAPS["e-mail type"]="EmailType";
$_ABI_FIELDMAPS["e-mail display name"]="EmailDisplayName";
$_ABI_FIELDMAPS["e-mail 2 address"]="Email2Address";
$_ABI_FIELDMAPS["e-mail 2 type"]="Email2Type";
$_ABI_FIELDMAPS["e-mail 2 display name"]="Email2DisplayName";
$_ABI_FIELDMAPS["e-mail 3 address"]="Email3Address";
$_ABI_FIELDMAPS["e-mail 3 type"]="Email3Type";
$_ABI_FIELDMAPS["e-mail 3 display name"]="Email3DisplayName";
$_ABI_FIELDMAPS["gender"]="Gender";
$_ABI_FIELDMAPS["government id number"]="GovernmentIDNumber";
$_ABI_FIELDMAPS["hobby"]="Hobby";
$_ABI_FIELDMAPS["home address po box"]="HomeAddressPOBox";
$_ABI_FIELDMAPS["initials"]="Initials";
$_ABI_FIELDMAPS["internet free busy"]="InternetFreeBusy";
$_ABI_FIELDMAPS["keywords"]="Keywords";
$_ABI_FIELDMAPS["language"]="Language";
$_ABI_FIELDMAPS["location"]="Location";
$_ABI_FIELDMAPS["manager's name"]="ManagerName";
$_ABI_FIELDMAPS["mileage"]="Mileage";
$_ABI_FIELDMAPS["notes"]="Notes";
$_ABI_FIELDMAPS["office location"]="OfficeLocation";
$_ABI_FIELDMAPS["organizational id number"]="OrganizationalIDNumber";
$_ABI_FIELDMAPS["other address po box"]="OtherAddressPOBox";
$_ABI_FIELDMAPS["priority"]="Priority";
$_ABI_FIELDMAPS["private"]="Private";
$_ABI_FIELDMAPS["profession"]="Profession";
$_ABI_FIELDMAPS["referred by"]="ReferredBy";
$_ABI_FIELDMAPS["sensitivity"]="Sensitivity";
$_ABI_FIELDMAPS["spouse"]="Spouse";
$_ABI_FIELDMAPS["user 1"]="User1";
$_ABI_FIELDMAPS["user 2"]="User2";
$_ABI_FIELDMAPS["user 3"]="User3";
$_ABI_FIELDMAPS["user 4"]="User4";
$_ABI_FIELDMAPS["web page"]="WebPage";
$_ABI_FIELDMAPS["titel"]="Title";
$_ABI_FIELDMAPS["vorname"]="FirstName";
$_ABI_FIELDMAPS["2. vorname"]="MiddleName";
$_ABI_FIELDMAPS["nachname"]="LastName";
$_ABI_FIELDMAPS["suffix"]="Suffix";
$_ABI_FIELDMAPS["firma"]="Company";
$_ABI_FIELDMAPS["abteilung"]="Department";
$_ABI_FIELDMAPS["position"]="JobTitle";
$_ABI_FIELDMAPS["stra\xC3\x9Fe (gesch\xC3\xA4ftlich)"]="BusinessStreet";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 2 (gesch\xC3\xA4ftlich)"]="BusinessStreet2";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 3 (gesch\xC3\xA4ftlich)"]="BusinessStreet3";
$_ABI_FIELDMAPS["ort (gesch\xC3\xA4ftlich)"]="BusinessCity";
$_ABI_FIELDMAPS["bundesland (gesch\xC3\xA4ftlich)"]="BusinessState";
$_ABI_FIELDMAPS["plz (gesch\xC3\xA4ftlich)"]="BusinessPostalCode";
$_ABI_FIELDMAPS["land (gesch\xC3\xA4ftlich)"]="BusinessCountry";
$_ABI_FIELDMAPS["stra\xC3\x9Fe (privat)"]="HomeStreet";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 2 (privat)"]="HomeStreet2";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 3 (privat)"]="HomeStreet3";
$_ABI_FIELDMAPS["ort (privat)"]="HomeCity";
$_ABI_FIELDMAPS["bundesland (privat)"]="HomeState";
$_ABI_FIELDMAPS["plz (privat)"]="HomePostalCode";
$_ABI_FIELDMAPS["land (privat)"]="HomeCountry";
$_ABI_FIELDMAPS["stra\xC3\x9Fe (sonstiges)"]="OtherStreet";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 2 (sonstiges)"]="OtherStreet2";
$_ABI_FIELDMAPS["stra\xC3\x9Fe 3 (sonstiges)"]="OtherStreet3";
$_ABI_FIELDMAPS["ort (sonstiges)"]="OtherCity";
$_ABI_FIELDMAPS["bundesland (sonstiges)"]="OtherState";
$_ABI_FIELDMAPS["plz (sonstiges)"]="OtherPostalCode";
$_ABI_FIELDMAPS["land (sonstiges)"]="OtherCountry";
$_ABI_FIELDMAPS["telefon assistent(in)"]="AssistantPhone";
$_ABI_FIELDMAPS["fax (gesch\xC3\xA4ftlich)"]="BusinessFax";
$_ABI_FIELDMAPS["telefon (gesch\xC3\xA4ftlich)"]="BusinessPhone";
$_ABI_FIELDMAPS["telefon 2 (gesch\xC3\xA4ftlich)"]="BusinessPhone2";
$_ABI_FIELDMAPS["autotelefon"]="MobilePhone";
$_ABI_FIELDMAPS["fax (privat)"]="HomeFax";
$_ABI_FIELDMAPS["telefon (privat)"]="HomePhone";
$_ABI_FIELDMAPS["telefon 2 (privat)"]="HomePhone2";
$_ABI_FIELDMAPS["isdn"]="ISDN";
$_ABI_FIELDMAPS["handy"]="MobilePhone";
$_ABI_FIELDMAPS["fax (sonstiges)"]="OtherFax";
$_ABI_FIELDMAPS["telefon (sonstiges)"]="OtherPhone";
$_ABI_FIELDMAPS["pager"]="Pager";
$_ABI_FIELDMAPS["funktelefon"]="RadioPhone";
$_ABI_FIELDMAPS["texttelefon"]="TTYTDDPhone";
$_ABI_FIELDMAPS["telex"]="Telex";
$_ABI_FIELDMAPS["account"]="Account";
$_ABI_FIELDMAPS["jahrestag"]="Anniversary";
$_ABI_FIELDMAPS["name assistent(in)"]="AssistantName";
$_ABI_FIELDMAPS["geburtstag"]="Birthday";
$_ABI_FIELDMAPS["kategorien"]="Categories";
$_ABI_FIELDMAPS["kinder"]="Children";
$_ABI_FIELDMAPS["e-mail-adresse"]="EmailAddress";
$_ABI_FIELDMAPS["anzeigename f\xC3\xBCr e-mail"]="EmailDisplayName";
$_ABI_FIELDMAPS["e-mail-adresse 2"]="Email2Address";
$_ABI_FIELDMAPS["anzeigename f\xC3\xBCr e-mail 2"]="Email2DisplayName";
$_ABI_FIELDMAPS["e-mail-adresse 3"]="Email3Address";
$_ABI_FIELDMAPS["anzeigename f\xC3\xBCr e-mail 3"]="Email3DisplayName";
$_ABI_FIELDMAPS["geschlecht"]="Gender";
$_ABI_FIELDMAPS["hobby"]="Hobby";
$_ABI_FIELDMAPS["initialen"]="Initials";
$_ABI_FIELDMAPS["sprache"]="Language";
$_ABI_FIELDMAPS["ort"]="Location";
$_ABI_FIELDMAPS["kilometerleistung"]="Mileage";
$_ABI_FIELDMAPS["anmerkungen"]="Notes";
$_ABI_FIELDMAPS["b\xC3\xBCro"]="OfficeLocation";
$_ABI_FIELDMAPS["personalnummer"]="GovernmentIDNumber";
$_ABI_FIELDMAPS["privat"]="Private";
$_ABI_FIELDMAPS["beruf"]="Profession";
$_ABI_FIELDMAPS["partner(in)"]="Spouse";
$_ABI_FIELDMAPS["nutzer 1"]="User1";
$_ABI_FIELDMAPS["nutzer 2"]="User2";
$_ABI_FIELDMAPS["nutzer 3"]="User3";
$_ABI_FIELDMAPS["nutzer 4"]="User4";
$_ABI_FIELDMAPS["webseite"]="Website";
$_ABI_FIELDMAPS["anrede"]="Title";
$_ABI_FIELDMAPS["vorname"]="FirstName";
$_ABI_FIELDMAPS["weitere vornamen"]="MiddleName";
$_ABI_FIELDMAPS["nachname"]="LastName";
$_ABI_FIELDMAPS["suffix"]="Suffix";
$_ABI_FIELDMAPS["firma"]="Company";
$_ABI_FIELDMAPS["abteilung"]="Department";
$_ABI_FIELDMAPS["position"]="JobTitle";
$_ABI_FIELDMAPS["stra\xC3\x9Fe gesch\xC3\xA4ftlich"]="BusinessStreet";
$_ABI_FIELDMAPS["stra\xC3\x9Fe gesch\xC3\xA4ftlich 2"]="BusinessStreet2";
$_ABI_FIELDMAPS["stra\xC3\x9Fe gesch\xC3\xA4ftlich 3"]="BusinessStreet3";
$_ABI_FIELDMAPS["ort gesch\xC3\xA4ftlich"]="BusinessCity";
$_ABI_FIELDMAPS["region gesch\xC3\xA4ftlich"]="BusinessState";
$_ABI_FIELDMAPS["postleitzahl gesch\xC3\xA4ftlich"]="BusinessPostalCode";
$_ABI_FIELDMAPS["land gesch\xC3\xA4ftlich"]="BusinessCountry";
$_ABI_FIELDMAPS["stra\xC3\x9Fe privat"]="HomeStreet";
$_ABI_FIELDMAPS["stra\xC3\x9Fe privat 2"]="HomeStreet2";
$_ABI_FIELDMAPS["stra\xC3\x9Fe privat 3"]="HomeStreet3";
$_ABI_FIELDMAPS["ort privat"]="HomeCity";
$_ABI_FIELDMAPS["region privat"]="HomeState";
$_ABI_FIELDMAPS["postleitzahl privat"]="HomePostalCode";
$_ABI_FIELDMAPS["land privat"]="HomeCountry";
$_ABI_FIELDMAPS["weitere stra\xC3\x9Fe"]="OtherStreet";
$_ABI_FIELDMAPS["weitere stra\xC3\x9Fe 2"]="OtherStreet2";
$_ABI_FIELDMAPS["weitere stra\xC3\x9Fe 3"]="OtherStreet3";
$_ABI_FIELDMAPS["weiterer ort"]="OtherCity";
$_ABI_FIELDMAPS["weitere region"]="OtherState";
$_ABI_FIELDMAPS["weitere postleitzahl"]="OtherPostalCode";
$_ABI_FIELDMAPS["weiteres land"]="OtherCountry";
$_ABI_FIELDMAPS["telefon assistent"]="AssistantPhone";
$_ABI_FIELDMAPS["fax gesch\xC3\xA4ftlich"]="BusinessFax";
$_ABI_FIELDMAPS["telefon gesch\xC3\xA4ftlich"]="BusinessPhone";
$_ABI_FIELDMAPS["telefon gesch\xC3\xA4ftlich 2"]="BusinessPhone2";
$_ABI_FIELDMAPS["r\xC3\xBCckmeldung"]="Callback";
$_ABI_FIELDMAPS["telefon firma"]="CompanyMainPhone";
$_ABI_FIELDMAPS["fax privat"]="HomeFax";
$_ABI_FIELDMAPS["telefon privat"]="HomePhone";
$_ABI_FIELDMAPS["telefon privat 2"]="HomePhone2";
$_ABI_FIELDMAPS["isdn"]="ISDN";
$_ABI_FIELDMAPS["mobiltelefon"]="MobilePhone";
$_ABI_FIELDMAPS["weiteres fax"]="OtherFax";
$_ABI_FIELDMAPS["weiteres telefon"]="OtherPhone";
$_ABI_FIELDMAPS["pager"]="Pager";
$_ABI_FIELDMAPS["haupttelefon"]="PrimaryPhone";
$_ABI_FIELDMAPS["mobiltelefon 2"]="RadioPhone";
$_ABI_FIELDMAPS["telefon f\xC3\xBCr h\xC3\xB6rbehinderte"]="TTYTDDPhone";
$_ABI_FIELDMAPS["telex"]="Telex";
$_ABI_FIELDMAPS["konto"]="Account";
$_ABI_FIELDMAPS["jahrestag"]="Anniversary";
$_ABI_FIELDMAPS["name assistent"]="AssistantName";
$_ABI_FIELDMAPS["abrechnungsinformation"]="BillingInformation";
$_ABI_FIELDMAPS["geburtstag"]="Birthday";
$_ABI_FIELDMAPS["postfach gesch\xC3\xA4ftlich"]="BusinessAddressPOBox";
$_ABI_FIELDMAPS["kategorien"]="Categories";
$_ABI_FIELDMAPS["kinder"]="Children";
$_ABI_FIELDMAPS["verzeichnisserver"]="DirectoryServer";
$_ABI_FIELDMAPS["e-mail-adresse"]="EmailAddress";
$_ABI_FIELDMAPS["e-mail-typ"]="EmailType";
$_ABI_FIELDMAPS["e-mail: angezeigter name"]="EmailDisplayName";
$_ABI_FIELDMAPS["e-mail 2: adresse"]="Email2Address";
$_ABI_FIELDMAPS["e-mail 2: typ"]="Email2Type";
$_ABI_FIELDMAPS["e-mail 2: angezeigter name"]="Email2DisplayName";
$_ABI_FIELDMAPS["e-mail 3: adresse"]="Email3Address";
$_ABI_FIELDMAPS["e-mail 3: typ"]="Email3Type";
$_ABI_FIELDMAPS["e-mail 3: angezeigter name"]="Email3DisplayName";
$_ABI_FIELDMAPS["keine angabe"]="Gender";
$_ABI_FIELDMAPS["regierungs-nr."]="GovernmentIDNumber";
$_ABI_FIELDMAPS["hobby"]="Hobby";
$_ABI_FIELDMAPS["postfach privat"]="HomeAddressPOBox";
$_ABI_FIELDMAPS["initialen"]="Initials";
$_ABI_FIELDMAPS["sprache"]="Language";
$_ABI_FIELDMAPS["ort"]="Location";
$_ABI_FIELDMAPS["name des/der vorgesetzten"]="ManagerName";
$_ABI_FIELDMAPS["reisekilometer"]="Mileage";
$_ABI_FIELDMAPS["notizen"]="Notes";
$_ABI_FIELDMAPS["b\xC3\xBCro"]="OfficeLocation";
$_ABI_FIELDMAPS["organisations-nr."]="OrganizationalIDNumber";
$_ABI_FIELDMAPS["weiteres postfach"]="OtherAddressPOBox";
$_ABI_FIELDMAPS["priorit\xC3\xA4t"]="Priority";
$_ABI_FIELDMAPS["privat"]="Private";
$_ABI_FIELDMAPS["beruf"]="Profession";
$_ABI_FIELDMAPS["stichw\xC3\xB6rter"]="ReferredBy";
$_ABI_FIELDMAPS["partner"]="Spouse";
$_ABI_FIELDMAPS["benutzer 1"]="User1";
$_ABI_FIELDMAPS["benutzer 2"]="User2";
$_ABI_FIELDMAPS["benutzer 3"]="User3";
$_ABI_FIELDMAPS["benutzer 4"]="User4";
$_ABI_LFIELDMAPS[]=array("DisplayName",array("display","name"));
$_ABI_LFIELDMAPS[]=array("FirstName",array("firstname"));
$_ABI_LFIELDMAPS[]=array("LastName",array("lastname"));
$_ABI_LFIELDMAPS[]=array("MiddleName",array("middlename"));
$_ABI_LFIELDMAPS[]=array("DisplayName",array("displayname"));
$_ABI_LFIELDMAPS[]=array("NickName",array("nickname"));
$_ABI_LFIELDMAPS[]=array("NickName",array("nick","name"));
$_ABI_LFIELDMAPS[]=array("DisplayName",array("name"));
$_ABI_LFIELDMAPS[]=array("EmailAddress",array("email"));
$_ABI_LFIELDMAPS[]=array("NickName",array("spitzname"));
$_ABI_LFIELDMAPS[]=array("NickName",array("spitz","name"));
$_ABI_LFIELDMAPS[]=array("EmailAddress",array("primary","email"));
$_ABI_LFIELDMAPS[]=array("Email2Address",array("secondary","email"));
$_ABI_LFIELDMAPS[]=array("FirstName",array("first","name"));
$_ABI_LFIELDMAPS[]=array("LastName",array("last","name"));
$_ABI_LFIELDMAPS[]=array("MiddleName",array("middle","name"));
$_ABI_LFIELDMAPS[]=array("EmailAddress",array("e","mail","address"));
$_ABI_LFIELDMAPS[]=array("HomeStreet",array("home","street"));
$_ABI_LFIELDMAPS[]=array("HomeCity",array("home","city"));
$_ABI_LFIELDMAPS[]=array("HomePostalCode",array("home","postal","code"));
$_ABI_LFIELDMAPS[]=array("HomeState",array("home","state"));
$_ABI_LFIELDMAPS[]=array("HomeCountry",array("home","country/region"));
$_ABI_LFIELDMAPS[]=array("HomePhone",array("home","phone"));
$_ABI_LFIELDMAPS[]=array("HomeFax",array("home","fax"));
$_ABI_LFIELDMAPS[]=array("MobilePhone",array("mobile","phone"));
$_ABI_LFIELDMAPS[]=array("PersonalWebSite",array("personal","web","page"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet",array("business","street"));
$_ABI_LFIELDMAPS[]=array("BusinessCity",array("business","city"));
$_ABI_LFIELDMAPS[]=array("BusinessPostalCode",array("business","postal","code"));
$_ABI_LFIELDMAPS[]=array("BusinessState",array("business","state"));
$_ABI_LFIELDMAPS[]=array("BusinessCountry",array("business","country/region"));
$_ABI_LFIELDMAPS[]=array("BusinessWebSite",array("business","web","page"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone",array("business","phone"));
$_ABI_LFIELDMAPS[]=array("BusinessFax",array("business","fax"));
$_ABI_LFIELDMAPS[]=array("Pager",array("pager"));
$_ABI_LFIELDMAPS[]=array("Company",array("company"));
$_ABI_LFIELDMAPS[]=array("JobTitle",array("job","title"));
$_ABI_LFIELDMAPS[]=array("Department",array("department"));
$_ABI_LFIELDMAPS[]=array("OfficeLocation",array("office","location"));
$_ABI_LFIELDMAPS[]=array("Notes",array("notes"));
$_ABI_LFIELDMAPS[]=array("Title",array("title"));
$_ABI_LFIELDMAPS[]=array("Suffix",array("suffix"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet2",array("business","street","2"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet3",array("business","street","3"));
$_ABI_LFIELDMAPS[]=array("BusinessCountry",array("business","country"));
$_ABI_LFIELDMAPS[]=array("HomeStreet2",array("home","street","2"));
$_ABI_LFIELDMAPS[]=array("HomeStreet3",array("home","street","3"));
$_ABI_LFIELDMAPS[]=array("HomeCountry",array("home","country"));
$_ABI_LFIELDMAPS[]=array("OtherStreet",array("other","street"));
$_ABI_LFIELDMAPS[]=array("OtherStreet2",array("other","street","2"));
$_ABI_LFIELDMAPS[]=array("OtherStreet3",array("other","street","3"));
$_ABI_LFIELDMAPS[]=array("OtherCity",array("other","city"));
$_ABI_LFIELDMAPS[]=array("OtherState",array("other","state"));
$_ABI_LFIELDMAPS[]=array("OtherPostalCode",array("other","postal","code"));
$_ABI_LFIELDMAPS[]=array("OtherCountry",array("other","country"));
$_ABI_LFIELDMAPS[]=array("AssistantPhone",array("assistant's","phone"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone2",array("business","phone","2"));
$_ABI_LFIELDMAPS[]=array("Callback",array("callback"));
$_ABI_LFIELDMAPS[]=array("CarPhone",array("car","phone"));
$_ABI_LFIELDMAPS[]=array("CompanyMainPhone",array("company","main","phone"));
$_ABI_LFIELDMAPS[]=array("HomePhone2",array("home","phone","2"));
$_ABI_LFIELDMAPS[]=array("ISDN",array("isdn"));
$_ABI_LFIELDMAPS[]=array("OtherFax",array("other","fax"));
$_ABI_LFIELDMAPS[]=array("OtherPhone",array("other","phone"));
$_ABI_LFIELDMAPS[]=array("PrimaryPhone",array("primary","phone"));
$_ABI_LFIELDMAPS[]=array("RadioPhone",array("radio","phone"));
$_ABI_LFIELDMAPS[]=array("TTYTDDPhone",array("tty/tdd","phone"));
$_ABI_LFIELDMAPS[]=array("Telex",array("telex"));
$_ABI_LFIELDMAPS[]=array("Account",array("account"));
$_ABI_LFIELDMAPS[]=array("Anniversary",array("anniversary"));
$_ABI_LFIELDMAPS[]=array("AssistantName",array("assistant's","name"));
$_ABI_LFIELDMAPS[]=array("BillingInformation",array("billing","information"));
$_ABI_LFIELDMAPS[]=array("Birthday",array("birthday"));
$_ABI_LFIELDMAPS[]=array("BusinessAddressPOBox",array("business","address","po","box"));
$_ABI_LFIELDMAPS[]=array("Categories",array("categories"));
$_ABI_LFIELDMAPS[]=array("Children",array("children"));
$_ABI_LFIELDMAPS[]=array("DirectoryServer",array("directory","server"));
$_ABI_LFIELDMAPS[]=array("EmailType",array("e","mail","type"));
$_ABI_LFIELDMAPS[]=array("EmailDisplayName",array("e","mail","display","name"));
$_ABI_LFIELDMAPS[]=array("Email2Address",array("e","mail","2","address"));
$_ABI_LFIELDMAPS[]=array("Email2Type",array("e","mail","2","type"));
$_ABI_LFIELDMAPS[]=array("Email2DisplayName",array("e","mail","2","display","name"));
$_ABI_LFIELDMAPS[]=array("Email3Address",array("e","mail","3","address"));
$_ABI_LFIELDMAPS[]=array("Email3Type",array("e","mail","3","type"));
$_ABI_LFIELDMAPS[]=array("Email3DisplayName",array("e","mail","3","display","name"));
$_ABI_LFIELDMAPS[]=array("Gender",array("gender"));
$_ABI_LFIELDMAPS[]=array("GovernmentIDNumber",array("government","id","number"));
$_ABI_LFIELDMAPS[]=array("Hobby",array("hobby"));
$_ABI_LFIELDMAPS[]=array("HomeAddressPOBox",array("home","address","po","box"));
$_ABI_LFIELDMAPS[]=array("Initials",array("initials"));
$_ABI_LFIELDMAPS[]=array("InternetFreeBusy",array("internet","free","busy"));
$_ABI_LFIELDMAPS[]=array("Keywords",array("keywords"));
$_ABI_LFIELDMAPS[]=array("Language",array("language"));
$_ABI_LFIELDMAPS[]=array("Location",array("location"));
$_ABI_LFIELDMAPS[]=array("ManagerName",array("manager's","name"));
$_ABI_LFIELDMAPS[]=array("Mileage",array("mileage"));
$_ABI_LFIELDMAPS[]=array("OrganizationalIDNumber",array("organizational","id","number"));
$_ABI_LFIELDMAPS[]=array("OtherAddressPOBox",array("other","address","po","box"));
$_ABI_LFIELDMAPS[]=array("Priority",array("priority"));
$_ABI_LFIELDMAPS[]=array("Private",array("private"));
$_ABI_LFIELDMAPS[]=array("Profession",array("profession"));
$_ABI_LFIELDMAPS[]=array("ReferredBy",array("referred","by"));
$_ABI_LFIELDMAPS[]=array("Sensitivity",array("sensitivity"));
$_ABI_LFIELDMAPS[]=array("Spouse",array("spouse"));
$_ABI_LFIELDMAPS[]=array("User1",array("user","1"));
$_ABI_LFIELDMAPS[]=array("User2",array("user","2"));
$_ABI_LFIELDMAPS[]=array("User3",array("user","3"));
$_ABI_LFIELDMAPS[]=array("User4",array("user","4"));
$_ABI_LFIELDMAPS[]=array("WebPage",array("web","page"));
$_ABI_LFIELDMAPS[]=array("Title",array("titel"));
$_ABI_LFIELDMAPS[]=array("FirstName",array("vorname"));
$_ABI_LFIELDMAPS[]=array("MiddleName",array("2","vorname"));
$_ABI_LFIELDMAPS[]=array("LastName",array("nachname"));
$_ABI_LFIELDMAPS[]=array("Company",array("firma"));
$_ABI_LFIELDMAPS[]=array("Department",array("abteilung"));
$_ABI_LFIELDMAPS[]=array("JobTitle",array("position"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet",array("stra\xC3\x9Fe","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet2",array("stra\xC3\x9Fe","2","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet3",array("stra\xC3\x9Fe","3","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessCity",array("ort","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessState",array("bundesland","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPostalCode",array("plz","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessCountry",array("land","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("HomeStreet",array("stra\xC3\x9Fe","privat"));
$_ABI_LFIELDMAPS[]=array("HomeStreet2",array("stra\xC3\x9Fe","2","privat"));
$_ABI_LFIELDMAPS[]=array("HomeStreet3",array("stra\xC3\x9Fe","3","privat"));
$_ABI_LFIELDMAPS[]=array("HomeCity",array("ort","privat"));
$_ABI_LFIELDMAPS[]=array("HomeState",array("bundesland","privat"));
$_ABI_LFIELDMAPS[]=array("HomePostalCode",array("plz","privat"));
$_ABI_LFIELDMAPS[]=array("HomeCountry",array("land","privat"));
$_ABI_LFIELDMAPS[]=array("OtherStreet",array("stra\xC3\x9Fe","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherStreet2",array("stra\xC3\x9Fe","2","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherStreet3",array("stra\xC3\x9Fe","3","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherCity",array("ort","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherState",array("bundesland","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherPostalCode",array("plz","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherCountry",array("land","sonstiges"));
$_ABI_LFIELDMAPS[]=array("AssistantPhone",array("telefon","assistent","in"));
$_ABI_LFIELDMAPS[]=array("BusinessFax",array("fax","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone",array("telefon","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone2",array("telefon","2","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("MobilePhone",array("autotelefon"));
$_ABI_LFIELDMAPS[]=array("HomeFax",array("fax","privat"));
$_ABI_LFIELDMAPS[]=array("HomePhone",array("telefon","privat"));
$_ABI_LFIELDMAPS[]=array("HomePhone2",array("telefon","2","privat"));
$_ABI_LFIELDMAPS[]=array("MobilePhone",array("handy"));
$_ABI_LFIELDMAPS[]=array("OtherFax",array("fax","sonstiges"));
$_ABI_LFIELDMAPS[]=array("OtherPhone",array("telefon","sonstiges"));
$_ABI_LFIELDMAPS[]=array("RadioPhone",array("funktelefon"));
$_ABI_LFIELDMAPS[]=array("TTYTDDPhone",array("texttelefon"));
$_ABI_LFIELDMAPS[]=array("Anniversary",array("jahrestag"));
$_ABI_LFIELDMAPS[]=array("AssistantName",array("name","assistent","in"));
$_ABI_LFIELDMAPS[]=array("Birthday",array("geburtstag"));
$_ABI_LFIELDMAPS[]=array("Categories",array("kategorien"));
$_ABI_LFIELDMAPS[]=array("Children",array("kinder"));
$_ABI_LFIELDMAPS[]=array("EmailAddress",array("e","mail","adresse"));
$_ABI_LFIELDMAPS[]=array("EmailDisplayName",array("anzeigename","f\xC3\xBCr","e","mail"));
$_ABI_LFIELDMAPS[]=array("Email2Address",array("e","mail","adresse","2"));
$_ABI_LFIELDMAPS[]=array("Email2DisplayName",array("anzeigename","f\xC3\xBCr","e","mail","2"));
$_ABI_LFIELDMAPS[]=array("Email3Address",array("e","mail","adresse","3"));
$_ABI_LFIELDMAPS[]=array("Email3DisplayName",array("anzeigename","f\xC3\xBCr","e","mail","3"));
$_ABI_LFIELDMAPS[]=array("Gender",array("geschlecht"));
$_ABI_LFIELDMAPS[]=array("Initials",array("initialen"));
$_ABI_LFIELDMAPS[]=array("Language",array("sprache"));
$_ABI_LFIELDMAPS[]=array("Location",array("ort"));
$_ABI_LFIELDMAPS[]=array("Mileage",array("kilometerleistung"));
$_ABI_LFIELDMAPS[]=array("Notes",array("anmerkungen"));
$_ABI_LFIELDMAPS[]=array("OfficeLocation",array("b\xC3\xBCro"));
$_ABI_LFIELDMAPS[]=array("GovernmentIDNumber",array("personalnummer"));
$_ABI_LFIELDMAPS[]=array("Private",array("privat"));
$_ABI_LFIELDMAPS[]=array("Profession",array("beruf"));
$_ABI_LFIELDMAPS[]=array("Spouse",array("partner","in"));
$_ABI_LFIELDMAPS[]=array("User1",array("nutzer","1"));
$_ABI_LFIELDMAPS[]=array("User2",array("nutzer","2"));
$_ABI_LFIELDMAPS[]=array("User3",array("nutzer","3"));
$_ABI_LFIELDMAPS[]=array("User4",array("nutzer","4"));
$_ABI_LFIELDMAPS[]=array("Website",array("webseite"));
$_ABI_LFIELDMAPS[]=array("Title",array("anrede"));
$_ABI_LFIELDMAPS[]=array("MiddleName",array("weitere","vornamen"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet",array("stra\xC3\x9Fe","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet2",array("stra\xC3\x9Fe","gesch\xC3\xA4ftlich","2"));
$_ABI_LFIELDMAPS[]=array("BusinessStreet3",array("stra\xC3\x9Fe","gesch\xC3\xA4ftlich","3"));
$_ABI_LFIELDMAPS[]=array("BusinessCity",array("ort","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessState",array("region","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPostalCode",array("postleitzahl","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessCountry",array("land","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("HomeStreet",array("stra\xC3\x9Fe","privat"));
$_ABI_LFIELDMAPS[]=array("HomeStreet2",array("stra\xC3\x9Fe","privat","2"));
$_ABI_LFIELDMAPS[]=array("HomeStreet3",array("stra\xC3\x9Fe","privat","3"));
$_ABI_LFIELDMAPS[]=array("HomeCity",array("ort","privat"));
$_ABI_LFIELDMAPS[]=array("HomeState",array("region","privat"));
$_ABI_LFIELDMAPS[]=array("HomePostalCode",array("postleitzahl","privat"));
$_ABI_LFIELDMAPS[]=array("HomeCountry",array("land","privat"));
$_ABI_LFIELDMAPS[]=array("OtherStreet",array("weitere","stra\xC3\x9Fe"));
$_ABI_LFIELDMAPS[]=array("OtherStreet2",array("weitere","stra\xC3\x9Fe","2"));
$_ABI_LFIELDMAPS[]=array("OtherStreet3",array("weitere","stra\xC3\x9Fe","3"));
$_ABI_LFIELDMAPS[]=array("OtherCity",array("weiterer","ort"));
$_ABI_LFIELDMAPS[]=array("OtherState",array("weitere","region"));
$_ABI_LFIELDMAPS[]=array("OtherPostalCode",array("weitere","postleitzahl"));
$_ABI_LFIELDMAPS[]=array("OtherCountry",array("weiteres","land"));
$_ABI_LFIELDMAPS[]=array("AssistantPhone",array("telefon","assistent"));
$_ABI_LFIELDMAPS[]=array("BusinessFax",array("fax","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone",array("telefon","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("BusinessPhone2",array("telefon","gesch\xC3\xA4ftlich","2"));
$_ABI_LFIELDMAPS[]=array("Callback",array("r\xC3\xBCckmeldung"));
$_ABI_LFIELDMAPS[]=array("CompanyMainPhone",array("telefon","firma"));
$_ABI_LFIELDMAPS[]=array("HomeFax",array("fax","privat"));
$_ABI_LFIELDMAPS[]=array("HomePhone",array("telefon","privat"));
$_ABI_LFIELDMAPS[]=array("HomePhone2",array("telefon","privat","2"));
$_ABI_LFIELDMAPS[]=array("MobilePhone",array("mobiltelefon"));
$_ABI_LFIELDMAPS[]=array("OtherFax",array("weiteres","fax"));
$_ABI_LFIELDMAPS[]=array("OtherPhone",array("weiteres","telefon"));
$_ABI_LFIELDMAPS[]=array("PrimaryPhone",array("haupttelefon"));
$_ABI_LFIELDMAPS[]=array("RadioPhone",array("mobiltelefon","2"));
$_ABI_LFIELDMAPS[]=array("TTYTDDPhone",array("telefon","f\xC3\xBCr","h\xC3\xB6rbehinderte"));
$_ABI_LFIELDMAPS[]=array("Account",array("konto"));
$_ABI_LFIELDMAPS[]=array("AssistantName",array("name","assistent"));
$_ABI_LFIELDMAPS[]=array("BillingInformation",array("abrechnungsinformation"));
$_ABI_LFIELDMAPS[]=array("BusinessAddressPOBox",array("postfach","gesch\xC3\xA4ftlich"));
$_ABI_LFIELDMAPS[]=array("DirectoryServer",array("verzeichnisserver"));
$_ABI_LFIELDMAPS[]=array("EmailType",array("e","mail","typ"));
$_ABI_LFIELDMAPS[]=array("EmailDisplayName",array("e","mail:","angezeigter","name"));
$_ABI_LFIELDMAPS[]=array("Email2Address",array("e","mail","2:","adresse"));
$_ABI_LFIELDMAPS[]=array("Email2Type",array("e","mail","2:","typ"));
$_ABI_LFIELDMAPS[]=array("Email2DisplayName",array("e","mail","2:","angezeigter","name"));
$_ABI_LFIELDMAPS[]=array("Email3Address",array("e","mail","3:","adresse"));
$_ABI_LFIELDMAPS[]=array("Email3Type",array("e","mail","3:","typ"));
$_ABI_LFIELDMAPS[]=array("Email3DisplayName",array("e","mail","3:","angezeigter","name"));
$_ABI_LFIELDMAPS[]=array("Gender",array("keine","angabe"));
$_ABI_LFIELDMAPS[]=array("GovernmentIDNumber",array("regierungs","nr"));
$_ABI_LFIELDMAPS[]=array("HomeAddressPOBox",array("postfach","privat"));
$_ABI_LFIELDMAPS[]=array("ManagerName",array("name","des/der","vorgesetzten"));
$_ABI_LFIELDMAPS[]=array("Mileage",array("reisekilometer"));
$_ABI_LFIELDMAPS[]=array("Notes",array("notizen"));
$_ABI_LFIELDMAPS[]=array("OrganizationalIDNumber",array("organisations","nr"));
$_ABI_LFIELDMAPS[]=array("OtherAddressPOBox",array("weiteres","postfach"));
$_ABI_LFIELDMAPS[]=array("Priority",array("priorit\xC3\xA4t"));
$_ABI_LFIELDMAPS[]=array("ReferredBy",array("stichw\xC3\xB6rter"));
$_ABI_LFIELDMAPS[]=array("Spouse",array("partner"));
$_ABI_LFIELDMAPS[]=array("User1",array("benutzer","1"));
$_ABI_LFIELDMAPS[]=array("User2",array("benutzer","2"));
$_ABI_LFIELDMAPS[]=array("User3",array("benutzer","3"));
$_ABI_LFIELDMAPS[]=array("User4",array("benutzer","4"));

//--------MAPPING END--------



//-----------------------------------------------------
//Experimental support for additional fields
//-----------------------------------------------------

//Definitions of available fields
define('Field_FirstName',"FirstName");
define('Field_MiddleName',"MiddleName");
define('Field_LastName',"LastName");
define('Field_DisplayName',"DisplayName");
define('Field_NickName',"NickName");
define('Field_Title',"Title");
define('Field_Suffix',"Suffix");
define('Field_Company',"Company");
define('Field_Department',"Department");
define('Field_JobTitle',"JobTitle");
define('Field_BusinessStreet',"BusinessStreet");
define('Field_BusinessStreet2',"BusinessStreet2");
define('Field_BusinessStreet3',"BusinessStreet3");
define('Field_BusinessCity',"BusinessCity");
define('Field_BusinessState',"BusinessState");
define('Field_BusinessPostalCode',"BusinessPostalCode");
define('Field_BusinessCountry',"BusinessCountry");
define('Field_HomeStreet',"HomeStreet");
define('Field_HomeStreet2',"HomeStreet2");
define('Field_HomeStreet3',"HomeStreet3");
define('Field_HomeCity',"HomeCity");
define('Field_HomePostalCode',"HomePostalCode");
define('Field_HomeCountry',"HomeCountry");
define('Field_OtherStreet',"OtherStreet");
define('Field_OtherStreet2',"OtherStreet2");
define('Field_OtherStreet3',"OtherStreet3");
define('Field_OtherCity',"OtherCity");
define('Field_OtherState',"OtherState");
define('Field_OtherPostalCode',"OtherPostalCode");
define('Field_OtherCountry',"OtherCountry");
define('Field_AssistantPhone',"AssistantPhone");
define('Field_BusinessFax',"BusinessFax");
define('Field_BusinessPhone',"BusinessPhone");
define('Field_CarPhone',"CarPhone");
define('Field_CompanyMainPhone',"CompanyMainPhone");
define('Field_HomeFax',"HomeFax");
define('Field_HomePhone',"HomePhone");
define('Field_HomePhone2',"HomePhone2");
define('Field_ISDN',"ISDN");
define('Field_MobilePhone',"MobilePhone");
define('Field_OtherFax',"OtherFax");
define('Field_OtherPhone',"OtherPhone");
define('Field_Pager',"Pager");
define('Field_PrimaryPhone',"PrimaryPhone");
define('Field_RadioPhone',"RadioPhone");
define('Field_TTYTDDPhone',"TTYTDDPhone");
define('Field_Telex',"Telex");
define('Field_Account',"Account");
define('Field_Anniversary',"Anniversary");
define('Field_AssistantName',"AssistantName");
define('Field_BillingInformation',"BillingInformation");
define('Field_Birthday',"Birthday");
define('Field_BusinessAddressPOBox',"BusinessAddressPOBox");
define('Field_Categories',"Categories");
define('Field_Children',"Children");
define('Field_DirectoryServer',"DirectoryServer");
define('Field_EmailAddress',"EmailAddress");
define('Field_EmailType',"EmailType");
define('Field_EmailDisplayName',"EmailDisplayName");
define('Field_Email2Address',"Email2Address");
define('Field_Email2Type',"Email2Type");
define('Field_Email2DisplayName',"Email2DisplayName");
define('Field_Email3Address',"Email3Address");
define('Field_Email3Type',"Email3Type");
define('Field_Email3DisplayName',"Email3DisplayName");
define('Field_Gender',"Gender");
define('Field_GovernmentIDNumber',"GovernmentIDNumber");
define('Field_Hobby',"Hobby");
define('Field_HomeAddressPOBox',"HomeAddressPOBox");
define('Field_Initials',"Initials");
define('Field_InternetFreeBusy',"InternetFreeBusy");
define('Field_Keywords',"Keywords");
define('Field_Language',"Language");
define('Field_Location',"Location");
define('Field_ManagerName',"ManagerName");
define('Field_Mileage',"Mileage");
define('Field_Notes',"Notes");
define('Field_OfficeLocation',"OfficeLocation");
define('Field_OrganizationalIDNumber',"OrganizationalIDNumber");
define('Field_OtherAddressPOBox',"OtherAddressPOBox");
define('Field_Priority',"Priority");
define('Field_Private',"Private");
define('Field_Profession',"Profession");
define('Field_ReferredBy',"ReferredBy");
define('Field_Sensitivity',"Sensitivity");
define('Field_Spouse',"Spouse");
define('Field_User1',"User1");
define('Field_User2',"User2");
define('Field_User3',"User3");
define('Field_User4',"User4");
define('Field_WebPage',"WebPage");




//@api
class OutlookContact {

	//Map of field name to field value
	var $fields = array();

	//Get a field value
	//
	//Params:
	//	$fieldId = Name of field
	//	defaultValue = Default value to return if field is not defined
	//Returns:
	//	Field value, or $defaultValue if undefined
	//@api
	function get($fieldId, $defaultValue=null) {
		return isset($this->fields[$fieldId]) ? $this->fields[$fieldId] : $defaultValue;
	}

	//@api
	function put($fieldId, $val) {

		//Map email1,2,3 to array in list...?

		$this->fields[$fieldId] = $val;
	}

	//Set value of a field if $val is not null
	//@api
	function putIfNotNull($fieldId, $val) {
		if ($val!=null) $this->fields[$fieldId] = $val;
	}

	//@api
	function remove($fieldId) {
		unset($this->fields[$fieldId]);
	}

	//@api
	function clear () {
		$this->fields = array();
	}

	//deprecated
	//@api
	function getAvailableFieldIds () {
		return array_keys($this->fields);
	}

	//Classic DesktopContact functions
	//@api
	function getName () {return $this->get('Name',null);}
	//@api
	function getEmail () {return $this->get('Email',null);}

	//Deprecated
	function swap ($field1, $field2) {
		$v1 = $this->get($field1);
		$v2 = $this->get($field2);
		$this->put($field1,$v2);
		$this->put($field2,$v1);
	}

}

//Deprecated. Contact2 is effectively renamed to OutlookContact
//@api
class Contact2 extends OutlookContact {
}



class OzCsvReader {

	var $pos = 0;
	var $csv;
	var $n;
	var $delim;

	function OzCsvReader ($csv,$delim=',') {
		$this->csv = $csv;
		$this->n = strlen($csv);
		$this->delim = $delim;
	}

	//Returns array of columns, or null if no more records available
	function nextRow() {
		$cells = array();
		$addCount = 0;
		$n = strlen($this->csv);
		$i = $this->pos;
		$lastChar = '';
		while (true) {
			$sb = '';
			$inQuote = false;
			$eol = false;
			$quoteAllowed = true;
			$hasData = false;
			while (true) {
				if ($i>=$n) {
					//If last character read was a delimiter, then this last item is actually a blank string
					if ($lastChar==$this->delim) $hasData=true;
					$eol = true;
					break;
				}
				$c = $this->csv[$i++];
				//xx // Since we also break the line upon hitting \r, we may encounter \n on the next start of line which we would need to ignore.
				//xx if (!$hasData && $c=="\n") continue;
				
				// If the line begins with a \n character, it may be a leftover of the pervious \r of the \r\n combo. Ignore it.
				if ($c==="\n" && $lastChar==='') continue;
				
				$hasData = true;
				if ($lastChar === '"' && $c !== '"' && $inQuote) {
					$inQuote = false;
				}
				if ($c === $this->delim) {
					if ($inQuote) {
						if ($lastChar === '"') break;
						else $sb.=$c;
					} else {
						$lastChar = $c;
						break;
					}
				} else if ($c === '"') {
					if ($inQuote) {
						if ($lastChar === '"') {
							$sb.=$c;
							$c = '';
						}
					} else {
						if ($quoteAllowed) {
							$inQuote = true;
							$c = '';
						} else {
							$sb.=$c;
						}
					}
				} else if ($c === "\r") {
					//if ($inQuote) $sb.=$c;
					if ($inQuote) {
						$sb.=$c;
					} else {
						$eol = true;
						break;
						//continue;
					}
				} else if ($c === "\n") {
					if ($inQuote) {
						$sb.=$c;
					} else {
						$eol = true;
						break;
					}
				} else {
					$sb.=$c;
					$quoteAllowed = false;
				}
				$lastChar = $c;
			}
			$this->pos = $i;
			if (!$hasData) return null;
			$cells[] = $sb;
			if ($eol) return $cells;
		}
	}
}




//Extract Outlook style CSV into Contact2 objects
class OzCsvExtractor {

	function _toWords($str) {
		$MAX_REALWORDS = 8;
		
		//Remove dashes (e-mail becomes email))
		$str = str_replace('-','',$str);

		//Split to words by these characters
		$words = preg_split("/[\\s_\\-\\.\\(\\)]+/",$str);
		$realwords = array();
		foreach ($words as $word) {
			$word = strtolower(trim($word));
			if (strlen($word)>0) {
				//Limit number of parts
				if (count($realwords)>=$MAX_REALWORDS) break;
				$realwords[]=$word;
			}
		}
		return $realwords;
	}

	function _countMatches($words1,$words2) {
		$c = 0;
		$n = count($words1);
		$m = count($words2);
		for ($i = 0; $i < $n; $i++) {
			for ($j = 0; $j < $m; $j++) {
				if ($words1[$i]==$words2[$j])
					$c++;
			}
		}
		return $c;
	}

	function detectFields ($fieldHeaders, $looseMatching) {
		global $_ABI_FIELDMAPS;
		global $_ABI_LFIELDMAPS;

		$n = count($fieldHeaders);
		$ids = array();
		for ($i=0; $i<$n; $i++) {
		 	$ids[$i] = NULL;
			$header = trim(strtolower($fieldHeaders[$i]));
			if (isset($_ABI_FIELDMAPS[$header])) {
				$ids[$i] = $_ABI_FIELDMAPS[$header];
			}
			else if ($looseMatching) {
				$headerWords = $this->_toWords($header);
				$bestRank = 0;
				foreach ($_ABI_LFIELDMAPS as $fw) {
					$fieldId = $fw[0];
					$count = $this->_countMatches($headerWords,$fw[1]);
					if ($count>0) {
						$rank = $count*65536 + (65536-1-count($fw[1]));
						if ($rank>$bestRank) {
							$bestRank = $rank;
							$ids[$i] = $fieldId;
						}
					}
				}
			}
		}
		return $ids;
	}

/*
	function _getFieldIndex($fieldIds, $fieldId) {
		$n = count($fieldIds);
		for ($i = 0; $i < $n; $i++) {
			if (isset($fieldIds[$i]) && $fieldId==$fieldIds[$i])
				return $i;
		}
		return -1;
	}
*/

	function extractFromReader($csvreader, $fieldIds) {

		//Read data rows
		
		$m = count($fieldIds);
		
		$cl = array();
		while (true) {
			$cells = $csvreader->nextRow();
			if ($cells==false) break;

			$c = new OutlookContact;
			$n = count($cells);
			$fieldCount = 0;
			foreach ($fieldIds as $i=>$fid) {
				if (isset($cells[$i])) {
					$s = $cells[$i];
					$c->put($fid,$s);
					$fieldCount++;
				}
			}
/*			
			for ($i=0; $i<$n; $i++) {
				$s = $cells[$i];
				if ($i<$m) {
					$fid = isset($fieldIds[$i]) ? $fieldIds[$i] : null;
					if ($fid!=null) {
						$c->put($fid,$s);
						$fieldCount++;
					}
				}
			}
*/			
			if ($fieldCount>0) $cl[] = $c;
		}
		return $cl;
	}


	function countFields ($csv, $delimiter) {
		$reader = new OzCsvReader($csv,$delimiter);
		$cells = $reader->nextRow();
		if ($cells==false) return 0;
		return count($cells);
	}

	function detectDelimiter ($csv) {
		$del = null;
		$c2 = 0;	//Highest count
		$c = $this->countFields($csv,",");
		if ($c>$c2) {$c2=$c;$del=',';}
		$c = $this->countFields($csv,";");
		if ($c>$c2) {$c2=$c;$del=';';}
		$c = $this->countFields($csv,"\t");
		if ($c>$c2) {$c2=$c;$del="\t";}
		return $del;
	}


	//FOR LEGACY SUPPORT
	function extract ($csv,$del=null) {
		//Step 1: Detect character set?
		//Cannot do for now

		//Step 2: Detect delimiter (comma, tab, semicolon)
		if ($del==null) $del = $this->detectDelimiter($csv);

		//Step 3: Detect fields. Read header and build mapping.
		$reader = new OzCsvReader($csv,$del);
		$cells = $reader->nextRow();
		if ($cells==false) {
			//No records??
			return array();
		}
		$fieldIds = $this->detectFields ($cells, true);
		return $this->extractFromReader($reader,$fieldIds);

		//$mapping = $this->buildMapping($cells);
		//Step 4: Extract fields
		//return $this->extractFromReader($reader,$mapping);
	}

	function OzCsvExtractor () {
	}
}


function oz_csv_encode ($str, $delimiter=',', $forceEscape=false) {
	$needEncoding = $forceEscape;
	$n = strlen($str);
	if (!$needEncoding) {
		for ($i=0; $i<$n; $i++) {
		 	$c = $str[$i];
			if ($c == ' ' || $c == '"' || $c == $delimiter || $c == '\r' || $c == '\n' || $c == '\t') {
				$needEncoding = true;
				break;
			}
		}
	}
	if ($needEncoding) {
		$sb='"';
		for ($i=0; $i<$n; $i++) {
		 	$c = $str[$i];
			if ($c == '"') $sb.='"';
			$sb.=$c;
		}
		$sb.= '"';
		return $sb;
	}
	else {
		return $str;
	}
}

