<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Bebo friends list importer and invite sender

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this invite sender!');

global $_OZ_SERVICES;
$_OZ_SERVICES['is_bebo'] = array('type'=>'is', 'label'=>'Bebo', 'class'=>'BeboInviter');

/////////////////////////////////////////////////////////////////////////////////////////
//BeboInviter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class BeboContact extends SocialContact {
	function FriendsterContact ($uid, $name, $imgurl) {
		parent::SocialContact($uid, $name, $imgurl);
	}
}

define('BeboInviter_NEXTPAGE_REGEX',"/<a href=([^ >\"]*)>\\s*<b>[^<]*?>>><\/b>\\s*<\/a>/ims");
define('BeboInviter_CONTACT_REGEX',"/<td class=m_c[^>]*>(.*?)<img src=http:\/\/s\\.bebo\\.com\/img\/vid.gif[^>]*>/ims");
define('BeboInviter_CONTACTDETAILS_REGEX',"/<a href=\/Profile\\.jsp\\?MemberId=(\\d*)[^>]*>\\s*<img src=([^ \"]*) width=90 height=90 vspace=3 border=0\/>.*?<td bgcolor=#efefef>\\s*<a href=\/Profile\\.jsp\\?MemberId=\\d*>\\s*<b>([^<]*)<\/b>\\s*<\/a>/ims");
define('BeboInviter_MEMBERID_REGEX',"/FriendList\\.jsp\\?MemberId=(\\d*)/ims");
define('BeboInviter_FORMTOKEN_REGEX',"/<input name=\"FormToken\" value=\"([^\"]*)\"/ims");

//@api
class BeboInviter extends WebRequestor {

	var $memberId;

	//@api
	function getInfo () {
		return array('id'=>'bebo');
	}

	//@api
	function login ($email, $password) {
		oz_set_domain('bebo');

		$html = $this->httpGet('http://www.bebo.com/SignIn.jsp');

		$form = new HttpForm;
		$form->addField("FriendsMemberId", "");
		$form->addField("FriendsChecksumNbr", "");
		$form->addField("InviteRecipientId", "");
		$form->addField("InviteChecksumNbr", "");
		$form->addField("AppUrl", "");
		$form->addField("Page", "");
		$form->addField("QueryString", "");
		$form->addField("api_key", "");
		$form->addField("next", "");
		$form->addField("canvas", "null");
		$form->addField("v", "");
		$form->addField("EmailUsername", $email);
		$form->addField("Password", $password);
		$form->addField("SignIn", "Sign In >");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost('http://www.bebo.com/SignIn.jsp', $postData);

		if (strpos($html, '<div id=error>')!=false ||
			strpos($html, 'not been recognized')!=false ||
			strpos($html, 'Your password is incorrect')!=false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad username or password');
		}

		//Get member ID
		$html = $this->httpGet("http://www.bebo.com/Profile.jsp?MyProfile=Y");
		if (preg_match(BeboInviter_MEMBERID_REGEX,$html,$matches)==0) {
			return abi_set_error(_ABI_FAILED,'Cannot find member id');
		}
		$this->memberId = $matches[1];

		return abi_set_success();
	}

	//@api
	function logout () {
		$this->httpGet("http://www.bebo.com/SignOut.jsp");
	}


	//@api
	function fetchContacts ($maxFetch=NULL, $maxPages=NULL) {

		//Get max contacts, pages, duration to fetch contacts
		if ($maxFetch===NULL) $maxFetch = oz_get_config('limit.max_contacts',1000);
		if ($maxPages===NULL) $maxPages = oz_get_config('limit.max_pages',30);

		$html = $this->httpGet('http://www.bebo.com/FriendList.jsp?MemberId='.$this->memberId);

		//Loop
		$ids = array();
		$al = array();
		//Allow up to 30 pages of contacts
		for ($i=0; $i<$maxPages; ++$i) {

			//Extract contacts on page
			preg_match_all(BeboInviter_CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
			foreach ($matches as $val) {

				$contacthtml = $val[1];
				if (preg_match(BeboInviter_CONTACTDETAILS_REGEX,$contacthtml,$matches2)) {
					$uid = trim($matches2[1]);
					if (!isset($ids[$uid])) {
						$ids[$uid] = $uid;
						$imgurl = htmlentities2utf8(trim($matches2[2]));
						$name = htmlentities2utf8(trim($matches2[3]));
						$contact = new BeboContact($uid,$name,$imgurl);
						$al[] = $contact;
						if (count($al)>=$maxFetch) break;
					}
				}
			}
			if (count($al)>=$maxFetch) break;
			if ($i+1>=$maxPages) break;

			//Get next page uri to jump to
			$nextPageUri = null;
			if (preg_match(BeboInviter_NEXTPAGE_REGEX,$html,$matches)) {
				$nextPageUri = htmlentities2utf8($matches[1]);
				$nextPageUri = $this->makeAbsolute($this->lastUrl, $nextPageUri);
			}

			//If we're at the last/only page, then exit
			if (empty($nextPageUri)) {
				break;
			}
			$html = $this->httpGet($nextPageUri);
		}

		return $al;
	}

	//returns true if successful, false if failed.
	//Remember to keep message short (less than 4000 characters)
	//@api
	function sendMessage ($uid, $subject, $message, $saveToSent = false) {

		if (oz_instanceof($uid,'SocialContact')) $uid = $uid->uid;

		$subject = substr($subject,0,100);
		$url = "http://www.bebo.com/mail/MailCompose.jsp?ToMemberId=".$uid;

		$form = new HttpForm;
		$form->addField("SelectAttachmentTypeCd", "");
		$form->addField("SendTo", $uid=="*" ? "LALL" : "M".$uid);
		$form->addField("Subject", $subject);
		$form->addField("Message", $message);
		$form->addField("Send", " Send ");
		$postData = $form->buildPostData();
		$html = $this->httpPost($url, $postData);
		return strpos($html,'<div id=error>')===false;
	}

	//@api
	function sendMessages ($uids, $subject, $message, $saveToSent = false) {
		$res = true;
		foreach ($uids as $uid) {
			$res &= $this->sendMessage($uid, $subject, $message, $saveToSent);
		}
		return $res==true;
	}

	//@api
	function postBulletin ($subject,$message) {
		return $this->sendMessage("*",$subject,$message);
	}

	//@api
	function postShoutOut ($message) {

		$message = substr($message,0,140);

        $form = new HttpForm;
        $form->action = "http://www.bebo.com/c/home20/update_saying";
        $form->addField("SayingTx", $message);
        $html = $this->postForm($form);
        return strpos($html,"\"message\":\"success\"")!==FALSE;
	}

}
