<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component
Administration/Config Page

*DEV VERSION. DO NOT USE*

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
//if (!defined('__ABI')) die('Please include abi.php to use this inviter component!');
$basedir = dirname(__FILE__);
if (!defined('__ABI')) include($basedir.'/abimporter/abi.php');
if (!defined('_OZ_INVITER')) include($basedir.'/inviter/ozinviter.php');





//header("Content-Type: text/html; charset=\"utf-8\"

//function ozi_get_param($key,$defaultValue=null) {
//	return isset($_REQUEST[$key]) ? (get_magic_quotes_gpc()?stripslashes($_REQUEST[$key]):$_REQUEST[$key]) : $defaultValue;
//}
/*
if (get_magic_quotes_gpc()) {
	$in = array(&$_GET, &$_POST, &$_COOKIE,&$_REQUEST);
	while (list($k,$v) = each($in)) {
		foreach ($v as $key => $val) {
			if (!is_array($val)) {
				$in[$k][$key] = stripslashes($val);
				continue;
			}
			$in[] =& $in[$k][$key];
		}
	}
	unset($in);
}
*/

function oz_render_select($name,$values,$selected) {
	$html = '<select name="'.$name.'">';
	foreach ($values as $k=>$v) $html .= '<option value="'.$k.'"'.($selected==$k?' selected="selected"':'').'>'.htmlspecialchars($v,ENT_COMPAT,'UTF-8').'</option>';
	$html .= '</select>';
	return $html;
}
function oz_render_input($name,$value='',$width=50,$maxlen=NULL) {
	$html = '<input type="text" name="'.$name.'" size="'.$width.'"';
	if ($maxlen!=NULL) $html .= ' maxlength="'.$maxlen.'"';
	$html .= ' value="'.htmlspecialchars($value,ENT_COMPAT,'UTF-8').'"/>';
	return $html;
}
function oz_render_textarea($name,$value='',$cols=50,$rows=5) {
	$html = '<textarea name="'.$name.'" cols="'.$cols.'" rows="'.$rows.'">';
	$html .= htmlspecialchars($value,ENT_COMPAT,'UTF-8');
	$html .= '</textarea>';
	return $html;
}
function oz_php_encode($str) {
	$n = strlen($str);
	$s = '';
	for ($i=0; $i<$n; $i++) {
		$c = $str[$i];
		$o = ord($c);
		if ($c==="\r") {$s.='\\r';}
		else if ($c==="\n") {$s.='\\n';}
		else if ($c==="\t") {$s.='\\t';}
		else if ($c==="\\" || $c=='$' || $c=='"') {
			$s.="\\".$c;
		}
		else if ($o<32 || $o>126) {
			$h=dechex($o);
			if (strlen($h)==1) $h='0'.$h;
			$s.='\\x'.$h;
		}
		else {
			$s.=$c;
		}
	}
	return $s;
}


function tmp_oz_get_config(&$arr,$key,$defaultval) {return isset($arr[$key])?$arr[$key]:$defaultval;}

function tmp_oz_render_css (&$configurable, $feature) {
	echo $configurable[$feature]?'':'class="oz_hidden"';
}



//--------------------------------------------------
//Check if the config file exists and is writable, or if it doesn't exist and directory is writable
//--------------------------------------------------
/*
function ozi_check_config_writable($filename) {
	if (file_exists($filename)) {
		if (!is_writable($filename)) {
			//CONFIG FILE CAN'T BE WRITTEN TO
			echo '<div class="oz_error">The file '.htmlspecialchars($filename).' needs to be writable. Cannot save settings.</div>';
			return false;
		}
	}
	else {
		if (!is_writable(dirname($filename))) {
			//DIRECTORY CANNOT BE WRITTEN. CAN'T CREATE CONFIG FILE!
			echo '<div class="oz_error">The directory '.htmlspecialchars(realpath(dirname($filename))).' needs to be writable. Cannot save settings.</div>';
			return false;
		}
	}
}
*/

//--------------------------------------------------
//Render the config PHP code
//$arr - Configuration array (typically $_OZ_CONFIG);
//--------------------------------------------------
function ozi_render_config_code(&$arr) {
	$s = "<?\r\n";
	foreach ($arr as $key=>$value) {
		$s .= 'ozi_set_config(\''.$key.'\',';
		if (is_string($value)) $s.='"'.oz_php_encode($value).'"';
		else if (is_bool($value)) $s.=$value?'TRUE':'FALSE';
		else if (is_null($value)) $s.='NULL';
		else if (is_numeric($value)) $s.=$value;
		$s .= ");\r\n";
	}
	$s .= '?>';
	return $s;
}

//--------------------------------------------------
//Render the admin page
//$configarray = Array of configuration (typically $_OZ_CONFIG)
//$configurable = Array of configurable parts. Parts that aren't configurable are hidden using CSS.
//--------------------------------------------------
function ozi_render_admin($configfile, $configurable) {

	global $_OZ_CONFIG;
	$configarray =& $_OZ_CONFIG;
	
	$_oz_default_configurable = array(
		'mailer' => TRUE,		//true=can customize mailer, false=system has its own mailer
		'sender' => TRUE,		//true=can customize sender name/email, false=system defines its own sender name/email
		'invite_url' => TRUE,	//true=can customize invite url, false=system defines its own invite url
		'mail_template' => TRUE,	//true=can customize mail template, false=system has its own mail template
		'personal_message' => TRUE,	//true=can customize personal message on/off, false=cannot personalize
		'default_mailer_available' => FALSE,	//true=mod/plugin has a default mailer which can be used, false=no default mailer available
	);
	$configurable = array_merge($_oz_default_configurable,$configurable);

		
	//	$configfile = realpath(JPATH_SITE.'/components/com_octazeninviter/inviter/settings/config.php');
	//ozi_check_config_writable($configfile);
	if (file_exists($configfile)) include($configfile);

	//Check file writable?	
	if (file_exists($configfile)) {
		if (!is_writable($configfile)) {
			//CONFIG FILE CAN'T BE WRITTEN TO
			echo '<div class="oz_error">The file '.htmlspecialchars($configfile,ENT_COMPAT,'UTF-8').' needs to be writable. Cannot save settings.</div>';
		}
	}
	else {
		$dir = dirname($configfile);
		if (!is_writable($dir)) {
			//DIRECTORY CANNOT BE WRITTEN. CAN'T CREATE CONFIG FILE!
			echo '<div class="oz_error">The directory '.htmlspecialchars($dir,ENT_COMPAT,'UTF-8').' needs to be writable. Cannot save settings.</div>';
		}
	}

	if (isset($_REQUEST['oz_save'])) {
	
		$configarray['selector_mode'] = intval(ozi_get_param('oz_selector_mode'));
		$configarray['selector_group_icons'] = ozi_get_param('oz_selector_group_icons')=='1';
		
		$configarray['your_name'] = ozi_get_param('oz_ask_sender_name_email')=='1';
		$configarray['your_email'] = ozi_get_param('oz_ask_sender_name_email')=='1';
		$configarray['allow_personal_message'] = ozi_get_param('oz_allow_personal_message')=='1';
		$configarray['manual_multiple_textbox'] = ozi_get_param('oz_manual_multiple_textbox')=='1';
		$configarray['prefer_webauth'] = ozi_get_param('oz_prefer_webauth')=='1';
		$configarray['allow_manual_invite'] = ozi_get_param('oz_allow_manual_invite')=='1';
		$configarray['allow_upload'] = ozi_get_param('oz_allow_upload')=='1';
		$configarray['allow_bookmark'] = ozi_get_param('oz_allow_bookmark')=='1';
		
		$configarray['desktopimporter_present'] = intval(ozi_get_param('oz_desktopimporter_present'));
		$configarray['desktopimporter_decrypt_key'] = ozi_get_param('oz_desktopimporter_decrypt_key');
		$configarray['desktopimporter_config_string'] = ozi_get_param('oz_desktopimporter_config_string');
		
		$configarray['url'] = ozi_get_param('oz_url');
		$configarray['from_email'] = ozi_get_param('oz_sender_email');
		$configarray['from_name'] = ozi_get_param('oz_sender_name');
		$configarray['mail_charset'] = ozi_get_param('oz_mail_charset');
		$configarray['subject'] = ozi_get_param('oz_subject');
		$configarray['text_body'] = ozi_get_param('oz_text_body');
		$configarray['html_body'] = ozi_get_param('oz_html_body');
		$configarray['prefer_format'] = ozi_get_param('oz_prefer_format');
		

		$configarray['mailer'] = ozi_get_param('oz_mailer','mail');
		$configarray['smtp_host'] = ozi_get_param('oz_smtp_host','localhost');
		$configarray['smtp_port'] = ozi_get_param('oz_smtp_port','25');
		$configarray['smtp_ssl'] = ozi_get_param('oz_smtp_ssl','0')=='1';
		$configarray['smtp_auth'] = ozi_get_param('oz_smtp_auth','0')=='1';
		$configarray['smtp_user'] = ozi_get_param('oz_smtp_user','');
		$configarray['smtp_pass'] = ozi_get_param('oz_smtp_pass','');
		$configarray['mail_format'] = ozi_get_param('oz_mail_format','text');

		$configarray['limits.max_contacts'] = ozi_get_param('oz_limits_max_contacts','10000');
		$configarray['limits.max_pages'] = ozi_get_param('oz_limits_max_pages','30');

		
		/////////////////////////////////////////////
		//Save config
		/////////////////////////////////////////////
		$f = fopen($configfile,'w');
		if ($f!==FALSE) {
			$s = ozi_render_config_code($_OZ_CONFIG);
			fwrite($f,$s);
			fclose($f);
			echo '<div class="oz_success">Saved settings</div>';
		}
		else {
			echo '<div class="oz_error">Failed to save to config file '.htmlspecialchars($configfile,ENT_COMPAT,'UTF-8').'</div>';
		}
	}

	
	ob_start();
?>
<style type="text/css">
/*
body,td,th,input,select,textarea {font-family:Arial, Helvetica, sans-serif;font-size:12px;}
*/

/* COLOR SETTINGS */
/*
#oz_config_table {border:solid 0px #CCCCCC;background-color:#F8F8F8;}
*/

.oz_config_table {
	width:100%;
}
.oz_config_table tr td, .oz_config_table tr th {
	border-bottom: dotted 1px #D0D0D0;
	padding-bottom: 5px;
}
/*
#oz_config_table tr th {background-color:#FEFEFE}
#oz_config_table tr td {}
*/

#oz_config {
	color:#000000;
	font-size:12px;
}
#oz_config * {
	font-family:Arial, Helvetica, sans-serif;
}
#oz_config textarea, #oz_config select, #oz_config input {
	border: solid 1px #999999;
}
#oz_config fieldset {
	background-color:#F8F8F8;
	font-weight: bold
}
/*
#oz_config_table {border:solid 0px #CCCCCC;}
*/

.oz_hidden {display:none;}

.oz_tip {
	color:#888888;
	font-weight:normal;
	font-size:11px;
}
/* FORMATTING SETTINGS */
.oz_config_table tr th {
	text-align:left;
	vertical-align:top;
	font-weight:bold;
	width: 250px;
	font-size:12px;
}
.oz_config_table tr td {
	text-align:left;
	vertical-align:top;
	font-size:12px;
}

.oz_error {
	border: solid 1px #808080;
	background: #FFE1E2;
	color: #000000;
	font-weight: bold;
	margin: 5px;
	padding: 5px;
}

.oz_success {
	border: solid 1px #808080;
	background: #E8FFE8;
	color: #000000;
	font-weight: bold;
	margin: 5px;
	padding: 5px;
}

.oz_admin_header {
	font-size: 18px;
	font-weight: bold;
	color: #A00000;
	padding-top: 5px;
	padding-bottom: 10px;
}

</style>
<div id="oz_config">
  <form name="ozform_admin" method="post">
    <? echo ozi_render_form_snippet(); ?>
    <div class="oz_admin_header">General</div>
    <table border="0" cellspacing="1" cellpadding="3" class="oz_config_table">
      <tr>
        <th>Selector Mode</th>
        <td><? echo oz_render_select('oz_selector_mode', array(0=>'Icon',1=>'Login form',2=>'Login form with icons'), tmp_oz_get_config($configarray,'selector_mode',0)) ?></td>
      </tr>
      <tr>
        <th>Group Icons
          <div class="oz_tip">Yes to separate groups of service icons with a dashed line</div></th>
        <td><? echo oz_render_select('oz_selector_group_icons',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'selector_group_icons',FALSE)?1:0) ?></td>
      </tr>
      <tr>
        <th>Manual Invite Email Entry
          <div class="oz_tip">Use individual email text boxes for manual invitation, or single combined textbox with multiple email addresses separated by comma</div></th>
        <td><? echo oz_render_select('oz_manual_multiple_textbox',array(1=>'Multiple Textbox',0=>'Single Textbox'), tmp_oz_get_config($configarray,'manual_multiple_textbox',FALSE)?1:0) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'personal_message') ?>>
        <th>Allow Personal Message
          <div class="oz_tip">Allow/Disallow personal message in sent invitations</div></th>
        <td><? echo oz_render_select('oz_allow_personal_message',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'allow_personal_message',FALSE)?1:0) ?></td>
      </tr>
      <tr>
        <th>Preferred Auth
          <div class="oz_tip">Prefer web authentication to login id/email+password</div></th>
        <td><? echo oz_render_select('oz_prefer_webauth',array(1=>'Web authentication',0=>'Login id/email + password'), tmp_oz_get_config($configarray,'prefer_webauth',TRUE)?1:0) ?></td>
      </tr>
      <tr>
        <th>Allow Manual Invites
          <div class="oz_tip">Allow users to manually enter email address of friends to invite</div></th>
        <td><? echo oz_render_select('oz_allow_manual_invite',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'allow_manual_invite',TRUE)?1:0) ?></td>
      </tr>
      <tr>
        <th>Allow  CSV/LDIF Upload
          <div class="oz_tip">Allow users to upload Outlook/Thunderbird CSV/LDIF address books.</div></th>
        <td><? echo oz_render_select('oz_allow_upload',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'allow_upload',TRUE)?1:0) ?></td>
      </tr>
      <tr>
        <th>Allow Bookmarks
          <div class="oz_tip">Allow users to share link on social bookmarks</div></th>
        <td><? echo oz_render_select('oz_allow_bookmark',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'allow_bookmark',TRUE)?1:0) ?></td>
      </tr>
    </table>
    <br/>
    <div class="oz_admin_header">Limits</div>
    <table border="0" cellspacing="1" cellpadding="3" class="oz_config_table">
      <tr>
        <th>Maximum Contacts
        <div class="oz_tip">Maximum number of contacts to fetch.</div></th>
        <td><? echo oz_render_input('oz_limits_max_contacts',tmp_oz_get_config($configarray,'limits.max_contacts',''),6,6) ?></td>
      </tr>
      <tr>
        <th>Maximum Pages of Contacts
        <div class="oz_tip">Maximum number of pages of contacts to fetch. 1 pages normally takes 1-2 web requests (approx 1-5 seconds)</div></th>
        <td><? echo oz_render_input('oz_limits_max_pages',tmp_oz_get_config($configarray,'limits.max_pages',''),6,6) ?></td>
      </tr>
    </table>

    
    <br/>
    <div class="oz_admin_header">ActiveX/Desktop Importer</div>
    <table border="0" cellspacing="1" cellpadding="3" class="oz_config_table">
      <tr>
        <th>Desktop Importer
          <div class="oz_tip">Enable/Disable Desktop Importer</div></th>
        <td><? echo oz_render_select('oz_desktopimporter_present',array(0=>'Not present',1=>'Present. Use ActiveX if possible',2=>'Present. Always use Desktop EXE'), tmp_oz_get_config($configarray,'desktopimporter_present',0)) ?>
        <div class="oz_tip"><br/>If available, place DesktopImporter.exe and OzDesktopImporter.exe in this directory:<br/><pre><? echo htmlspecialchars(realpath(dirname(__FILE__).'/res/desktop/')) ?></pre></div>
        </td>
      </tr>
      <tr>
        <th>Desktop Importer Decryption Key
          <div class="oz_tip">Place your desktop importer decryption key here</div></th>
        <td><? echo oz_render_input('oz_desktopimporter_decrypt_key',tmp_oz_get_config($configarray,'desktopimporter_decrypt_key',''),50,100) ?></td>
      </tr>
      <tr>
        <th>Desktop Importer Config String
          <div class="oz_tip">Place your desktop importer configuration string here</div></th>
        <td><? echo oz_render_input('oz_desktopimporter_config_string',tmp_oz_get_config($configarray,'desktopimporter_config_string',''),50,10000) ?></td>
      </tr>
    </table>
    <br/>
    <div class="oz_admin_header">Invite Message</div>
    <table border="0" cellspacing="1" cellpadding="3" class="oz_config_table">
      <tr <? tmp_oz_render_css($configurable,'invite_url') ?>>
        <th>Invite/Bookmark URL
        <div class="oz_tip">Invitation url. Blank for mod/plugin default.</div></th>
        <td><? echo oz_render_input('oz_url',tmp_oz_get_config($configarray,'url',''),50,200) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'sender') ?>>
        <th>Prompt for Sender Name &amp; Email
          <div class="oz_tip">Prompt for name and email address of sender</div></th>
        <td><? echo oz_render_select('oz_ask_sender_name_email',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'your_email',FALSE)?1:0) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'sender') ?>>
        <th>Sender Name
        <div class="oz_tip">Name of sender. Blank for mod/plugin default.</div></th>
        <td><? echo oz_render_input('oz_sender_name',tmp_oz_get_config($configarray,'from_name',''),50,100) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'sender') ?>>
        <th>Sender Email
        <div class="oz_tip">Email address of sender. Blank for mod/plugin default.</div></th>
        <td><? echo oz_render_input('oz_sender_email',tmp_oz_get_config($configarray,'from_email',''),50,100) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'mail_template') ?>>
        <th>Mail Charset
        <div class="oz_tip">Character set for mail. Default is 'utf-8'.</div></th>
        <td><? echo oz_render_input('oz_mail_charset',tmp_oz_get_config($configarray,'mail_charset','utf-8'),50,200) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'mail_template') ?>>
        <th>Mail Subject
        <div class="oz_tip">Mail subject. (Blank for mod/plugin default)</div></th>
        <td><? echo oz_render_input('oz_subject',tmp_oz_get_config($configarray,'subject',''),50,200) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'mail_template') ?>>
        <th>Preferred Format</th>
        <td><? echo oz_render_select('oz_prefer_format', array('html'=>'HTML','text'=>'Text'), tmp_oz_get_config($configarray,'prefer_format','text')) ?></td>
      </tr>
      
      <tr <? tmp_oz_render_css($configurable,'mail_template') ?>>
        <th>Text Message
          <div class="oz_tip">Blank for mod/plugin default. The placeholder {URL} is replaced with the invite URL, and {PERSONALMESSAGE} is replaced with the user's personal message (if any) </div></th>
        <td><? echo oz_render_textarea('oz_text_body',tmp_oz_get_config($configarray,'text_body',''),50,10) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'mail_template') ?>>
        <th>HTML Message
          <div class="oz_tip">Blank for mod/plugin default. The placeholder {URL} is replaced with the invite URL, and {PERSONALMESSAGE} is replaced with the user's personal message (if any)</div></th>
        <td><? echo oz_render_textarea('oz_html_body',tmp_oz_get_config($configarray,'html_body',''),50,10) ?></td>
      </tr>
    </table>
    <br/>
    <div class="oz_admin_header">Mailer</div>
    <table border="0" cellspacing="1" cellpadding="3" class="oz_config_table">
      <tr>
        <th>Preferred Mailer</th>
        <td><? 
		$cfg = array();
		if ($configurable['default_mailer_available']) $cfg[''] = '(Application\'s mailer)';
		$cfg['mail'] = 'mail()';
		$cfg['smtp'] = 'SMTP';
		echo oz_render_select('oz_mailer', $cfg, tmp_oz_get_config($configarray,'mailer','')) 
		?></td>
      </tr>
      <tr>
        <th>SMTP Host:Port</th>
        <td><? echo oz_render_input('oz_smtp_host',tmp_oz_get_config($configarray,'smtp_host','localhost'),10,100) ?>:<? echo oz_render_input('oz_smtp_port',tmp_oz_get_config($configarray,'smtp_port','25'),5,5) ?></td>
      </tr>
      <tr>
        <th>SMTP SSL?</th>
        <td><? echo oz_render_select('oz_smtp_ssl',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'smtp_ssl',FALSE)?1:0) ?></td>
      </tr>
      <tr>
        <th>SMTP Auth Required?</th>
        <td><? echo oz_render_select('oz_smtp_auth',array(1=>'Yes',0=>'No'), tmp_oz_get_config($configarray,'smtp_auth',FALSE)?1:0) ?></td>
      </tr>
      <tr>
        <th>SMTP Auth User:Password</th>
        <td><? echo oz_render_input('oz_smtp_user',tmp_oz_get_config($configarray,'smtp_user',''),20,100) ?>:<? echo oz_render_input('oz_smtp_pass',tmp_oz_get_config($configarray,'smtp_pass',''),20,100) ?></td>
      </tr>
      <tr <? tmp_oz_render_css($configurable,'mailer') ?>>
        <th>Preferred Mail Format</th>
        <td><? echo oz_render_select('oz_mail_format', array('text'=>'Text','html'=>'HTML'), tmp_oz_get_config($configarray,'mail_format','text')) ?></td>
      </tr>
      
    </table>
    <br/>
    <br/>
    <input type="submit" name="oz_save" value="Save Settings" />
    <input type="hidden" name="oz_unicode" value="&#21513;" />
  </form>

 <br/><br/><div>For more information, please visit <a href="http://www.octazen.com" target="_blank">http://www.octazen.com</a></div> 
</div>
<?
	$html = ob_get_contents();
	ob_end_clean();
	return $html;
}	
?>