<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
//if (!defined('__ABI')) die('Please include abi.php to use this inviter component!');

define('_OZ_INVITER',1);

global $_OZI_CALLBACKS;
$_OZI_CALLBACKS = array(
	'get_invite_message' => 'oz_get_invite_message',
	'send_emails' => 'oz_send_emails',
	'filter_contacts' => 'oz_filter_contacts',
	'get_form_snippet' => 'oz_get_form_snippet',
	'presend_invites' => 'oz_presend_invites',
	'add_friends' => 'oz_add_friends',
);

global $_OZI_STATE;
$_OZI_STATE = NULL;

global $_OZI_DIR;
$_OZI_DIR = dirname(__FILE__);


include(dirname(__FILE__).'/lib/ozi_tools.php');
if (file_exists(dirname(__FILE__).'/lib/ozi_fbconnect.php')) include(dirname(__FILE__).'/lib/ozi_fbconnect.php');
include(dirname(__FILE__).'/ozinviter_lang.php');
include(dirname(__FILE__).'/ozinviter_config.php');
if (file_exists(dirname(__FILE__).'/lib/ozi_stats.php')) include(dirname(__FILE__).'/lib/ozi_stats.php');

$ozi_configfilename = dirname(__FILE__).'/settings/config.php';
if (file_exists($ozi_configfilename)) {
	global $_OZ_CONFIG;
	$_ozi_oldconfig = $_OZ_CONFIG;
	include($ozi_configfilename);
	$_OZ_CONFIG = array_merge($_ozi_oldconfig,$_OZ_CONFIG);
	unset($_ozi_oldconfig);
}
unset($ozi_configfilename);
//include(dirname(__FILE__).'/settings/config.php');



define('_OZ_STATE_INITIAL',0);
define('_OZ_STATE_LOGGING_IN',1);
define('_OZ_STATE_FETCHING_CONTACTS',2);
define('_OZ_STATE_SELECT_CONTACTS',3);
define('_OZ_STATE_SENDING_INVITES',4);
define('_OZ_STATE_FINISHED',5);

define('_OZ_STATE_SELECT_MEMBERS',6); //new. Selecting existing members to add as friend
define('_OZ_STATE_ADD_FRIENDS',7);	//new. Adding members as friend


class OzState
{
	var $inviter;	//The inviter object instance
	var $contacts;	//??? UNUSED?
	var $members;
	var $state;
	var $view;	//Current view
	var $svc_id;

	//For stats	
	var $record_id;
	
	//var $selected_contacts;
	function OzState() {$this->reset();$params=array();}
	function reset () {$this->state=_OZ_STATE_INITIAL;$this->inviter=ozi_new_ozinviter();$this->contacts=NULL;$this->members=NULL;$this->view='selector';$this->svc_id=NULL;$this->record_id=NULL;}
	function save_contacts ($contacts) {
		global $_OZI_CALLBACKS;
		$func = $_OZI_CALLBACKS['add_friends'];
		if (ozi_get_config('use_add_as_friend',TRUE) && function_exists($func)) {
			$this->members = array();
			$this->contacts = array();
			foreach ($contacts as $c) {
				if (isset($c['member_id'])) $this->members[]=$c;
				else $this->contacts[]=$c;
			}
		}
		else {
			$this->contacts = $contacts;
			$this->members = NULL;
		}
	}
}


function ozi_render_form_snippet() {
	global $_OZI_CALLBACKS;
	$func = $_OZI_CALLBACKS['get_form_snippet'];
	$html = function_exists($func) ? $func() : '';
	//For magic quote test
	$html.='<input type="hidden" name="oz_mq" value="\'"/>';
	return $html;
}

//--------------------------------------------------
//Lookup text string 
//--------------------------------------------------
function oz_text($key) {
	global $_OZINVITER_LANG;
	return isset($_OZINVITER_LANG[$key]) ? $_OZINVITER_LANG[$key] : $key;
}

//--------------------------------------------------
//Compile and evaluate view
//--------------------------------------------------
function _oz_eval_template ($templatefile) {
	//Check if template already present in file system and that it's up to date.
	//If it is, then reuse it using include.
	$src = file_get_contents($templatefile);
	$php = '';
	$i = 0;
	$n = strlen($src);
	while ($i<$n) {
		$i2 = strpos($src,'{{',$i);
		if ($i2===FALSE) {$php .= substr($src,$i,$n-$i);break;}
		$i3 = strpos($src,'}}',$i2+2);
		if ($i3===FALSE) {$php .= substr($src,$i,$n-$i);break;}
		if ($i2>$i) $php.=substr($src,$i,$i2-$i);
		$key = substr($src,$i2+2,$i3-$i2-2);
		$php.='<? echo oz_text(\''.$key.'\'); ?>';
		$i = $i3+2;
	}
	return eval(" \r\n?>".$php."<? \r\n");
}

//--------------------------------------------------
//Send invitation either through the social network's private messaging,
//or through email (calls oz_send_email()).
//
//Allows for personalization of messages.
//
//$ozinviter - OzInviter instance
//$contacts  - Array of contacts, where each contact is an associative array containing name,email,id,uid fields.
//				Required Keys: id, email (for email contacts), uid (for social network contacts)
//
//This function rarely needs to be modified.
//--------------------------------------------------
function _oz_send_invitation (&$ozinviter, &$contacts, $personal_message=NULL)
{
	$from_name = ozi_get_param('oz_from_name',NULL);
	$from_email = ozi_get_param('oz_from_email',NULL);

	//Build the message
	global $_OZI_CALLBACKS;
	$func = $_OZI_CALLBACKS['get_invite_message']	;
	$msg = $func($from_name,$from_email,$personal_message);
	$subject = $msg['subject'];
	$text_body = $msg['text_body'];
	$html_body = $msg['html_body'];
	
	//If present, we'll use the service-specific messages, in the format of "text_body.is_twitter", etc.
	//Useful for messages customized for Twitter, Friendster, etc.
	$sid = ozi_get_current_service_id();
	if ($sid===NULL) $sid='';
	$tkey = 'text_body.'.$sid;
	$hkey = 'html_body.'.$sid;
	if (isset($msg[$tkey])) $text_body = $msg[$tkey];
	else if (strpos($sid,'is_')===0 && isset($msg['text_body.is'])) $text_body = $msg['text_body.sn'];
	if (isset($msg[$hkey])) $html_body = $msg[$hkey];
	else if (strpos($sid,'is_')===0 && isset($msg['html_body.is'])) $html_body = $msg['html_body.sn'];
	
	if (ozi_get_config('allow_personal_message',TRUE))
	{
		$text_body = str_replace('{PERSONALMESSAGE}',$personal_message==NULL?'':$personal_message,$text_body);
		$html_body = str_replace('{PERSONALMESSAGE}',$personal_message==NULL?'':htmlspecialchars($personal_message,ENT_COMPAT,'UTF-8'),$html_body);
	}

	global $_OZI_CALLBACKS;
	$func = $_OZI_CALLBACKS['presend_invites'];
	if (function_exists($func)) $func($contacts);
	if (function_exists('ozi_stats_record_invite')) ozi_stats_record_invite($contacts);

	//If inviter isn't a social network, then it can only import and not send emails.
	$res = is_null($ozinviter) ? OZE_UNSUPPORTED_OPERATION : $ozinviter->send_messages($contacts,$subject,$text_body);
	if ($res===OZE_UNSUPPORTED_OPERATION)
	{
		$recplist = array();

		//----------------------------------------------------------------	
		//Send invitation by email.
		$cl = array();
		$n = count($contacts);
		for ($i=0; $i<$n; $i++) {
			$c = &$contacts[$i];
			if (!is_array($c)) $c2=array('type'=>'email','id'=>$c,'email'=>$c);
			else $c2 = $c;
			$email = $c2['email'];
			//$email = is_array($r) ? (isset($r['email']) ? $r['email'] : '') : $r;
			if (!empty($email) && ozi_valid_email($email)) 
			{
				$cl[]=$c2;
				$recplist[] = $email;
			}
		}
		global $_OZI_CALLBACKS;
		$func = $_OZI_CALLBACKS['send_emails'];
		$func($from_name,$from_email,$cl,$personal_message);
		//oz_send_emails($cl,$subject,$text_body,$html_body);
		//----------------------------------------------------------------	

		//Store recipients list to be presented in output		
		$_REQUEST['oz_recipients'] = $recplist;
		$res = OZE_SUCCESS;
	}
	//Other errors include OZE_CAPTCHA, etc
	
	return $res;
}

//--------------------------------------------------
//Get relative/absolute path to the resource (res) folder,  terminated by '/'
//--------------------------------------------------
function oz_get_resource_path ()
{
	//Defaults to "./res/" URI path relative to the current url.
	//This may be changed to point to some other folders in case Apache mod_rewrite or
	//SEO friendly urls are used and the "./res/" path doesn't point to correct location.
	return $_REQUEST['oz_res_uri'];
}

function oz_get_privacy_policy_path() 
{
	return oz_get_resource_path().'privacy.html';
}

function oz_is_greeting_view()
{
	return !isset($_POST['oz_state']);
}

function _ozi_process_contacts (&$contacts) {
	global $_OZI_STATE;
	global $_OZI_CALLBACKS;
	
	//Run through contacts filter
	$func = $_OZI_CALLBACKS['filter_contacts'];
	if (function_exists($func)) $func($contacts);
	
	//Store contacts list in request				
	$_OZI_STATE->save_contacts($contacts);
	
	//Update stats
	if (function_exists('ozi_stats_record_import')) ozi_stats_record_import($contacts);

	//Split into member and non-member lists if required
	global $_OZI_CALLBACKS;
	$func = $_OZI_CALLBACKS['add_friends'];

	if (ozi_get_config('use_add_as_friend',FALSE) && !empty($_OZI_STATE->members) && function_exists($func)) {
		$_OZI_STATE->state = _OZ_STATE_SELECT_MEMBERS;
		$_OZI_STATE->view = 'members';
	}
	else {
		$_OZI_STATE->state = _OZ_STATE_SELECT_CONTACTS;
		$_OZI_STATE->view = 'contacts';
	}
}


/**
 * Handle login
 */
function _ozi_handle_login() {
	global $_OZI_STATE;
	
	//Create the inviter and attempt login
	$svcid = $_REQUEST['oz_service'];
	$login = ozi_get_param('oz_auth_login','');
	$password = ozi_get_param('oz_auth_password','');
	$authstr = ozi_get_param('oz_authstr','');
	
	
	if ((empty($login) || empty($password)) && empty($authstr))
	{
		return OZE_AUTHENTICATION_FAILED;
	}
	else
	{
		//It's best we reset the state and create a new OzInviter instance in case 
		//user hits reload, causing the login sequence to fail (since user already logged in)
		$_OZI_STATE->reset();
		$_OZI_STATE->svc_id = $svcid;
		$_OZI_STATE->state = _OZ_STATE_LOGGING_IN;
		if (!empty($authstr)) $res = $_OZI_STATE->inviter->auth($authstr,$svcid);
		else $res = $_OZI_STATE->inviter->login($login,$password,$svcid);
		if ($res==OZE_SUCCESS)
		{
			//Not used for now
			//$svc_id2 = $_OZI_STATE->inviter->get_service_id();
			
			//Login successful. Try fetching contacts now. 
			$_OZI_STATE->state = _OZ_STATE_FETCHING_CONTACTS;
			$res = $_OZI_STATE->inviter->fetch_contacts();
			
			//Switch to contacts list view if successful.
			if (is_array($res))
			{
				_ozi_process_contacts($res);
				$res = OZE_SUCCESS;
			}
		}
		return $res;
	}
}

/**
 * Handle captcha answer
 */
function _ozi_handle_captcha() {
	global $_OZI_STATE;
		
	if ($_OZI_STATE->inviter==NULL)
	{
		$_OZI_STATE->view = 'selector';	//Go back to login page if we're done
		return OZE_SUCCESS;
	}
	else
	{
		$answer = ozi_get_param('oz_captcha_answer');
		$res = $_OZI_STATE->inviter->answer_captcha($answer);
		if ($res===OZE_SUCCESS || is_array($res))
		{
			//Captcha for login phase successful. Try fetching contacts.
			if ($_OZI_STATE->state == _OZ_STATE_LOGGING_IN)
			{
				//Login successful. Try fetching contacts now. 
				$_OZI_STATE->state = _OZ_STATE_FETCHING_CONTACTS;
				$res = $_OZI_STATE->inviter->fetch_contacts();
				//Switch to contacts list view if successful.
				if (is_array($res))
				{
					_ozi_process_contacts($res);
					$res = OZE_SUCCESS;
				}
			}
			//Captcha for fetch contacts successful. Next step is to select friends.
			else if ($_OZI_STATE->state==_OZ_STATE_FETCHING_CONTACTS)
			{
				$_OZI_STATE->state = _OZ_STATE_SELECT_CONTACTS;
				//$res MUST be an array right now
				_ozi_process_contacts($res);
				$res = OZE_SUCCESS;
			}
			//Captcha for send invites successful.
			else if ($_OZI_STATE->state==_OZ_STATE_SENDING_INVITES)
			{
				$_OZI_STATE->state = _OZ_STATE_FINISHED;
				$_OZI_STATE->view = 'finished';
			}
			else
			{
				//??
			}
			//Just to be safe...
			if (is_array($res)) $res=OZE_SUCCESS;
		}
		
		return $res;
	}

}

/**
 * Handle cancellation of captcha challenge
 */
function _ozi_handle_cancel_captcha() {
	global $_OZI_STATE;
	
	//If captcha is caused by sending contacts, then cancellation causes
	//user to go back to contacts list
	if ($_OZI_STATE->state==_OZ_STATE_SENDING_INVITES)
	{
//		$_REQUEST['oz_contacts'] = $_OZI_STATE->contacts;
		$_OZI_STATE->state = _OZ_STATE_SELECT_CONTACTS;
		$_OZI_STATE->view = 'contacts';
		return OZE_SUCCESS;
	}
	//In all other cases (login captcha, fetch contacts captcha,etc), go back to starting screen
	else
	{
		$_OZI_STATE->reset();
		$_OZI_STATE->view = 'selector';
		return OZE_SUCCESS;
	}
}

/**
 * Handle user clicking on "Send Invites" button
 */
function _ozi_handle_send_invites() {
	global $_OZI_STATE;
		
	if (isset($_REQUEST['oz_cid']))
	{
		$_OZI_STATE->state = _OZ_STATE_SENDING_INVITES;
		$cids = $_REQUEST['oz_cid'];
		
		//Translate contact IDs to contacts
		$cmap = array();
		$contacts = array();
		if ($_OZI_STATE->contacts!=NULL) foreach ($_OZI_STATE->contacts as $c) $cmap[$c['id']]=$c;
		foreach ($cids as $cid) if (isset($cmap[$cid]))	$contacts[] = $cmap[$cid];
		
		$msg = ozi_get_param('oz_message',NULL);
		$res = _oz_send_invitation($_OZI_STATE->inviter,$contacts,$msg);
/*			
		$res = _oz_send_invitation($_OZI_STATE->inviter,$cids);
		
		$msg = oz_get_invite_message();
		$subject = $msg['subject'];
		$text_body = $msg['message'];
		$res = $_OZI_STATE->inviter->send_messages($cids,$subject,$text_body);
*/			
		if ($res===OZE_SUCCESS)
		{
			$_OZI_STATE->state = _OZ_STATE_FINISHED;
			$_OZI_STATE->view = 'finished';
		}
	}
	return $res;
}

function _ozi_handle_skip_add_friends() {
	global $_OZI_STATE;
	
	//Next view is non-member selection, or finished (if no non-members)
	if (!empty($_OZI_STATE->contacts)) {
		$_OZI_STATE->state = _OZ_STATE_SELECT_CONTACTS;
		$_OZI_STATE->view = 'contacts';
	}
	else {
		$_OZI_STATE->state = _OZ_STATE_FINISHED;
		$_OZI_STATE->view = 'finished';
	}
}

/**
 * Handle user click on "Add as friend"
 */
function _ozi_handle_add_friends() {
	global $_OZI_STATE;
	
	$_OZI_STATE->state = _OZ_STATE_ADD_FRIENDS;
	$mids = isset($_REQUEST['oz_mid']) ? $_REQUEST['oz_mid'] : array();
	
	if (!empty($mids)) {
		$msg = ozi_get_param('oz_message',NULL);
	
		global $_OZI_CALLBACKS;
		$func = $_OZI_CALLBACKS['add_friends'];
		if (function_exists($func)) $func($mids);
	}

	//Next view is non-member selection, or finished (if no non-members)
	if (!empty($_OZI_STATE->contacts)) {
		$_OZI_STATE->state = _OZ_STATE_SELECT_CONTACTS;
		$_OZI_STATE->view = 'contacts';
	}
	else {
		$_OZI_STATE->state = _OZ_STATE_FINISHED;
		$_OZI_STATE->view = 'finished';
	}
	
	return OZE_SUCCESS;
}

/**
 * Handle manual invite
 */
function _ozi_handle_manual() {
	global $_OZI_STATE;

	$_OZI_STATE->svc_id = 'manual';
	$_OZI_STATE->state = _OZ_STATE_SENDING_INVITES;
	$_OZI_STATE->record_id = NULL;

	if (isset($_REQUEST['oz_cids'])) $cids = preg_split("/[\s,;]+/", $_REQUEST['oz_cids'], -1, PREG_SPLIT_NO_EMPTY);
	else $cids = $_REQUEST['oz_cid'];
	$msg = ozi_get_param('oz_message',NULL);
	$inviter = NULL;
	$contacts = array();
	foreach ($cids as $cid) {
		if (ozi_valid_email($cid))
			$contacts[]=array('id'=>$cid,'email'=>$cid);
	}

	//For manual, we're basically "importing" it as well
	if (function_exists('ozi_stats_record_import')) ozi_stats_record_import($contacts);

	//TODO: DO WE FILTER THE CONTACTS LIST?

	$res = _oz_send_invitation($inviter,$contacts,$msg);
	if ($res===OZE_SUCCESS)
	{
		$_OZI_STATE->state = _OZ_STATE_FINISHED;
		$_OZI_STATE->view = 'finished';
	}
	return $res;
}

/**
 * Handle uploaded file
 */
function _ozi_handle_upload() {
	global $_OZI_STATE;
	
	$_OZI_STATE->record_id = NULL;
	
	if (is_uploaded_file($_FILES['oz_file']['tmp_name'])) 
	{
		$filename = $_FILES['oz_file']['tmp_name'];
		if (file_exists($filename)) 
		{
			//TODO: What character set encoding is the file?
			$data = file_get_contents($filename);
			if (!empty($data)) {
				$_OZI_STATE->inviter = ozi_new_ozinviter();
			
				//Parse the CSV file
				$format = $_REQUEST['oz_file_format'];
				$res = $_OZI_STATE->inviter->parse_contacts_file($data,$format);
				$_OZI_STATE->svc_id = $format;
				/*
				if ($format=="file_olcsv") $res = $_OZI_STATE->inviter->parse_contacts_file($data,'olcsv');
				else if ($format=="file_oecsv") $res = $_OZI_STATE->inviter->parse_contacts_file($data,'oecsv');
				else if ($format=="file_wmcsv") $res = $_OZI_STATE->inviter->parse_contacts_file($data,'oecsv');
				else if ($format=="file_tbldif") $res = $_OZI_STATE->inviter->parse_contacts_file($data,'tbldif');
				else $res = OZE_UNSUPPORTED;
				*/
				
				//Switch to contacts list view if successful.
				if (is_array($res))
				{
					_ozi_process_contacts($res);
				}
			}
			unlink($filename);
		}
	}
	return OZE_SUCCESS;
}

/**
 * Handle ActiveX/Desktop Contacts Importer result
 */
function _ozi_handle_dabi() {
	global $_OZI_STATE;
	
	$_OZI_STATE->svc_id = 'desktop';
	$_OZI_STATE->record_id = NULL;
	
	//Extract desktop contacts importer result and decode
	$data = $_REQUEST['oz_dabi_result'];
	$i1 = strpos($data,'-----BEGIN CONTACTS-----');
	$i2 = strpos($data,'-----END CONTACTS-----');
	if ($i1===FALSE || $i2===FALSE || $i1>$i2) 
	{
		//Error! Bad data
		return OZE_INVALID_FILE_FORMAT;
	}
	else 
	{
		//$data = $matches[1];
		$i1 += 24; //Skip the header
		$data = trim(substr($data,$i1,$i2-$i1));
	
		//Base64-decode
		$data = base64_decode($data);
	
		//Decrypt with key
		$ckey = base64_decode(ozi_get_config('desktopimporter_decrypt_key',''));
		$data = oz_dabi_decrypt($ckey,$data);
	
		//Decompress
		$data = @gzuncompress($data);
		if ($data===false) 
		{
			//Error
			return OZE_INVALID_FILE_FORMAT;
		}
		else 
		{
			//#################################################################################
			//Extract contacts from the data and print to screen
			//#################################################################################
			$cl= oz_dabi_extract_contacts($data);
			
			//Convert Desktop contacts to normal contacts
			_ozi_process_contacts($cl);
			return OZE_SUCCESS;
		}
	}
}

//--------------------------------------------------
//Render the inviter and returns the generated HTML
//--------------------------------------------------
function oz_render_inviter($resuri='./res/',$resdir=NULL)
{
	global $_OZI_STATE;

	//If character set of language file is not utf-8, then perform character set conversion
	$charset = ozi_get_config('charset.lang','UTF-8');
	$charset2 = strtolower($charset);
	if ($charset2!='utf-8' && $charset2!='utf8') {
		static $lang_converted = FALSE;
		if (!$lang_converted) {
			global $_OZINVITER_LANG;
			$a = array();
			foreach ($_OZINVITER_LANG as $k=>$v) {
				if (function_exists('mb_convert_encoding')) $v = @mb_convert_encoding($v, 'utf-8', $charset);
				else if (function_exists('iconv')) $v = @iconv($charset, 'utf-8', $v);
				$a[$k] = $v;
			}
			$_OZINVITER_LANG = $a;
			$lang_converted = TRUE;
			unset($a);
		}
	}

	ob_start();

	//Check if checkinstall is present?
	$checkfile = dirname(__FILE__).'/checkinstall.php';
	if (file_exists($checkfile)) {
		echo '<b style="color:red;background-color:yellow">WARNING. Please remove the file '.htmlspecialchars(realpath($checkfile)).' !</b><br/>';
	}

	//Save resource path
	$n = strlen($resuri);
	$c = $resuri[$n-1];
	if ($c!=='/' && $c!=='\\') $resuri.='/';
	$_REQUEST['oz_res_uri'] = $resuri;
	$_REQUEST['oz_res_absurl'] = ozi_make_absolute_url(oz_get_current_url(),$resuri);
	if ($resdir===NULL) $resdir = dirname(__FILE__).'/res/';
	$n = strlen($resdir);
	$c = $resdir[$n-1];
	if ($c!=='/' && $c!=='\\') $resdir.='/';
	$_REQUEST['oz_res_dir'] = $resdir;

	$_OZ_VIEWS = array(
		'selector'=>dirname(__FILE__).'/views/view_selector.php',
		'captcha'=>dirname(__FILE__).'/views/view_captcha.php',
		'members'=>dirname(__FILE__).'/views/view_members.php',
		'contacts'=>dirname(__FILE__).'/views/view_contacts.php',
		'finished'=>dirname(__FILE__).'/views/view_finished.php'
	);

	//===================================================================================
	//User first time browsing to this page
	//===================================================================================
	if (!isset($_POST['oz_state']))
	{
		$_REQUEST['oz_state'] = oz_generate_state_filename();
		$_OZI_STATE = new OzState;
		$_OZI_STATE->view = 'selector';
	}
	else
	{
	/*
	echo "[REQUEST]<hr/>";
	echo '<pre>';
	echo htmlspecialchars(var_export($_REQUEST,true));
	echo '</pre>';
	echo "[STATE]<hr/>";
	echo '<pre>';
	echo htmlspecialchars(var_export($state,true));
	echo '</pre>';
	echo '<hr/>';
	*/
		
		
	
		$res = OZE_SUCCESS;
		
		//Load state. Create one if no state as yet.
		$_OZI_STATE = oz_load_state($_REQUEST['oz_state']);
		if ($_OZI_STATE===NULL) {$_REQUEST['oz_state'] = oz_generate_state_filename();$_OZI_STATE=new OzState;}	
		$_OZI_STATE->view = $_OZI_STATE->view;

		if (empty($_OZI_STATE->view)) $_OZI_STATE->view='selector';
	
		//===================================================================================
		//User selected webmail/social network service
		//===================================================================================
		/*
		if (isset($_REQUEST['ozbtn_select']))
		{
			$svcid = $_REQUEST['oz_service'];
			if (strpos($svcid,'file')===0)
			{
				if ($svcid=='file_oecsv') $_REQUEST['oz_file_format']='oecsv';
				else if ($svcid=='file_wmcsv') $_REQUEST['oz_file_format']='wmcsv';
				else if ($svcid=='file_tbldif') $_REQUEST['oz_file_format']='tbldif';
				//if ($svcid=='file' || $svcid=='file_olcsv') $_REQUEST['oz_file_format']='olcsv';
				else $_REQUEST['oz_file_format']='olcsv';
				$_OZI_STATE->view = 'upload';
				$res = OZE_SUCCESS;
			}
			else if ($svcid=='manual')
			{
				$_OZI_STATE->view = 'manual';
				$res = OZE_SUCCESS;
			}
			else if ($svcid=='bookmark')
			{
				$_OZI_STATE->view = 'bookmark';
				$res = OZE_SUCCESS;
			}
			else if (strpos($svcid,'is_')===0)
			{
				$_OZI_STATE->view = 'login';
				$res = OZE_SUCCESS;
			}
			else 
			{
				$_OZI_STATE->view = 'login';
				$res = OZE_SUCCESS;
			}
		}
		*/
	
		//===================================================================================
		//Call handler
		//===================================================================================
		else if (isset($_REQUEST['ozbtn_login']) || isset($_REQUEST['ozbtn_login_x']) || isset($_REQUEST['oz_authstr']))
		{
			$res = _ozi_handle_login();
		}
		else if (isset($_REQUEST['ozbtn_captcha']) || isset($_REQUEST['ozbtn_captcha_x']))
		{
			$res = _ozi_handle_captcha();
		}
		else if (isset($_REQUEST['ozbtn_cancel_captcha']) || isset($_REQUEST['ozbtn_cancel_captcha_x']))
		{
			$res = _ozi_handle_cancel_captcha();
		}
		else if (isset($_REQUEST['ozbtn_contacts']) || isset($_REQUEST['ozbtn_contacts_x']))
		{
			$res = _ozi_handle_send_invites();
		}
		else if (isset($_REQUEST['ozbtn_members']) || isset($_REQUEST['ozbtn_members_x']))
		{
			$res = _ozi_handle_add_friends();
		}
		else if (isset($_REQUEST['ozbtn_members_skip']) || isset($_REQUEST['ozbtn_members_skip_x']))
		{
			$res = _ozi_handle_skip_add_friends();
		}
		else if (isset($_REQUEST['ozbtn_manual']) || isset($_REQUEST['ozbtn_manual_x']))
		{
			$res = _ozi_handle_manual();
		}
		else if (isset($_REQUEST['ozbtn_upload']) || isset($_REQUEST['ozbtn_upload_x']))
		{
			$res = _ozi_handle_upload();
		}
		else if (isset($_REQUEST['oz_dabi_result']))
		{
			$res = _ozi_handle_dabi();
		}
	

	
		//===================================================================================
		//Handle errors
		//===================================================================================
		//Captcha was raised?
		if ($res===OZE_CAPTCHA)
		{
			$imageurl = $_OZI_STATE->inviter->get_captcha_image_url();
			//Service supports answering captcha challenges
			if (!empty($imageurl))
			{
				$_REQUEST['oz_captcha_image'] = $imageurl;
				$_REQUEST['oz_errmsg'] = oz_text('ERROR_CAPTCHA');
				$_REQUEST['oz_captcha_remaining_count'] = $_OZI_STATE->inviter->get_remaining_count();
				$_OZI_STATE->view = 'captcha'; //_file = dirname(__FILE__).'/view_captcha.php';
			}
			//Service doesn't support answering of captcha challenge
			else
			{
				$_REQUEST['oz_errmsg'] = oz_text('ERROR_CAPTCHA_PRESENTED');
				//What view eh?
			}
			
			//If user cancels the captcha, where do we go?
			//If the captcha is successful, go where?
			
	//		$_OZI_STATE->captcha_cancel_view = $view;
	//		$_OZI_STATE->captcha_success_view = $view;
		}
		else if ($res==OZE_AUTHENTICATION_FAILED)
		{
			$_REQUEST['oz_errmsg'] = oz_text('ERROR_AUTH');
		}
		else if (is_int($res))
		{
			//Error. Show the error message
			if ($res!=OZE_SUCCESS)
			{
				//$_REQUEST['oz_errmsg'] = oz_get_error_message($res);
				$_REQUEST['oz_errmsg'] = oz_text('ERROR_'.$res);
			}
		}		
	}
?>
<script src="<? echo htmlspecialchars(oz_get_resource_path()) ?>domready2.js" type="text/javascript"></script>
<script type="text/javascript">
var oz_requested_notify_resize = false;
//var oz_resize_timeout = null;
function ozNotifyResize() {
	if (!oz_requested_notify_resize) {
		oz_requested_notify_resize = true;
		DomReady.ready(function() {
			oz_requested_notify_resize = false;
			if (typeof(ozOnResized)=="function") ozOnResized();		
		});
	}
	//if (oz_resize_timeout==null) {
	//	oz_resize_timeout=setTimeout('clearTimeout(oz_resize_timeout);oz_resize_timeout=null;if (typeof(ozOnResized)=="function") ozOnResized();',1);
	//}
}

var oz_requested_viewchange = false;
var oz_viewchange_timeout = null;
var oz_viewchange_view = null;
function ozNotifyViewChange(view) {
	oz_viewchange_view = view;
	
	if (!oz_requested_viewchange) {
		oz_requested_viewchange = true;
		DomReady.ready(function() {
			oz_requested_viewchange = false;
			if (typeof(ozOnViewChanged)=="function") ozOnViewChanged(oz_viewchange_view);
		});
	}

	//if (oz_viewchange_timeout==null) {
	//	oz_viewchange_timeout=setTimeout('clearTimeout(oz_viewchange_timeout);oz_viewchange_timeout=null;if (typeof(ozOnViewChanged)=="function") ozOnViewChanged(oz_viewchange_view);',1);
	//}
}

function ozSetDisplayStyle(ids,style) {
	var ida = ids.split(',');
	for (var i=0; i<ida.length; i++)
	{
		var ele = document.getElementById(ida[i]);
		if (ele!=null && ele!=undefined) {
			ele.style.display = style;
			ozNotifyResize();
		}
	}
}

function ozHide(d) {ozSetDisplayStyle(d,'none');} //var ele = document.getElementById(d);if (ele!=null && ele!=undefined) ele.style.display = "none";}
function ozShow(d) {ozSetDisplayStyle(d,'block');} //var ele = document.getElementById(d);if (ele!=null && ele!=undefined) ele.style.display = "block";}

function ozPopUp(url,frame,width,height) {
	var left = (screen.width) ? (screen.width-width)/2 : 320;
	var top = (screen.height) ? (screen.height-height)/2 : 240;
	var win = open(url,frame,'toolbar=no,resizable=yes,scrollbars=yes,directories=no,menubar=no,status=yes,width='+width+',height='+height+',top='+top+',left='+left);
	win.focus();
	return win;
}

function ozOnSubmit()
{
	//Hide all and loader panel
	document.getElementById('ozpanel_all').style.display="none";
	document.getElementById('ozpanel_please_wait').style.display="block";
	ozNotifyResize();
	ozNotifyViewChange('submitting');
	return true;
}
function ozStartAgain2() {
	document.forms.ozform_startagain.submit();
}

</script>

<div id="ozpanel_please_wait"><center><? echo oz_text('PLEASEWAIT') ?></center></div>
<form name="ozform_startagain" method="post" style="display:none;">
<? echo ozi_render_form_snippet(); ?>
</form>
<div id="ozpanel_all">
<?
	//If error message is present, then display it
	if (isset($_REQUEST['oz_errmsg']))
	{
		$err = $_REQUEST['oz_errmsg'];
		echo '<div id="oz_error">'.htmlspecialchars($err).'</div>';
	}

	$view = $_OZI_STATE->view;
	
	//Save/Delete state
	if ($_OZI_STATE->state===_OZ_STATE_FINISHED) 
	{
		oz_delete_state($_REQUEST['oz_state']);
		$_OZI_STATE->reset();
	}	
	else oz_save_state($_REQUEST['oz_state'],$_OZI_STATE);

	//Store some common items on request
	$_REQUEST['oz_inviter'] = $_OZI_STATE->inviter;
	$_REQUEST['oz_contacts'] = $_OZI_STATE->contacts;
	$_REQUEST['oz_members'] = $_OZI_STATE->members;
		
	//Split contacts into 2 parts
	//Non-member contacts
	//Member contacts?
	




	
//	echo '<div id="oz_inviter">';


	//Render the view	
	
//echo "[VIEW=".$view."]";
//echo "[VIEWFILE=".$_OZ_VIEWS[$view]."]";
	
	if (isset($_OZ_VIEWS[$view])) {
		_oz_eval_template($_OZ_VIEWS[$view]);
		//include($_OZ_VIEWS[$_OZI_STATE->view]);
	}
	
	
//	if ($_OZI_STATE->view!='login')
//	{
//		echo '<div class="oz_footer"><a href="'.$_SERVER['REQUEST_URI'].'">Start again</a></div>';
//	}
	
//	echo '</div>';
//	echo '<div id="oz_footer">Powered by <a href="http://www.octazen.com" target="_blank">Octazen Solutions Invite Engine</a></div>';
	?>
    
</div>
<?

	
//echo '<pre>';
//echo htmlspecialchars(var_export($_OZI_STATE,true));
//echo '</pre>';


	$html = "\r\n<!-- OCTAZEN INVITER COMPONENT BEGIN -->\r\n";
	$html .= ob_get_contents();
	$html .= '<script type="text/javascript">//<![CDATA['."\r\n".'if (typeof(ozOnLoaded)=="function") ozOnLoaded();'."\r\n".'//]]></script>';
	$html .= "\r\n<!-- OCTAZEN INVITER COMPONENT END -->\r\n";
	ob_end_clean();
	
	//If character set is not utf-8, then perform character set conversion
	$charset = ozi_get_config('charset','UTF-8');
	$charset2 = strtolower($charset);
	if ($charset2!='utf-8' && $charset2!='utf8') {
		if (function_exists('mb_convert_encoding')) $html = @mb_convert_encoding($html, $charset, 'utf-8');
		else if (function_exists('iconv')) $html = @iconv('utf-8', $charset, $html);
	}
	return $html;
}




function ozi_encode_header($input, $charset = 'UTF-8')
{
	$m=preg_match_all('/(\w*[\x80-\xFF]+\w*)/', $input, $matches);
	if($m)$input=mb_encode_mimeheader($input,$charset, 'Q');
	return $input;
}

//--------------------------------------------------
//Default mail sender
//--------------------------------------------------
function oz_inviter_sendmail ($from_name, $from_email, &$contacts, $subject, $text, $html)
{
	if (empty($from_name)) $from_name=ozi_get_config('from_name','');
	if (empty($from_email)) $from_name=ozi_get_config('from_email','');
				
	$sc = 0; //Mail count for smtp session
	$m = ozi_get_config('mails_per_smtp_session',10);
	$method = ozi_get_config('mailer','mail');
	$charset = ozi_get_config('mail_charset','utf-8');
	$mailer = NULL;
	
	if ($method==='smtp' && !class_exists('PHPMailer')) {
		//trigger_error('Cannot find PHPMailer class. Reverting to PHP\'s mail() function',E_USER_WARNING);
		$method='mail';
	}
	
	if (is_callable('mb_encode_mimeheader')) {
		if (!empty($from_name)) $from_name = ozi_encode_header($from_name,$charset);
		if (strpos($from_name,'=?')!==0) $from_name='"'.$from_name.'"';
		if (!empty($subject)) $subject = ozi_encode_header($subject,$charset);
	}
	
	foreach ($contacts as $c) {
		$to_name = isset($c['name']) ? $item['name'] : '';
		$to_email = $c['email'];
		//TODO: CHECK EMAIL VALID (it should be valid)

		///////////////////////////////////////////////////////////////////////			
		//Send using mail()
		///////////////////////////////////////////////////////////////////////			
		if ($method=='mail') {
			$headers = "MIME-Version: 1.0\r\n";
			

			if (empty($from_name)) $headers .= 'From: '.$from_email."\r\n";
			else $headers .= 'From: '.$from_name.' <'.$from_email.">\r\n";
			if (!empty($html)) {
				$headers .= "Content-Type: text/html;charset=$charset\r\n";
				$r = mail($to_email,$subject,$html,$headers);
			}
			else {
				$headers .= "Content-Type: text/plain;charset=$charset\r\n";
				$r = mail($to_email,$subject,$text,$headers);
			}	
		}

		///////////////////////////////////////////////////////////////////////			
		//Send using Octazen mailq
		///////////////////////////////////////////////////////////////////////			
		else if ($method=='mailq') {
			$mqconfig = array(
				'method' => $method,
				'smtp_host' => ozi_get_config('smtp_host','localhost'),
				'smtp_port' => intval(ozi_get_config('smtp_port','25')),
				'smtp_auth' => ozi_get_config('smtp_auth',FALSE),
				'smtp_ssl' => ozi_get_config('smtp_ssl',FALSE),
				'smtp_user' => ozi_get_config('smtp_user',''),
				'smtp_pass' => ozi_get_config('smtp_pass',''),
				'mail_spool' => ozi_get_config('mailq_spool',dirname(__FILE__).'/spool/'),
				//Unused values
				'default_from' => '',
				'lock_timeout' => 60,
				'mails_per_smtp_session' => 10,
				'mails_per_batch' => 100,
				'lock_file' => 'lock.pid'
			);
			mq_queue_mail($config, $from_name, $from_email, $to_name, $to_email, $subject, $text, $html);
		}
		
		///////////////////////////////////////////////////////////////////////			
		//Send using phpmailer
		///////////////////////////////////////////////////////////////////////			
		else {
			//echo "PHPMAILER(): FROM $from_name &lt;$from_email&gt;, TO $to_name &lt;$to_email&gt;<br/>";
			//flush();
			
			//Create PhpMailer instance if not available
			if ($mailer==NULL) {
				$mailer=new PHPMailer();
				$mailer->Mailer = 'smtp';
				$mailer->IsSMTP();
				$mailer->Host = ozi_get_config('smtp_host','localhost');
				$mailer->Port = intval(ozi_get_config('smtp_port','25'));
				if (ozi_get_config('smtp_ssl',FALSE)) $mailer->SMTPSecure = "ssl";
				if (ozi_get_config('smtp_auth',FALSE)) {
					$mailer->SMTPAuth = TRUE;
					$mailer->Username = ozi_get_config('smtp_user','');
					$mailer->Password = ozi_get_config('smtp_pass','');
				}
			}

			//Set from, to, subejct, etc
			$mailer->CharSet = $charset;
			$mailer->From     = $from_email;
			$mailer->FromName = $from_name;
			$mailer->ClearAddresses();
			$mailer->AddAddress($to_email, $to_name);
			$mailer->Subject = $subject;
			if (!empty($html)) {
				$mailer->IsHTML(TRUE);
				$mailer->Body = $html;
				if (!empty($text)) $mailer->AltBody = $text;
			}
			else {
				$mailer->IsHTML(FALSE);
				$mailer->Body = $html;
			}
			
			//TODO: What if error sending mail?
			$r = $mailer->Send();
			$sc++;
			if (!$r || $sc>=$m) {
				$sc=0;
				$mailer->SmtpClose();
				$mailer = NULL;
			}
		}

	}
	
	//Close Phpmailer if used
	if ($mailer!==NULL) $mailer->SmtpClose();
}

//--------------------------------------------------
//Get current service ID, returns null/blank string if none.
//--------------------------------------------------
function ozi_get_current_service_id() {
	global $_OZI_STATE;
	if (!$_OZI_STATE) return NULL;
	return $_OZI_STATE->svc_id;
}

//--------------------------------------------------
//Process a url by embedding tracking information,etc
//
//Useful only when stats is enabled. 
//In the future, this may also make use of url shorteners.
//--------------------------------------------------
function ozi_process_url ($url) {
	global $_OZI_STATE;
	if ($_OZI_STATE && function_exists('ozi_stats_enabled') && ozi_stats_enabled() && ozi_get_config('stats.track_links',FALSE)) {
		$record_id = $_OZI_STATE->record_id;
		if ($record_id===NULL || $record_id==='') return $url;	//No use if no record id
		
		$token = isset($GLOBALS['ozi_token']) ? $GLOBALS['ozi_token'] : '';
		$trackurl = $_REQUEST['oz_res_absurl'].'t/?';
		$trackurl.='id='.urlencode($record_id);
		if ($token!=='') $trackurl.='&token='.urlencode($token);
		$trackurl.='&url='.urlencode($url);
		return $trackurl;
	}
	return $url;
}

function ozi_set_member_id($member_id) {
	$GLOBALS['ozi_member_id'] = $member_id;
}
function ozi_set_token($token) {
	$GLOBALS['ozi_token'] = $token;
}

function ozi_get_owner_email() {
	global $_OZI_STATE;
	if (!$_OZI_STATE || !$_OZI_STATE->inviter) return NULL;
	return $_OZI_STATE->inviter->get_owner_email();
}

?>