<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Alice.it contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['aliceit'] = array('type'=>'abi', 'label'=>'Alice.it', 'class'=>'AliceItImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//AliceItImporter. To be released on 23 July 2008.
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class AliceItImporter extends WebRequestor {

	var $TOKENS_REGEX = "/mainFrameset\\.aspx\\?t=([^&]+)&spc=([^&\\s\"']+)/ims";
	var $CONTACT_REGEX = "/<input\\s+name=\"[^\"]+?\\\$MsgID\"[^>]*?value=\"(.*?)####[^>]*>.*?<font[^>]*>\\s*<b[^>]*>\\s*(.*?)\\s*<\/b>\\s*<\/font>/ims";

	var $t;
	var $spc;

	//@api
	function getInfo () {
		return array('id'=>'alice.it');
	}

	//@api
	function login ($loginemail, $password) {
	
		$this->setOwnerEmail($loginemail);
		$loginemail = strtolower($loginemail);
		$parts = $this->getEmailParts ($loginemail);
		$id = $parts[0];
		$domain = $parts[1];

		oz_set_domain($domain);

		$form = new HttpForm;
		$form->action = "https://authsrs.alice.it/aap/validatecredential";
		$form->addField("usernameDisplay", $id);
		$form->addField("password", $password);
		$form->addField("dominio", $domain); // @alice.it
		$form->addField("login", $loginemail);
		$form->addField("pwd", $password);
		$form->addField("channel", "mail_alice"); // ???
		$form->addField("URL_OK","https://authsrs.alice.it/aap/aap_redir.jsp?entry=mail_alice"); // ??
		$form->addField("URL_KO","https://authsrs.alice.it/aap/aap_redir_ko.jsp?entry=mail_alice"); // ??
		$form->addField("servizio", "mail");
		$form->addField("msisdn", $id);
		$form->addField("username", $loginemail);
		$form->addField("user", $loginemail);
		$form->addField("a3afep","http://portale.rossoalice.alice.it/ps/ManageCodError.do?code=470&channel=hp_alice"); // ??
		$form->addField("DOMAIN", "");
		$form->addField("PASS", $password);
		$form->addField("self", "true");
		$form->addField("a3si", "none");
		$form->addField("a3st", "VCOMM");
		$form->addField("nototop", "true");
		$form->addField("a3aid", "na");
		$form->addField("a3flag", "0");
		$form->addField("a3ep", "http://communicator.alice.it/asp/login.asp"); // ?
		$form->addField("a3se","http://portale.rossoalice.alice.it/ps/ManageCodError.do?code=470&channel=hp_alice"); // ???
		$form->addField("a3dcep","http://communicator.alice.it/asp/homepage.asp?s=005"); // ?
		$form->addField("a3l", $loginemail);
		$form->addField("a3p", $password);
		$form->addField("imageField.x", "18");
		$form->addField("imageField.y", "8");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$html = $this->postForm($form);

		$url = $this->lastUrl;
		if (strpos($url,"aap_redir_ko.jsp")!==false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
		if (strpos($url,"aap/aap_redir.jsp")===false) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Did not receive expected redirection url');
		}

		$html = $this->httpGet("https://authsrs.alice.it/aap/aap_redir.jsp?entry=mail_alice");
		$html = $this->httpGet("http://auth.rossoalice.alice.it/aap/serviceforwarder?sf_dest=mail_rubrica");
		$url = $this->lastUrl;
		if (preg_match($this->TOKENS_REGEX,$url,$matches)==0) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find t and spc token');
		}
		$this->t = $matches[1];
		$this->spc = $matches[2];

		return abi_set_success();
	}

	//@api
	function logout() {
		$this->httpGet("http://aaacsc.alice.it/xsso/XSSO?_action=logout&a3ep=http%3A%2F%2Fdise.alice.it%2Fdest%2Flogout");
	}
		
	//@api
	function fetchContacts ($loginemail, $password) {
		
		$res = $this->login($loginemail,$password);
		if ($res!=_ABI_SUCCESS) return $res;

		// Extract contacts
		$html = $this->httpGet("http://rubrica.rossoalice.alice.it/Default.aspx?t=$this->t&spc=$this->spc&profile=Basic");
		$emails = array();
		$cl = array();
		preg_match_all($this->CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			$email = htmlentities2utf8(trim($val[1]));
			$name = htmlentities2utf8(trim($val[2]));
			if (empty($name)) $name=$email;
			if (abi_valid_email($email)) $cl[] = new Contact($name,$email);
		}

		return $cl;
	}
}

//alice.it (release date: 23 July 2008)
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["alice.it"] = 'AliceItImporter';
//$_DOMAIN_IMPORTERS["tin.it"] = 'AliceItImporter';
//$_DOMAIN_IMPORTERS["tim.it"] = 'AliceItImporter';
//$_DOMAIN_IMPORTERS["virgilio.it"] = 'AliceItImporter';
