<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Plaxo contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['plaxo'] = array('type'=>'abi', 'label'=>'Plaxo', 'class'=>'PlaxoImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//PlaxoImporter
/////////////////////////////////////////////////////////////////////////////////////////

//@api
class PlaxoImporter extends PortableContactsImporter {

	//@api
	function getInfo () {
		return array('id'=>'plaxo');
	}

	//@api
	function removeSuffix ($email) {
		// Remove suffix
		$email = preg_replace("/^(.*?)(\.plaxo)$/ims", '${1}', $email);
		$this->setOwnerEmail($email);
		return $email;
	}
	
	function PlaxoImporter () {
		parent::PortableContactsImporter('http://www.plaxo.com/pdata/contacts');
	}
	
	function login ($email, $password) {
		oz_set_domain('plaxo');
		return parent::login($email,$password);
	}
	
}

//plaxo
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["plaxo"] = 'PlaxoImporter';
