<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Rambler.ru contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['rambler'] = array('type'=>'abi', 'label'=>'Rambler', 'class'=>'RamblerImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//RamblerImporter
/////////////////////////////////////////////////////////////////////////////////////////
define('RamblerImporter_REQKEY_REGEX',"/var\\s+_request_key\\s*=\\s*\"([^\"]*)\";/ims");

//@api
class RamblerImporter extends WebRequestor {
	
	var $reqKey;

	//@api
	function getInfo () {
		return array('id'=>'rambler');
	}

	//@api
	function login ($loginemail, $password) {

		$parts = $this->getEmailParts ($loginemail);
		$loginid = $parts[0];
		$this->setOwnerEmail($loginemail);
		oz_set_domain($parts[1]);

		$form = new HttpForm;
		$form->action = "http://id.rambler.ru/script/auth.cgi";
		$form->addField("back", "http://mail.rambler.ru/mail/startpage");
		$form->addField("login", $loginid);
		$form->addField("passw", $password);
		$html = $this->postForm($form);
		if (strpos($this->lastUrl,'/auth.cgi')!==FALSE || strpos($html,'class="txt_error"')!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		if (!preg_match(RamblerImporter_REQKEY_REGEX,$html,$matches)) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find request key');
		}
		$this->reqKey = $matches[1];
		return abi_set_success();
	}

	//@api
	function logout() {
		$this->httpGet("http://id.rambler.ru/script/auth.cgi?back=;mode=logout;r=9f18");
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$res = $this->login($loginemail,$password);
		if ($res!=_ABI_SUCCESS) return $res;

		$html = $this->httpGet("http://mail.rambler.ru/mail/contacts.cgi?mode=json&request_key=".$this->reqKey."&result=comment");
		
		$cl = array();
		$ct = $this->getResponseHeader('Content-Type');
		if (strpos($ct,'text/x-json')!==FALSE) {
		 	$json = oz_json_decode($html,TRUE);
		 	foreach ($json as $rec) {
				if (count($rec)>=2)	{
					$name = $rec[0];
					$email = $rec[1];
					if (abi_valid_email($email)) {
						$cl[] = new Contact($name,$email);
					}
				}
			}
			return $cl;
		}
		else {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Not receiving expected json result');
		}
	}
}


// rambler.ru
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["rambler.ru"] = 'RamblerImporter';
