<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Sapo.pt contacts importer.

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['sapo'] = array('type'=>'abi', 'label'=>'Sapo.pt', 'class'=>'SapoImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//SapoImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class SapoImporter extends WebRequestor {

	var $CONTACTLIST_REGEX = "/<select[^>]*?name=\"search_results[^>]*>(.*)<\/select>/ims";
	var $CONTACT_REGEX = "/<option value=\"([^\"]*)\"[^>]*>([^<]*)<\/option>/ims";

	var $REFRESHURL_REGEX = "/\\s*\\d+\\s*;\\s*url=(.*)\\s*/ims";

	//@api
	function getInfo () {
		return array('id'=>'sapo');
	}

	function getRefreshUrl($refreshString) {
		if (preg_match($this->REFRESHURL_REGEX,$refreshString,$matches)==0) {
			return null;
		}
		return $matches[1];
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$this->setOwnerEmail($loginemail);
		oz_set_domain(oz_get_email_domain($loginemail));

		//$this->userAgent = "Mozilla/4.0 (compatible; MSIE 6.0; WINDOWS; .NET CLR 1.1.4322)";
		
		//Use FF for now. Using IE6 will cause the "refresh" header to be issued by sapo
		$this->userAgent = "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11";

		$form = new HttpForm;
		$form->addField("actionID", "");
		$form->addField("url", "");
		$form->addField("mailbox", "INBOX");
		$form->addField("frameset", "");
		$form->addField("logindata", "");
		$form->addField("imapuser", $loginemail);
		$form->addField("pass", $password);
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost("http://mail.sapo.pt/imp/redirect.php", $postData);
		if (strpos($html,"id=\"errorBox\"")!==false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		//$refresh = $this->getResponseHeader("Refresh");
		//if ($refresh!=null) {
		//	$url = $this->getRefreshUrl($refresh);
		//	$html = $this->httpGet($url);
		//	$this->lastUrl = $url;
		//}

		// sapo.pt has a crummy problem with CSV export reliability. It randomly
		// gives error. In fact, it does the same for normal web page but with lower probability.
		/*
		$form = new HttpForm;
		$form->addField("actionID", "export");
		$form->addField("exportID", "104"); // Outlook ?
		$form->addField("source", "localsql");
		$postData = $form->buildPostData();
		$this->lastUrl = $this->makeAbsolute($this->lastUrl,"/turba/data.php");
		$html = $this->httpPost("/turba/data.php/contactos?fn_ext=%2Fcontactos.csv", $postData);
		$res = abi_extract_outlook_csv($html);
		$this->close();
		return $res;
		*/

		//Due to buggy server in sapo.pt, we'll try 5 times until we get some results
		for ($tries=0; $tries<5; $tries++) {

			$html = $this->httpGet("/imp/contacts.php");
			$form = oz_extract_form_by_id($html, "contacts");
			if ($form==null) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find contacts list form');
			}
			$form->setField("source", "localsql");
			$form->setField("formname", "compose");
			$form->setField("searched", "1");
			$form->setField("sa", "");
			$form->setField("search", "");
			$form->setField("source", "localsql");
			$form->setField("display", "name");
			$postData = $form->buildPostData();
			$html = $this->httpPost($form->action, $postData);

			$al = array();
			if (preg_match($this->CONTACTLIST_REGEX,$html,$matches)==0) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find contacts list');
			}
			$html = $matches[1];

			preg_match_all($this->CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
			foreach ($matches as $val) {
				//#1 is the lastname,firstname
				$email = urldecode(trim($val[1]));
				$name =  htmlentities2utf8(trim($val[2]));
				if (abi_valid_email($email)) {
					$contact = new Contact($name, $email);
					$al[] = $contact;
				}
			}
			$this->close();
			if (count($al)>0) {
				//echo "[TRIES=$tries]";
				return $al;
			}
		}
		return array();
	}
}

//sapo.pt
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["sapo.pt"] = 'SapoImporter';
