<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Web.de contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['webde'] = array('type'=>'abi', 'label'=>'Web.de', 'class'=>'WebDeImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//WebDeImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class WebDeImporter extends WebRequestor {

	var $SI_REGEX = "/[\\?&]si=([^&]+)/ims";
	var $SID_REGEX = "/[\\?&]sid=([^&]+)/ims";
	var $si;
	var $homeUrl;

	//@api
	function getInfo () {
		return array('id'=>'web.de');
	}

	//@api
	function login ($loginemail, $password) {

		$this->homeUrl=null;

		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		$this->setOwnerEmail($loginemail);
		oz_set_domain($parts[1]);

		$form = new HttpForm;
		$form->addField("service", "freemail");
		$form->addField("server", "https://freemail.web.de");
		$form->addField("onerror", "https://freemail.web.de/msg/temporaer.htm");
		$form->addField("onfail", "https://freemail.web.de/msg/logonfailed.htm");
		$form->addField("username", $login);
		$form->addField("password", $password);
		$form->addField("rv_dologon", "Login");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost("https://login.web.de/intern/login/", $postData);
		if (strpos($html, 'Passwort vergessen')!=false ||
			strpos($html, 'vielleicht vertippt')!=false ||
			strpos($html, 'nicht erfolgreich')!=false ||
			strpos($this->lastUrl, 'failed')>0)
			{
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		if (preg_match($this->SI_REGEX,$this->lastUrl,$matches)==0) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find si');
		}
		$this->si = $matches[1];

		//Get logout link
		$this->homeUrl = $this->lastUrl;

		return abi_set_success();
	}

	//@api
	function logout () {
		//Logout
		if ($this->homeUrl!=null) {
			$location = $this->makeAbsolute($this->homeUrl,"/?si=".$this->si."&rv_logoff=true");
			$this->httpGet($location);
		}
	}

	function fetchCsv () {

		$this->lastUrl = $this->homeUrl;
		$location =  "/online/adressbuch/?si=$this->si&noscript=true";
		$html = $this->httpGet($location);

		if (preg_match($this->SID_REGEX,$this->lastUrl,$matches)==0) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find sid');
		}
		$sid = $matches[1];

		$form = new HttpForm;
		$form->addField("action", "export");
		$form->addField("sid", $sid);
		$form->addField("category", "0");
		$form->addField("language", "2");
		$form->addField("expType", "3");
		$form->addField("export", "Exportieren");
		$postData = $form->buildPostData();
		$html = $this->httpPost("/adr_action/", $postData);

/*
		//Web.de's english CSV has problem of the following: Although present in the header, the following
		//fields are actually missing from the body part, causing other columns to shift forward.
		//
		//We'll replace the header with a correct version instead.
		//
		$parts = explode("\r\n",$html,2);
		if (count($parts==2)) {
			$header = '"Title","First Name","Last Name","Company","Department","Job Title","Business Street","Business City","Business Postal Code","Business Country","Home Street","Home City","Home Postal Code","Home Country","Other Street","Other Street 2","Other Street 3","Other City","Other Postal Code","Other Country","Business Fax","Business Phone","Home Fax","Home Phone","Mobile Phone","Other Fax","Other Phone","E-mail Address","Birthday","Categories","Notes","Web Page"';
			$html = $header."\r\n".$parts[1];
		}
*/

		//Convert character set to utf-8
		//if (function_exists('mb_convert_encoding')) $html = mb_convert_encoding($html, "utf-8","ISO-8859-1");
		//else if (function_exists('iconf')) $html = iconv('ISO-8859-1', 'utf-8', $html);
		//else, we can't perform the conversion. Return raw form.

//		$res = abi_extract_outlook_csv($html);
//	 	$this->close();



		return $html;
	}



	//@api
	function fetchContacts ($loginemail, $password) {
		$res = $this->login($loginemail,$password);
		if ($res!=_ABI_SUCCESS) return $res;
		$html = $this->fetchCsv();
		$this->logout();
		if (!is_string($html)) return $html;
		$res = abi_extract_outlook_csv($html);
		return $res;
	}
}


//web.de
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["web.de"] = 'WebDeImporter';
$_DOMAIN_IMPORTERS["email.de"] = 'WebDeImporter';
