<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Email.it contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['emailit'] = array('type'=>'abi', 'label'=>'Email.it', 'class'=>'EmailItImporter');

define('EmailIt_TOKENS_REGEX',"/us=([^&]*).*?&sid=([^&]*)/ims");

/////////////////////////////////////////////////////////////////////////////////////////
//EmailItImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class EmailItImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'email.it');
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		//Remove suffix
		$loginemail = preg_replace("/^(.*?)(\.emailit)$/ims", '${1}', $loginemail);

		$this->setOwnerEmail($loginemail);

		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		//$this->domain = $parts[1];

		oz_set_domain($parts[1]);

		$this->lastUrl = 'http://wm.email.it/webmail/wm_5/login.php?action=login&home=1';

		$form = new HttpForm;
		$form->action = "http://wm.email.it/webmail/wm_5/login.php?action=login&home=1";
		$form->addField("f_user", $login);
		$form->addField("f_pass", $password);
		$form->addField("LOGIN", $login);
		$form->addField("PASSWD", $password);
		$form->addField("Act_Login", "");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$form->addField("tempomemo", "duesett");
		$html = $this->postForm($form);
		if (strpos($this->lastUrl,'/login.php')!==FALSE || strpos($html,'errlogin.php')!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		// Add cookie and get redirect location
		if (preg_match(EmailIt_TOKENS_REGEX,$this->lastUrl,$matches)==0) {
			if (preg_match(EmailIt_TOKENS_REGEX,$html,$matches)==0) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find redirect location');
			}
		}
		$us = $matches[1];
		$sid = $matches[2];

		$url = "addressbook_export.php?us=$us&sid=$sid&tid=0&lid=0&prem=0";
		
		//Email.it has bug with content-type charset, which defines utf-8 (instead of iso-8859-1)
		$html = $this->httpRequest($url, false, null, 'iso-8859-1', null, 'iso-8859-1');
		//$html = $this->httpGet($url);
		

		return abi_extractContactsFromLdif ($html);
	}


}

//email.it (release date: 15 June 2008)
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["email.it"] = 'EmailItImporter';
$_DOMAIN_IMPORTERS["emailit"] = 'EmailItImporter';
