<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

GMX contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['gmx'] = array('type'=>'abi', 'label'=>'GMX.net', 'class'=>'GmxImporter');

//gmx.de/net
define('GmxImporter_DETAIL_REGEX',"/CUSTOMERNO=(\\d+).*?&(?:amp;)?t=([^&]+)/ims");

//gmx.com
define('GmxImporter_LOGINURL_REGEX',"/<form\\s+action=\"([^\"]*?:FormLogin::[^\"]*)\"[^>]*>.*?<input\\s+type=\"hidden\"\\s+name=\"(idc_[^\"]*)\"/ims");
define('GmxImporter_TOKENS_REGEX',"/authToken\\s+:\\s+\"([^\"]*)\".*?custNo\\s+:\\s+(\\d+).*?partnerData\\s+:\\s+\"community=(\\d+).*?\\s+rms\\s+:\\s+\"([^\"]*)\"/ims");

/////////////////////////////////////////////////////////////////////////////////////////
//GmxImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class GmxImporter extends WebRequestor {

	var $gmxcom = false;

	//gmx.com
	var $authToken;
	var $custNo;
	var $custNo2;
	var $rms;
	
	//gmx.de/.net
	var $t;
	var $customerNo;

	//@api
	function getInfo () {
		return array('id'=>'gmx');
	}

	//@api
	function logout ()
	{
	 	if ($this->gmxcom)
			$this->httpGet("http://gmx.com/logout.html");
		else
			$this->httpGet("http://logout.gmx.net");
	}

	//@api
	function login ($loginemail, $password) {
		$this->setOwnerEmail($loginemail);
		$domain = oz_get_email_domain($loginemail);
		oz_set_domain($domain);

		if ($domain=='gmx.com') {
		 	$this->gmxcom = true;
		 	
			$html = $this->httpGet("http://mail-us.gmx.com/");
			if (!preg_match(GmxImporter_LOGINURL_REGEX,$html,$matches)) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find login form');
			}
	
			$form = new HttpForm;
			$form->action = $matches[1];
			$form->addField($matches[2], "");
			$form->addField("TextfieldEmail", $loginemail);
			$form->addField("TextfieldPassword", $password);
			$form->addField("ButtonLogin", "Sign In");
			$form->addField("RadioLoginType", "BROWSER");
			$form->addField("ButtonLogin", "1");
			$html = $this->postForm($form);
			if (strpos($html,'feedbackPanelERROR')!==FALSE) {
				$this->close();
				return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
			}
	
			if (!preg_match(GmxImporter_TOKENS_REGEX,$html,$matches)) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find tokens');
			}
	
			$this->authToken = $matches[1];
			$this->custNo = $matches[2];
			$this->custNo2 = $matches[3];
			$this->rms = $matches[4];
		}
		else {
		 	$this->gmxcom = false;
			$form = new HttpForm;
			$form->addField("AREA", "1");
			$form->addField("EXT", "redirect");
			$form->addField("EXT2", "");
			$form->addField("id", $loginemail);
			$form->addField("p", $password);
			$form->addField("_authtrkcde", "{#TRKCDE#}");
			$postData = $form->buildPostData();
			$html = $this->httpPost("http://service.gmx.net/de/cgi/login", $postData);
			if (strpos($html, 'Diese Kennung wurde vom Systembetreiber gesperrt')!=false) {
				$this->close();
				return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Account closed by system operator');
			}
			if (strpos($html, '<div class="error">')!=false ||
				strpos($html, 'errormodule')!=false) {
				$this->close();
				return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
			}
	
			if (preg_match(GmxImporter_DETAIL_REGEX,$this->lastUrl,$matches)==0) {
				//The last url may not be pointing to mainbox, but it may be an advertisement.
				if (preg_match(GmxImporter_DETAIL_REGEX,$html,$matches)==0) {
					$this->close();
					return abi_set_error(_ABI_FAILED,'Cannot find CUSTOMERNO and t');
				}
			}
	
			$this->customerNo = urldecode($matches[1]);
			$this->t = urldecode($matches[2]);
		}
		return abi_set_success();
	}


	function fetchCsv () {

		$form = new HttpForm;
		$form->addField("CUSTOMERNO", $this->customerNo);
		$form->addField("t", $this->t);
		$form->addField("site", "importexport");
		$form->addField("language", "english");
		$form->addField("dataformat", "o2002");
		$form->addField("b_export", "Export starten");
		$postData = $form->buildPostArray();

		$html = $this->httpPost("http://service.gmx.net/de/cgi/addrbk.fcgi", $postData,'utf-8');

		//Convert character set to utf-8
		if (function_exists('mb_convert_encoding')) $html = mb_convert_encoding($html, "utf-8","ISO-8859-1");
		else if (function_exists('iconf')) $html = iconv('ISO-8859-1', 'utf-8', $html);
		//else, we can't perform the conversion. Return raw form.

		//ISO-8859-1

		$this->logout();
		return $html;
		/*
		$res = abi_extract_outlook_csv($html);


		$this->close();
		return $res;
		*/
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$res = $this->login($loginemail,$password);
		if ($res!=_ABI_SUCCESS) return $res;

		if ($this->gmxcom) {
			$form = new HttpForm;
			$rand = $this->custNo + "-" + time();
			$url = "http://www.gmx.com/callgate-".$this->rms."/coms5/CEPService/getAll?X-UI-JSON=javascript&X-UI-RequestId=".$rand."&Authorization=".$this->authToken."&X-UI-AccountId=".$this->custNo2."&nocache=".time();
			$headers = array('Content-Type: application/json;charset=UTF-8');
			$html = $this->httpRequest ($url, true, "{\"cepDTPClass\":{\"email\":true},\"order\":null,\"from\":null,\"to\":null}", $defaultCharset='utf-8', $headers);
			 
			$cl = array();
			$jv = oz_json_decode($html,TRUE);
			if (!isset($jv['response'])) return abi_set_error(_ABI_FAILED,'Cannot read json response');
			$jv = $jv['response'];
			foreach ($jv as $jc) {
			 	$fname = isset($jc['firstName']) ? $jc['firstName'] : '';
			 	$lname = isset($jc['name']) ? $jc['name'] : '';
			 	$name = trim(oz_reduce_whitespace($fname.' '.$lname));
			 	if (isset($jc['email'])) {
					$emails = $jc['email'];
					foreach ($emails as $je) {
					 	if ($je['address']) {
							$email = trim($je['address']);
							if (abi_valid_email($email)) {
								$cl[] = new Contact($name,$email);
							}
						}
					}
				}
			}
			return $cl;
		}
		else {
			$html = $this->fetchCsv();
	
			$this->logout();
	
			if (!is_string($html)) {
				return $html;
			}
			$res = abi_extract_outlook_csv($html);
			return $res;
		}
	}
}

//GMX
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["gmx.net"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx.at"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx.ch"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx.eu"] = 'GmxImporter';

$_DOMAIN_IMPORTERS["gmx.com"] = 'GmxImporter';


//GMX fun domains
$_DOMAIN_IMPORTERS["bist-eine-haelfte-von-mir.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["bleib-bei-mir.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["es-ist-liebe.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["fahr-zur-hoelle.org"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ich-bin-verrueckt-nach-dir.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ist-allein.info"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ist-es-liebe.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ist-ganz-allein.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ist-willig.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["lass-es-geschehen.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["liebt-dich.info"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["loveyouforever.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["moechte-mit-dir-aufwachen.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["schmusemail.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["schreib-doch-mal-wieder.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["teilt-mit-dir-alle-geheimnisse.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["verlass-mich-nicht.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["vorsicht-scharf.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["weinenvorglueck.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["alphafrau.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["feinripptraeger.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["fettabernett.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ist-einmalig.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["kaffeeschluerfer.com"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["liebt-den-mann-ihrer-chefin.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["liebt-die-frau-seines-chefs.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["maennerversteherin.com"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["partybombe.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["partyheld.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["polizisten-duzer.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["raubtierbaendiger.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["saeuferleber.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["tortenboxer.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["turboprinz.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["turboprinzessin.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["vorsicht-bissig.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["alpenjodel.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["das-spiel-hat-90-minuten.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["der-ball-ist-rund.net"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["die-genossen.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["die-optimisten.net"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["email-ausdrucker.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["fantasymail.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["freudenkinder.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gentlemansclub.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx-ist-cool.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["herr-der-mails.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ich-habe-fertig.com"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["meine-wahrheit-deine-wahrheit.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["muskelshirt.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["quantentunnel.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["sags-per-mail.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["sonnenkinder.org"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["turnbeutel-vergesser.com"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["vollbio.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["volloeko.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["vorabend-einchecker.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["weibsvolk.org"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["wenns-um-email-geht.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["wir-sind-cool.org"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["wolke7.net"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["abwesend.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["baldmama.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["baldpapa.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["betriebsdirektor.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["buerotiger.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["habmalnefrage.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["hab-verschlafen.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["ich-will-net.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["kommespaeter.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["mailueberfall.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["netterchef.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["nurfuerspam.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["streber24.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["terminverpennt.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["unterderbruecke.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["will-hier-weg.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["wir-haben-nachwuchs.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["women-at-work.org"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["bin-wieder-da.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["coole-files.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["die-besten-bilder.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["digi-dia-freakshow.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["digital-filestore.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["digitalfoto-model-award.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["download-privat.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["gmx-topmail.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["meine-dateien.info"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["meine-diashow.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["meine-fotos.info"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["meine-urlaubsfotos.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["neue-dateien.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["office-dateien.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["peinliche-fotos.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["public-files.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["shared-files.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["topmail-files.de"] = 'GmxImporter';
$_DOMAIN_IMPORTERS["war-im-urlaub.de"] = 'GmxImporter';

