<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Virgilio.it contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['virgilioit'] = array('type'=>'abi', 'label'=>'Virgilio.it', 'class'=>'VirgilioItImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//VirgilioItImporter. 
/////////////////////////////////////////////////////////////////////////////////////////

//@api
class VirgilioItImporter extends WebRequestor {

	var $VREDIR_URL_REGEX = "/window\\.parent\\.location\\.href\\s*=\\s*\"([^\"]*)\"/ims";
	var $VREDIR2_URL_REGEX = "/window\\.location\\.href\\s*=\\s*\"([^\"]*)\"/ims";
	var $T_REGEX = "/<input\\s+type=\"hidden\"\\s+name=\"t\"\\s+value=\"([^\"]*)\"/ims";

	var $t;
	var $login;
	var $domain;

	//@api
	function getInfo () {
		return array('id'=>'virgilio.it');
	}

	//@api
	function login ($loginemail, $password) {

		$loginemail = strtolower($loginemail);
		$parts = $this->getEmailParts ($loginemail);
		$this->id = $parts[0];
		$this->domain = $parts[1];
		$this->setOwnerEmail($loginemail);
		oz_set_domain($parts[1]);

		$form = new HttpForm;
		$form->action = "https://aaacsc.alice.it/piattaformaAAA/aapm/amI";
		$form->addField("usernameDisplay", $this->id);
		$form->addField("password", $password);
		$form->addField("dominio", $this->domain); // @alice.it
		$form->addField("login", $loginemail);
		$form->addField("pwd", $password);
		$form->addField("channel", "mail_alice"); // ???
		$form->addField("URL_OK","https://authsrs.alice.it/aap/aap_redir.jsp?entry=Vmail"); // ??
		$form->addField("URL_KO","https://authsrs.alice.it/aap/aap_redir_ko.jsp?entry=Vmail"); // ??
		$form->addField("servizio", "mail");
		$form->addField("msisdn", $this->id);
		$form->addField("username", $loginemail);
		$form->addField("user", $loginemail);
		$form->addField("a3afep","http://portale.rossoalice.alice.it/ps/ManageCodError.do?code=470&channel=Vmail"); // ??
		$form->addField("DOMAIN", "");
		$form->addField("PASS", $password);
		$form->addField("self", "true");
		$form->addField("a3si", "none");
		$form->addField("a3st", "VCOMM");
		$form->addField("nototop", "true");
		$form->addField("a3aid", "na");
		$form->addField("a3flag", "0");
		$form->addField("a3ep", "http://communicator.alice.it/asp/login.asp"); // ?
		$form->addField("a3se","http://portale.rossoalice.alice.it/ps/ManageCodError.do?code=470&channel=Vmail"); // ???
		$form->addField("a3dcep","http://communicator.alice.it/asp/homepage.asp?s=005"); // ?
		$form->addField("a3l", $loginemail);
		$form->addField("a3p", $password);
		$form->addField("imageField.x", "18");
		$form->addField("imageField.y", "8");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$html = $this->postForm($form);
		
		if (strpos($html,"&paaa=_&")!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
		if (!preg_match($this->VREDIR_URL_REGEX,$html,$matches)) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find redirection url');
		}
		$url = $matches[1];
		$html = $this->httpGet($url);

		if (preg_match($this->VREDIR2_URL_REGEX,$html,$matches)) {
			$url = $matches[1];
			$html = $this->httpGet($url);
		}
		
		$url = "PreLogin?u=".urlencode($this->id)."&d=virgilio.it&rnd=".time();
		$html = $this->httpGet($url);

		if (!preg_match($this->T_REGEX,$html,$matches)) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find t token');
		}
		$this->t = $matches[1];

		return abi_set_success();
	}

	//@api
	function logout() {
		$this->httpGet("http://webmailvtin.alice.it/cp/ps/Main/logout/Logout?d=virgilio.it&l=it");// &u=kenfoo&t=d12357d6965d6071d52d)
	}
		
	//@api
	function fetchContacts ($loginemail, $password) {
		
		$res = $this->login($loginemail,$password);
		if ($res!=_ABI_SUCCESS) return $res;

		$form = new HttpForm;
		$form->action = "/cp/ps/pspab/SLcommands/pabExportContacts?l=it";
		$form->addField("u", $this->id);
		$form->addField("d", $this->domain);
		$form->addField("t", $this->t);
		$html = $this->postForm($form);

		$reader = new OzCsvReader($html);
		//Read header
		$cols = $reader->nextRow();
		if ($cols==null || count($cols)<=2) {
		 	return array();
			//$this->close();
			//return abi_set_error(_ABI_FAILED,'Cannot find CSV');
		}
		$cl = array();
		while (true) {
			$cols = $reader->nextRow();
			if ($cols==null || count($cols)<=0) break;
			if (count($cols)>=2) {
				$name = $cols[0];
				$email = trim($cols[1]);
				if (abi_valid_email($email)) {
					$cl[] = new Contact($name,$email);
				}
			}
		}
		return $cl;
	}
}

//alice.it
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["virgilio.it"] = 'VirgilioItImporter';
