<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Wp.pl contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['wppl'] = array('type'=>'abi', 'label'=>'Wp.pl', 'class'=>'WpImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//WpImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class WpImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'wp.pl');
	}

	//@api
	function logout () {
		$this->httpGet('http://logout.freenet.de/');
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		$this->setOwnerEmail($loginemail);
		oz_set_domain($parts[1]);

		$html = $this->httpGet("http://profil.wp.pl/login.html?serwis=wp.pl");
		$form = new HttpForm;
		$form->setField("tryLogin", "1");
		$form->setField("countTest", "1");
		$form->setField("serwis", "nowa_poczta_wp");
		$form->setField("url","http://ksiazka-adresowa.wp.pl/import-export.html");
		$form->setField("login_username", $login);
		$form->addField("login_password", $password);
		$form->setField("subm", "Zaloguj");
		$form->setField("savessl", "2");
		$form->setField("starapoczta", "2");
		$form->setField("savelogin", "2");
		$form->setField("minipoczta", "2");
		$form->setField("mini", "0");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost("http://profil.wp.pl/login.html", $postData);
		if (strpos($html, 'niestety podany login lub')!==false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		$form = new HttpForm;
		$form->setField("gr_id", "0");
		$form->setField("program", "tb");
		// yh=yahoo
		// oeex=Outlook Express
		// oeof=Outlook
		// nn=Netscape
		// bt=The Bat!
		// tb=Thunderbird
		// gm=Gmail
		$postData = $form->buildPostData();
		$html = $this->httpPost("/csv.html", $postData);

		$res = abi_extract_thunderbird_csv($html);
		$this->close();
		return $res;
	}
}

//wp.pl
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["wp.pl"] = 'WpImporter';
