<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component
Statistics Management

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
if (!defined('__ABI')) die('Please include abi.php to use this inviter component!');

global $_OZI_STATS_DB;
$_OZI_STATS_DB = NULL;


function ozi_stats_enabled() {
	return ozi_get_config('stats.enabled',FALSE);
}


function ozi_stats_opendb() {
	global $_OZI_STATS_DB;

	//Already open? Skip
	if ($_OZI_STATS_DB!==NULL) return $_OZI_STATS_DB;
	if (!ozi_stats_enabled()) return FALSE;
	if (!function_exists('sqlite_open')) {
		trigger_error('You need PHP5 or PECL sqlite to be installed for stats to work',E_USER_ERROR);
		return FALSE;
	}
	
	$dbfile = ozi_get_config('stats.dbfile',NULL);
	if ($dbfile===NULL)
		$dbfile = dirname(__FILE__).'/../tmp/stats.sqlite';
	
	//TODO: MAKE SURE DIRECTORY/FILE IS WRITABLE
	
	$existing = file_exists($dbfile);
	$_OZI_STATS_DB = sqlite_open($dbfile,0666);
	if ($_OZI_STATS_DB===FALSE) return FALSE;
	else {
		//Create DB tables, and perform schema upgrades if necessary
		if (!$existing) {
			sqlite_query($_OZI_STATS_DB, "BEGIN TRANSACTION;
				CREATE TABLE ozi_config (config_key VARCHAR(50) PRIMARY KEY, config_value TEXT);
				INSERT INTO ozi_config (config_key,config_value) VALUES ('schema','1');
				CREATE TABLE ozi_stats_invites (id INTEGER PRIMARY KEY, member_id VARCHAR(50), op_date DATETIME NOT NULL, svc_id VARCHAR(20), total_contacts INTEGER NOT NULL DEFAULT 0, total_invites INTEGER NOT NULL DEFAULT 0, total_clicks INTEGER NOT NULL DEFAULT 0, ip CHAR(15), token VARCHAR(50));
				CREATE INDEX ozi_idx_invites ON ozi_stats_invites(op_date DESC);
				CREATE INDEX ozi_idx_invites2 ON ozi_stats_invites(svc_id,op_date DESC);
				CREATE INDEX ozi_idx_invites3 ON ozi_stats_invites(member_id,op_date DESC);
				CREATE TABLE ozi_stats_daily  (datestr CHAR(10) PRIMARY KEY, total_requests INTEGER NOT NULL DEFAULT 0, total_contacts INTEGER NOT NULL DEFAULT 0, total_invites INTEGER NOT NULL DEFAULT 0, total_clicks INTEGER NOT NULL DEFAULT 0);
				CREATE INDEX ozi_idx_daily ON ozi_stats_daily(datestr DESC);
				COMMIT;
				");
				
				//CREATE TABLE ozi_stats_clicks (id INTEGER PRIMARY KEY, op_date DATETIME NOT NULL, invite_id INTEGER, ip CHAR(15), url VARCHAR(255), referrer VARCHAR(255));
				//CREATE INDEX ozi_idx_clicks ON ozi_stats_clicks(op_date DESC);
				
		}
		else {
			//Ensure schema is up to date, and update accordingly
		}

		//Close db automatically		
		register_shutdown_function('ozi_stats_closedb');
		
		return $_OZI_STATS_DB;
	}
}

//Automatically called
function ozi_stats_closedb() {
	global $_OZI_STATS_DB;
	if ($_OZI_STATS_DB!==NULL) {
		sqlite_close($_OZI_STATS_DB);
		$_OZI_STATS_DB = NULL;
	}
	return TRUE;
}

//Reset all statistics back to 0
function ozi_stats_reset() {
	$db = ozi_stats_opendb();
	if ($db) {
		$sql = "BEGIN TRANSACTION;
				DELETE FROM ozi_stats_invites;
				COMMIT;";
//				DELETE FROM ozi_stats_imports;
		sqlite_exec($db,$sql);
	}
	return TRUE;
}

function ozi_escape_string($str) {
	return $str===NULL ? 'NULL' : sqlite_escape_string($str);
}

//Record imported contacts
function ozi_stats_record_import (&$contacts) {
	global $_OZI_STATE;

	$n = count($contacts);

	$db = ozi_stats_opendb();
	if ($db) {

		//Update daily result count
		$now = time();
		$ds = date("Y-m-d",$now);
		sqlite_exec($db,"UPDATE ozi_stats_daily SET total_requests=total_requests+1, total_contacts=total_contacts+$n WHERE datestr='$ds';");
		if (sqlite_changes($db)==0) {
			sqlite_exec($db,"INSERT INTO ozi_stats_daily (datestr,total_requests,total_contacts,total_invites,total_clicks) VALUES('$ds',1,$n,0,0);");
		}

		//Insert records
		$sql = sprintf("INSERT INTO ozi_stats_invites (id,op_date,member_id,svc_id,total_contacts,ip,token) VALUES (NULL,'%s',%s,%s,%d,%s,%s);",
			date("Y-m-d H:i:s",$now),
			isset($GLOBALS['ozi_member_id']) ? "'".sqlite_escape_string($GLOBALS['ozi_member_id'])."'" : 'NULL',
			$_OZI_STATE->svc_id!==NULL?"'".sqlite_escape_string($_OZI_STATE->svc_id)."'":'NULL',
			$n,
			"'".sqlite_escape_string($_SERVER['REMOTE_ADDR'])."'",
			isset($GLOBALS['ozi_token']) ? "'".sqlite_escape_string($GLOBALS['ozi_token'])."'" : 'NULL');
		$res = sqlite_exec($db,$sql);
		if ($res) {
			//Save record id
			global $_OZI_STATE;
			$_OZI_STATE->record_id = sqlite_last_insert_rowid($db);
		}
		return $res;
	}
	else {
		return FALSE;
	}
}

//Record imported contacts
function ozi_stats_record_invite (&$contacts) {

	$n = count($contacts);
	if ($n==0) return TRUE;
	
	$db = ozi_stats_opendb();
	if ($db) {
	
		//Update daily result count
		$now = time();
		$ds = date("Y-m-d",$now);
		sqlite_exec($db,"UPDATE ozi_stats_daily SET total_requests=total_requests++1, total_invites=total_invites+$n WHERE datestr='$ds';");
		if (sqlite_changes($db)==0) {
			sqlite_exec($db,"INSERT INTO ozi_stats_daily (datestr,total_requests,total_contacts,total_invites,total_clicks) VALUES('$ds',1,0,$n,0);");
		}
			
		global $_OZI_STATE;
		$record_id = $_OZI_STATE->record_id;
		if ($record_id===NULL) {
			$sql = sprintf("INSERT INTO ozi_stats_invites (id,op_date,member_id,svc_id,total_contacts,total_invites,ip,token) VALUES (NULL,'%s',%s,%s,%d,%d,%s,%s);",
				date("Y-m-d H:i:s",$now),
				isset($GLOBALS['ozi_member_id']) ? "'".sqlite_escape_string($GLOBALS['ozi_member_id'])."'" : 'NULL',
				$_OZI_STATE->svc_id===NULL ? 'NULL' : "'".sqlite_escape_string($_OZI_STATE->svc_id)."'",
				$n,
				$n,
				"'".sqlite_escape_string($_SERVER['REMOTE_ADDR'])."'",
				isset($GLOBALS['ozi_token']) ? "'".sqlite_escape_string($GLOBALS['ozi_token'])."'" : 'NULL');
			$res = sqlite_exec($db,$sql);
			$_OZI_STATE->record_id = sqlite_last_insert_rowid($db);		
		}
		else {
			$sql = sprintf("UPDATE ozi_stats_invites SET total_invites=%d WHERE id=%d;",
				$n,
				$record_id);
			$res = sqlite_exec($db,$sql);
		}
		return $res;
	}
	else {
		return FALSE;
	}
}

//Track a click on the invitation link
function ozi_stats_record_click($url,$record_id,$token,$referrer) {

	$db = ozi_stats_opendb();
	if ($db) {
		//Update daily result count
		$now = time();
		$ds = date("Y-m-d",$now);
		sqlite_exec($db,"UPDATE ozi_stats_daily SET total_clicks=total_clicks+1 WHERE datestr='$ds';");
		if (sqlite_changes($db)==0) {
			sqlite_exec($db,"INSERT INTO ozi_stats_daily (datestr,total_requests,total_contacts,total_invites,total_clicks) VALUES('$ds',0,0,0,1);");
		}
		
		//Increment click count on the invite 
		if ($record_id!==NULL && $record_id!=='') {
			$sql = sprintf("UPDATE ozi_stats_invites SET total_clicks=total_clicks+1 WHERE id=%s;",intval($record_id));
			return sqlite_exec($db,$sql);
		}
	}
	return FALSE;

/*
		//Insert click record
		$sql .= sprintf("INSERT INTO ozi_stats_clicks (id,op_date,invite_id,ip,url,referrer) VALUES (NULL,DATETIME('NOW'),%s,%s,%s,%s);",
//			date("Y-m-d H:i:s"),
			$record_id===NULL || $record_id==='' ? 'NULL' : intval($record_id),
			"'".sqlite_escape_string($_SERVER['REMOTE_ADDR'])."'",
			$url==NULL ? 'NULL' : "'".sqlite_escape_string(substr($url,0,255))."'",
			$referrer==NULL ? 'NULL' : "'".sqlite_escape_string(substr($referrer,0,255))."'");
*/
			
}

//Perform a generic SQL query
//function ozi_stats_query($sql) {
//}

function ozi_stats_next_row ($res) {
	return sqlite_fetch_array($res);
}

function ozi_stats_get_top_inviters($days=30, $limit=100) {
	$db = ozi_stats_opendb();
	if ($db) {
		$ds = date("Y-m-d H:i:s",time()-($days*24*60*60));
		$sql = "SELECT member_id, COUNT(id) as total_requests, SUM(total_contacts) as total_contacts, SUM(total_invites) AS total_invites, SUM(total_clicks) AS total_clicks FROM ozi_stats_invites WHERE op_date >='$ds' GROUP BY member_id ORDER BY total_invites DESC LIMIT $limit";
		return sqlite_array_query($db,$sql,SQLITE_ASSOC);
	}
	return FALSE;
}

/**
* Returns assoc array of total_invites, total_contacts, total_clicks, total_members (number of distinct members performing invites)
*/
function ozi_stats_get_cumulative_summary($days=30) {

	$db = ozi_stats_opendb();
	if ($db) {
		$ds = date("Y-m-d H:i:s",time()-($days*24*60*60));

		//Get total members inviting
		$sql = "SELECT COUNT(member_id) as total_members FROM (SELECT DISTINCT member_id FROM ozi_stats_invites WHERE op_date >='$ds');";
		$total_members = sqlite_single_query($db,$sql,SQLITE_ASSOC);
		
		$sql = "SELECT COUNT(id) AS total_requests, SUM(total_contacts) as total_contacts, SUM(total_invites) AS total_invites, SUM(total_clicks) AS total_clicks FROM ozi_stats_invites WHERE op_date >='$ds';";
		$res = sqlite_array_query($db,$sql,SQLITE_ASSOC);
		if ($res===FALSE || count($res)===0) return FALSE;
		
		$res[0]['total_members'] = $total_members;
		
		return $res[0];
	}
	return FALSE;
}

/**
* Get daily summary of invites. Result is an array of daily counts, where daily counts are stored in an associative array, sorted in ascending order.
*/
function ozi_stats_get_total_daily_invites($days=30) {
	$db = ozi_stats_opendb();
	if ($db) {
		$ds = date("Y-m-d H:i:s",time()-($days*24*60*60));
		$sql = "SELECT datestr AS date_str,SUM(total_requests) AS total_requests, SUM(total_contacts) AS total_contacts, SUM(total_invites) AS total_invites, SUM(total_clicks) AS total_clicks FROM ozi_stats_daily WHERE DATESTR>='$ds' GROUP BY datestr ORDER BY datestr ASC";
		return sqlite_array_query($db,$sql,SQLITE_ASSOC);		
	}
	return FALSE;
}


//get total invites in last 30 days

//get invites on daily basis for the last 30 days
//NEED a daily table of sums.


?>