<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Hyves invite sender

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
if (!defined('__ABI')) die('Please include abi.php to use this invite sender!');

global $_OZ_SERVICES;
$_OZ_SERVICES['is_hyves'] = array('type'=>'is', 'label'=>'Hyves', 'class'=>'HyvesInviter');

/////////////////////////////////////////////////////////////////////////////////////////
//HyvesInviter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class HyvesContact extends SocialContact {
	function HyvesContact ($uid, $name, $imgurl) {
		parent::SocialContact($uid, $name, $imgurl);
	}
}

//define('HyvesInviter_CONTACT_REGEX',"/contentblock_clipper.*?<div><a[^>]+id=\"mop_[^\"]*\"[^>]+?href=\"http:\/\/([^.]*)\\.hyves[^>]+>.*?<img\\s+src=\"([^\"]+)\".*?BodyTextSmall\">(.*?)\\s+\\(\\d+\\)<\/span>/ims");
define('HyvesInviter_CONTACT_REGEX',"/<div\\s+class=\"avatar.*?<img[^>]*?class=\"avatar-img\"[^>]*?src=\"([^\"]*)\".*?<p\\s+class=\"avatar-name\"[^>]*>\\s*<a[^>]*?href='http:\/\/([^\\.]*)\\.hyves.nl'[^>]*?title=\"([^\"]*)\"[^>]*>(.*?)\\s\\(\\d+\\)<\/a/ims");
define('HyvesInviter_PAGER_REGEX',"/new Pager\\(.*?nrPages:\\s*(\\d+),.*?extra:\\s*'([^']*)'/ims");
define('HyvesInviter_SECRET_REGEX',"/var\\s+global_postman_secret\\s*=\\s*'([^']*)'/ims");

//@api
class HyvesInviter extends WebRequestor {

	var $memberId;

	//@api
	function getInfo () {
		return array('id'=>'hyvez');
	}

	//@api
	function login ($userId, $password) {
		oz_set_domain('hyves');

		$form = new HttpForm;
		$form->action = "http://www.hyves.nl/?module=authentication&action=loginMobile";
		$form->addField("l1", "mo");
		$form->addField("auth_feedbackUrl", "http://www.hyves.nl/?l1=mo&l2=lg");
		$form->addField("auth_ignoreCurrentUrl", "1");
		$form->addField("auth_currentUrl", "http://www.hyves.nl/?l1=mo&l2=lg");
		$form->addField("auth_username", $userId);
		$form->addField("auth_password", $password);
		$form->addField("login", "ok");
		$html = $this->postForm($form);
		if (strpos($this->lastUrl,"&l2=lg")!==FALSE || strpos($html,'class="error"')!==FALSE) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad username or password');
		}
		$this->memberId = $userId;
		$this->close();
		return abi_set_success();
	}

	//@api
	function logout()  {
		$this->httpGet("http://www.hyves.nl/?module=authentication&action=logoutMobile&auth_currentUrl=http://www.hyves.nl/mobile/?");
	}

	function _extractContacts($html, &$cl) {

		//Avoid the suggested friends
		$i = strpos($html,"pager_quickfinder_member_friends");
		if ($i!==FALSE) $html=substr($html,0,$i);
		$i = strpos($html,"suggestionFriendContainer");
		if ($i!==FALSE) $html=substr($html,0,$i);
	 
		$n = 0;
		preg_match_all(HyvesInviter_CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
		$c=0;
		foreach ($matches as $val) {
			$uid = trim($val[2]);
			if ($uid!=$this->memberId) {
				$imgurl = $this->makeAbsolute($this->lastUrl,htmlentities2utf8(trim($val[1])));
				$name = trim(htmlentities2utf8(trim($val[3])));
				//Hyves name may contain html!
				$name = $this->extractText($name);
				$contact = new HyvesContact($uid,$name,$imgurl);
				$c++;
				$cl[] = $contact;
			}
		}
		return $c;
	}

	//@api
	function fetchContacts ($maxFetch=NULL, $maxPages=NULL) {

		//Get max contacts, pages, duration to fetch contacts
		if ($maxFetch===NULL) $maxFetch = oz_get_config('limit.max_contacts',1000);
		if ($maxPages===NULL) $maxPages = oz_get_config('limit.max_pages',30);

		$html = $this->httpGet("http://".urlencode($this->memberId).".hyves.nl/friends/");
		// "http://dushigirl77.hyves.nl/friends/"

		$cl = array();
		if ($this->_extractContacts($html, $cl) == 0)
			return $cl;
		if (!preg_match(HyvesInviter_PAGER_REGEX,$html,$matches))
			return $cl;

		$nrPages = intval($matches[1]);
		$extra = $matches[2];

		for ($i = 2; $i <= $nrPages && $i <= $maxPages; $i++) {
			$form = new HttpForm;
			$form->action = "/index.php?xmlHttp=1&module=pager&action=showPage";
			$form->addField("name", "quickfinder_member_friends");
			$form->addField("pageNr", $i);
			$form->addField("config", "hyvespager-config.php");
			$form->addField("extra", $extra);
			$html = $this->postForm($form);
			if ($this->_extractContacts($html, $cl) == 0)
				break;
		}

		return $cl;
	}

	//returns true if successful, false if failed.
	//@api
	function sendMessage ($uid, $subject, $message, $saveToSent = false) {
		$uids = array();
		$uids[] = $uid;
		return $this->sendMessages($uids,$subject,$message);
	}

	//@api
	function sendMessages ($uids, $subject, $message, $saveToSent = false) {

		abi_set_success();

		$BATCH_SIZE = 20;
		$start = 0;
		$maxRecipientsPerMessage = $BATCH_SIZE;
		$res = true;
		$uidcount = count($uids);
		while ($start < $uidcount) {
			$n = $start + $maxRecipientsPerMessage;
			if ($n > $uidcount) $n=$uidcount;

			$html = $this->httpGet("http://www.hyves.nl/messages?autoOpenNew=1");
			if (!preg_match(HyvesInviter_SECRET_REGEX,$html,$matches)) {
				return abi_set_error(_ABI_FAILED,'Cannot find secret');
				break;	//Error
			}
			$secret = $matches[1];


			$form = new HttpForm;
			$form->action = "http://www.hyves.nl/?module=Message&action=postSendMessage";
			$form->addField("postman_secret", $secret);
			//$form->addField("type", "livemail");
			$form->addField("sendmessage_type", "2"); // private msg
			$sb = '';
			for ($i = $start; $i < $n; $i++) {
				if ($sb!='') $sb.=',';
				$uid = $uids[$i];
				if (oz_instanceof($uid,'SocialContact')) $uid = $uid->uid;
				$sb.=$uid;
			}
			$form->addField("sendmessage_to", $sb);
			$form->addField("sendmessage_to_extra", "");
			$form->addField("sendmessage_subject", $subject);
			$form->addField("sendmessage_body", $message);
			$form->addField("_","");
			$html = $this->postForm($form);

			// Get result
			$res &= strpos($html,"\"success\":true")!==FALSE;
			
			//Fail? Abort!
			if ($res===FALSE) break;

			if (strpos($html,"l2=confirmemail")!==FALSE) {
				break;
			}

			$start = $n;
		}
		return $res==true;
	}

}
