<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/

//////////////////////////////////////////////////////////////////////////
//Parameters
//	oz_recipients
//		Array of contacts.
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();
?>

<? if ($_GET['type'] == 'setup'){ ?>
  <h2>
    {{FINISHED_TITLE}}
  </h2>
<? } ?>
<div id="ozpanel_finished">
<?
$recipients = isset($_REQUEST['oz_recipients']) ? $_REQUEST['oz_recipients'] : array();
if (count($recipients)>0)
{
	echo oz_text('FINISHED_SENT_TO');
	echo '<ul class="rec">';
	foreach ($recipients as $r) 
		echo '<li>'.htmlspecialchars($r).'</li>';
	echo '</ul>';
}
else
{
	echo oz_text('FINISHED_SENT');
}

?>
</div>
<div id="ozpanel_finished_buttons">
  {{FINISHED_HAVE_MORE_FRIENDS}}
  <button onclick="ozStartAgain2();return false;" class="invite_more short_button">{{FINISHED_INVITE_THEM}}</button>
  <? if ($_GET['type'] == 'setup') { ?>
    <button onclick="return top.Signup.NextStep()" class="next_step short_button">Continue to next step</button>
  <? } ?>
</div>

<script type="text/javascript">
//<![CDATA[
ozNotifyViewChange('finished');
//]]>
</script>