<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/

//////////////////////////////////////////////////////////////////////////
//Takes in parameter from $_POST
//
//oz_service (optional)
//	Contains the service ID if we're to jump straight to login form
//
//oz_auth_login (optional)
//	Contains the user auth ID that is to be prefilled
//
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();

//Set defaults
//if (!isset($_REQUEST['oz_service'])) $_REQUEST['oz_service']='';
if (!isset($_REQUEST['oz_auth_login'])) $_REQUEST['oz_auth_login']='';

global $oz_option_count;
$oz_option_count = 0;
function oz_render_service_option($id,$name) {
	global $oz_option_count;
	$skiptest = strpos($id,'file')!==FALSE || $id=='manual' || $id=='bookmark';
	if (!ozi_get_config('facebook_classicmode',FALSE)) $skiptest=$skiptest?true:$id=='is_facebook';
	$inviter = isset($_REQUEST['oz_inviter'])?$_REQUEST['oz_inviter']:NULL;
	if (($inviter!==NULL && $inviter->is_service_supported($id)) || empty($id) || $skiptest) {
		$s = '<option value="'.htmlspecialchars($id).'"';
		if ($id==$_REQUEST['oz_service']) $s.=' selected="selected"';
		$s .= '>'.htmlspecialchars($name,ENT_COMPAT,'UTF-8').'</option>';
		$oz_option_count++;
		return $s;
		//return oz_render_service_option2($id,$name,$loginpanel);
	}
	else {
		return '';
	}
}

?>
<? if ($_GET['type']=='setup') { ?><h2>{{LOGIN_TITLE}} <? } ?>
  <? if ($_GET['type']=='setup') { ?>
    <a href="#" onclick="return top.Signup.NextStep()" style="float:right; margin-left: 15px;">Skip to next step</a>
  <? } ?>
<? if ((ozi_get_config('selector_mode',0)==0) && ($_GET['type']=='setup')) { ?><a href='#' onclick='ozStartAgain();return false;'>{{START_AGAIN}}</a><? } ?>
  
<? if ($_GET['type']=='setup') { ?></h2><? } ?>

<div id="ozpanel_login">
  <script type="text/javascript">
//<![CDATA[
//var oz_lastSelectedService=null;
var _oz_service_panels = new Array();
_oz_service_panels['wa_hotmail']='ozpanel_login_windowslive';
_oz_service_panels['wa_gmail']='ozpanel_login_gmail';
_oz_service_panels['wa_databg']='ozpanel_login_gmail';
_oz_service_panels['wa_igcombr']='ozpanel_login_gmail';
<? if (!ozi_get_config('facebook_classicmode',FALSE)) {?>_oz_service_panels['is_facebook']='ozpanel_facebook';<? } ?>
//_oz_service_panels['wa_googleapps']='ozpanel_login_googleapps';

//_oz_service_panels['file_olcsv']='ozpanel_upload';//,ozpanel_olcsv';
//_oz_service_panels['file_oecsv']='ozpanel_upload';//,ozpanel_oecsv';
//_oz_service_panels['file_wmcsv']='ozpanel_upload';//,ozpanel_wmcsv';
//_oz_service_panels['file_tbldif']='ozpanel_upload';//,ozpanel_tbldif';
//_oz_service_panels['bookmark']='ozpanel_bookmark';
//_oz_service_panels['manual']='ozpanel_manual';


function ozLoginInit(src) {

	var opts = document.forms.ozform_select.oz_service.options;
	for (var i=0; i<opts.length; i++) 
	{
		if (opts[i].value==src)
		{		
			document.forms.ozform_select.oz_service.selectedIndex=i;
			break;
		}
	}
	
	//hide('ozpanel_upload,ozpanel_olcsv,ozpanel_oecsv,ozpanel_wmcsv,ozpanel_tbldif,ozpanel_loginpassword,ozpanel_manual,ozpanel_bookmark,ozpanel_dabi');
	ozHide('ozpanel_loginpassword,ozpanel_login_windowslive,ozpanel_login_gmail,ozpanel_facebook');
	var visiblepanels = _oz_service_panels[src];
	if (visiblepanels==undefined)
	{
		ozShow('ozpanel_loginpassword');
		try {document.forms.ozform_login.oz_auth_login.focus();} catch (e) {}
	}
	else
	{
		ozShow(visiblepanels);
	}

//	document.getElementById('oz_header_label').innerHTML=document.forms.ozform_select.oz_service.options[document.forms.ozform_select.oz_service.selectedIndex].innerHTML;
	document.forms.ozform_login.oz_service.value=src;
	
	//Some logins are based on login ID, not email. 
	if (src=='is_blackplanet' || src=='is_hyves' || src=='is_xing' || src=='is_twitter') {
		ozSetDisplayStyle('oz_loginid','inline');
		ozSetDisplayStyle('oz_loginemail','none');
	}
	else {
		ozSetDisplayStyle('oz_loginid','none');
		ozSetDisplayStyle('oz_loginemail','inline');
	}

<?  if (ozi_get_config('prefer_webauth',FALSE)) { ?>
	//If we're selecting one of the well known google apps aliases, then open the popup window if we're preferring web auth
	if (src=='wa_databg') {
		document.forms.ozform_googleapps.gapps_domain.value='data.bg';
		ozGoogleAppsAuth();
	}
	else if (src=='wa_igcombr') {
		document.forms.ozform_googleapps.gapps_domain.value='ig.com.br';
		ozGoogleAppsAuth();
	}
	
<? } ?>	
	//Scroll to top of page, otherwise user may miss out some content.
	//window.scroll(0,0);

	ozNotifyViewChange('login');
	if (typeof(ozOnServiceSelected)=='function') ozOnServiceSelected(src);
	
	
}
//]]>
</script>

<div class="notice">We won't send anything back to your account without your explicit permission</div>

  <div id="ozpanel_service_dropdown">
    <form method="post" name="ozform_select" id="ozform_select" style="margin:0px;" >
<? echo ozi_render_form_snippet(); ?>
      <div class="sep"><label class="oz_field_label_dd">{{LOGIN_NETWORK}}</label>
          <div class="dd"><select name="oz_service" onChange="ozLoginInit(this.options[this.selectedIndex].value)" style="width:250px" class="oz_field_select" id="oz_service_dropdown">
<?          
$oz_common_webmails_html = '';
$oz_common_webmails_html.=oz_render_service_option('',oz_text('ANY_WEBMAIL'));
$oz_option_count = 0;
if (ozi_get_config('show_abi',TRUE)) {
	$oz_common_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_gmail':'gmail','GMail');
	$oz_common_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_hotmail':'hotmail','Hotmail');
	$oz_common_webmails_html.=oz_render_service_option('yahoo','Yahoo');
	$oz_common_webmails_html.=oz_render_service_option('aol','AOL');
	$oz_common_webmails_html.=oz_render_service_option('lycos','Lycosmail');
	$oz_common_webmails_html.=oz_render_service_option('medotcom','MobileMe (.mac / .me)');
}
$oz_common_webmails_count = $oz_option_count;

$oz_option_count = 0;
$oz_other_webmails_html = '';
if (ozi_get_config('show_abi',TRUE)) {
	$oz_other_webmails_html.=oz_render_service_option('aliceit','Alice.it');
	$oz_other_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_databg':'databg','Data.bg');
	$oz_other_webmails_html.=oz_render_service_option('daumnet','Daum.net');
	$oz_other_webmails_html.=oz_render_service_option('emailit','Email.it');
	$oz_other_webmails_html.=oz_render_service_option('fastmail','FastMail');
	$oz_other_webmails_html.=oz_render_service_option('freenet','Freenet.de');
	$oz_other_webmails_html.=oz_render_service_option('gmx','GMX.net');
	$oz_other_webmails_html.=oz_render_service_option('icq','IcqMail');
	$oz_other_webmails_html.=oz_render_service_option(ozi_get_config('prefer_webauth',FALSE)?'wa_igcombr':'igcombr','Ig.com.br');
	$oz_other_webmails_html.=oz_render_service_option('indiatimes','Indiatimes');
	$oz_other_webmails_html.=oz_render_service_option('interia','Interia.pl');
	$oz_other_webmails_html.=oz_render_service_option('libero','Libero.it');
	$oz_other_webmails_html.=oz_render_service_option('mailru','Mail.ru');
	$oz_other_webmails_html.=oz_render_service_option('maildotcom','Mail.com');
	$oz_other_webmails_html.=oz_render_service_option('mynet','MyNet');
	$oz_other_webmails_html.=oz_render_service_option('naver','Naver.com');
	$oz_other_webmails_html.=oz_render_service_option('o2','O2.pl');
	$oz_other_webmails_html.=oz_render_service_option('onet','Onet.pl');
	$oz_other_webmails_html.=oz_render_service_option('orangees','Orange.es');
	$oz_other_webmails_html.=oz_render_service_option('rambler','Rambler');
	$oz_other_webmails_html.=oz_render_service_option('rediff','Rediffmail');
	$oz_other_webmails_html.=oz_render_service_option('sapo','Sapo.pt');
	$oz_other_webmails_html.=oz_render_service_option('sohu','Sohu');
	$oz_other_webmails_html.=oz_render_service_option('terra','Terra.es');
	//$oz_other_webmails_html.=oz_render_service_option('tonlinede','T-Online');
	$oz_other_webmails_html.=oz_render_service_option('virgilioit','Virgilio.it');
	$oz_other_webmails_html.=oz_render_service_option('webde','Web.de');
	$oz_other_webmails_html.=oz_render_service_option('wppl','Wp.pl (Wirtualna Polska)');
	$oz_other_webmails_html.=oz_render_service_option('yandex','Yandex');
}
$oz_other_webmails_count = $oz_option_count;

$oz_option_count = 0;
$oz_sn_html = '';
if (ozi_get_config('show_sn',TRUE)) {
	$oz_sn_html.=oz_render_service_option('is_facebook','Facebook');
	$oz_sn_html.=oz_render_service_option('is_myspace','MySpace');
	$oz_sn_html.=oz_render_service_option('is_twitter','Twitter');
	$oz_sn_html.=oz_render_service_option('linkedin','LinkedIn');
	$oz_sn_html.=oz_render_service_option('plaxo','Plaxo');
	$oz_sn_html.=oz_render_service_option('is_friendster','Friendster');
	$inviter = isset($_REQUEST['oz_inviter'])?$_REQUEST['oz_inviter']:NULL;
	$orkutEmailSupported = $inviter!==NULL && $inviter->is_service_supported('orkut');
	$oz_sn_html.=oz_render_service_option($orkutEmailSupported?'orkut':'is_orkut','Orkut');
	//$oz_sn_html.=oz_render_service_option('is_orkut','Orkut');
	//$oz_sn_html.=oz_render_service_option('orkut','Orkut (Email)');
	$oz_sn_html.=oz_render_service_option('is_hi5','Hi5');
	$oz_sn_html.=oz_render_service_option('is_bebo','Bebo');
	$oz_sn_html.=oz_render_service_option('is_xing','Xing');
	$oz_sn_html.=oz_render_service_option('is_blackplanet','BlackPlanet');
	$oz_sn_html.=oz_render_service_option('is_meinvz','MeinVZ');
	$oz_sn_html.=oz_render_service_option('is_hyves','Hyves');
}
$oz_sn_count = $oz_option_count;

?>          

			<? if ($oz_common_webmails_count>0) { ?>
            <optgroup label="{{DROPDOWN_COMMON_WEBMAILS}}"><? echo $oz_common_webmails_html ?></optgroup>
            <? } ?>
              
			<? if ($oz_other_webmails_count>0) { ?>
            <optgroup label="{{DROPDOWN_OTHER_WEBMAILS}}"><? echo $oz_other_webmails_html ?></optgroup>
            <? } ?>

			<? if ($oz_sn_count>0) { ?>
            <optgroup label="{{DROPDOWN_SOCIAL_NETWORKS}}"><? echo $oz_sn_html ?></optgroup>
            <? } ?>
  
            </select>
		</div></div>
    </form>
  </div>
  <?
//=====================================================================================================================
//LOGIN ID/PASSWORD FORM PANEL
//=====================================================================================================================
?>
  <div id="ozpanel_loginpassword">
    <form method="post" name="ozform_login" onsubmit="return ozOnSubmit();" style="margin:0px;">
<? echo ozi_render_form_snippet(); ?>
      <input type="hidden" name="oz_state" value="<? echo htmlspecialchars($_REQUEST['oz_state']) ?>"/>
      <input type="hidden" name="oz_service" value=""/>
      <div class="sep"><label class="oz_field_label"  id="oz_loginid">{{LOGIN_ID}}</label><label class="oz_field_label" id="oz_loginemail">{{LOGIN_EMAIL}}</label>
          <div class="dd"><input name="oz_auth_login" type="text" value="<? echo htmlspecialchars(ozi_get_param('oz_auth_login',''),ENT_COMPAT,'UTF-8') ?>" style="width:250px" class="oz_field_input"/></div></div>
			<div class="sep"><label class="oz_field_label">{{LOGIN_PASSWORD}}</label><div class="dd"><input name="oz_auth_password" type="password" style="width:250px" class="oz_field_input"/></div></div>

          <p class="instruct sep right_note">{{LOGIN_INSTRUCTIONS}}</p>
		<div class="button_bar">
		<button name="ozbtn_login" class="oz_field_button short_button">{{LOGIN_FETCH_CONTACTS}}</button>
		<? if ((ozi_get_config('selector_mode',0)==0) && ($_GET['type']=='app')) { ?><a href='#' onclick='ozStartAgain();return false;' class='start_again_app'>{{START_AGAIN}}</a><? } ?>
		</div>
    </form>
  </div>
  
  <?
//=====================================================================================================================
//HOTMAIL WINDOWS LIVE LOGIN PANEL
//=====================================================================================================================
?>
    <form method="post" name="ozform_webauth" onsubmit="return ozOnSubmit();" style="margin:0px">
<? echo ozi_render_form_snippet(); ?>
      <input type="hidden" name="oz_state" value="<? echo htmlspecialchars($_REQUEST['oz_state']) ?>"/>
      <input type="hidden" name="oz_service" value=""/>
      <input type="hidden" name="oz_authstr" value=""/>
	<script type="text/javascript">
	//<![CDATA[
    function ozAuthCallback(serviceid,authstr)
    {
		ozOnSubmit();	//Show progress bar
		document.forms.ozform_webauth.oz_service.value=serviceid;
		document.forms.ozform_webauth.oz_authstr.value=authstr;
		document.forms.ozform_webauth.submit();
    }
    
    function ozWindowsLiveAuth()
    {
		<? 
		echo '//'.strtolower(ozi_make_absolute_url(oz_get_current_url(),''))."\r\n";
		if (strpos(strtolower(ozi_make_absolute_url(oz_get_current_url(),'')),'localhost')!==FALSE) { ?>
		alert('Windows Live Login cannot work if the current url is "localhost". Please browse to this page using 127.0.0.1 or a host name');
		<? } ?>
		var url = 'https://consent.live.com/Delegation.aspx?RU=<? echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/windowslive.php')) ?>&ps=Contacts.View&pl=<? echo (ozi_make_absolute_url(oz_get_current_url(),oz_get_privacy_policy_path())) ?>';
		ozPopUp(url,'oz_auth',650,500);
    }
    function ozGoogleAuth()
    {
		var url = 'https://www.google.com/accounts/AuthSubRequest?session=0&secure=0&scope=http%3A%2F%2Fwww%2Egoogle%2Ecom%2Fm8%2Ffeeds%2F&next=<? echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/google.php')) ?>';
		ozPopUp(url,'oz_auth',650,500);
    }
    function ozGoogleAppsAuth()
    {
		var domain = document.forms.ozform_googleapps.gapps_domain.value;
		var url = 'https://www.google.com/accounts/AuthSubRequest?session=0&secure=0&scope=http%3A%2F%2Fwww%2Egoogle%2Ecom%2Fm8%2Ffeeds%2F&next=<? echo urlencode(ozi_make_absolute_url(oz_get_current_url(),oz_get_resource_path().'auth/google.php')) ?>&hd='+escape(domain);
		ozPopUp(url,'oz_auth',650,500);
    }
	//]]>
    </script>
    </form>
		  

  <div id="ozpanel_login_windowslive" style="display:none;">
	<form style="margin:0px">
<? echo ozi_render_form_snippet(); ?>
  <p class="instruct">{{LOGIN_HOTMAIL_INSTRUCTIONS}}</p>
  <div class="button_bar">
      <button name="ozbtn_wll" onclick="ozWindowsLiveAuth();return false;" class="short_button">{{LOGIN_HOTMAIL_BUTTON}}</button>
<? if ((ozi_get_config('selector_mode',0)==0) && ($_GET['type']=='app')) { ?><a href='#' onclick='ozStartAgain();return false;' class='start_again_app'>{{START_AGAIN}}</a><? } ?>
	</div>
    </form>
  </div>
  <div id="ozpanel_login_gmail" style="display:none">
 	<form style="margin:0px" name="ozform_googleapps">
<? echo ozi_render_form_snippet(); ?>
    <p class="instruct">{{LOGIN_GMAIL_INSTRUCTIONS}}</p>
	<div class="button_bar">
      <button name="ozbtn_gmail" onclick="ozGoogleAuth();return false;" class="short_button space_bottom">{{LOGIN_GMAIL_BUTTON}}</button>
    </div>

    <p class="instruct">{{LOGIN_GOOGLEAPPS_INSTRUCTIONS}}</p>
	<div class="sep">
      <label class="oz_field_label">{{LOGIN_GOOGLEAPPS_DOMAIN}}</label><div class="dd"> <input type="text" name="gapps_domain" size="15" class="oz_field_input"/><span class="note"> {{LOGIN_GOOGLEAPPS_DOMAIN_EXAMPLE}}</span></div>
	</div>
	<div class="button_bar">
	  
      <button name="ozbtn_googleapps" onclick="ozGoogleAppsAuth();return false;" class="short_button">{{LOGIN_GOOGLEAPPS_BUTTON}}</button>
	  <? if ((ozi_get_config('selector_mode',0)==0) && ($_GET['type']=='app')) { ?><a href='#' onclick='ozStartAgain();return false;' class='start_again_app'>{{START_AGAIN}}</a><? } ?>
	</div>
    </form>    
  </div>

  <div id="ozpanel_facebook" style="display:none;">
<?
	global $_OZI_CALLBACKS;
	$func = $_OZI_CALLBACKS['get_invite_message']	;
	$msg = $func(NULL,NULL,NULL);
	//$msg = oz_get_invite_message();
	$url = $msg['url'];
	$title = $msg['subject'];
	//$text_body = str_replace('{PERSONALMESSAGE}','',$msg['text_body']);
	//$text_body = '';
?>
	<form style="margin:0px">
<?
////////////////////////////////////////////////////////////////////////////////////////////
//FB BEGIN
////////////////////////////////////////////////////////////////////////////////////////////
$ozi_fb_app_key = ozi_get_config('facebook_connect.api_key','');
if (!empty($ozi_fb_app_key) && function_exists('ozi_render_fbconnect')) {
	ozi_render_fbconnect($msg);
?>
<div style="margin:10px;">
   <p class="instruct">{{FACEBOOK_CONNECT_SHARE_INSTRUCTIONS}}<p>
   <input type="button" onclick="ozPopUp('http://www.facebook.com/sharer.php?u=<? echo urlencode($url) ?>&amp;t=<? echo urlencode($title) ?>','oz_auth',650,600);return false;" value="{{SHARE_LINK}}">
</div>
<?
}
else {
?>
   <p class="instruct">{{SHARE_FACEBOOK_INSTRUCTIONS}}<p>
	<div class="button_bar">
	  <a href='#' onclick='ozStartAgain();return false;' class='start_again_app'>{{START_AGAIN}}</a>
   <button onclick="ozPopUp('http://www.facebook.com/sharer.php?u=<? echo urlencode($url) ?>&amp;t=<? echo urlencode($title) ?>','oz_auth',650,600);return false;" class="short_button">{{SHARE_LINK}}</button>
   </div>
<?	
}
////////////////////////////////////////////////////////////////////////////////////////////
//FB END
////////////////////////////////////////////////////////////////////////////////////////////
?>
   </form>
   
  </div>
</div></div>
<div style="display:none">Powered by <a href="http://www.octazen.com" target="_blank">Octazen Solutions Invite Engine</a></div>
<!--
<script type="text/javascript">

/*
function ozUpdateVisibility()
{
	sel = document.forms.ozform_select.oz_service;
	ozLoginInit(sel.options[sel.selectedIndex].value);
	clearTimeout(oz_timeout1);
}
//Enabling this seems to cause a error on IE where we try to set focus on a field which is not yet visible.
//(as the whole login form itself isn't visible during the first load)

oz_timeout1 = setTimeout("ozUpdateVisibility()",0);
*/
</script>
-->