<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/
if (!defined('_OZ_INVITER')) exit();
//////////////////////////////////////////////////////////////////////////
//Takes in parameter from $_REQUEST
//	oz_members
//		Array of contacts. Each contact is an associative array.
//
//Submits the following
//	oz_mid[]
//		Array of select member IDs
//////////////////////////////////////////////////////////////////////////
?>
<div class="oz_header">
<div class="oz_header_label">{{MEMBERS_TITLE}}</div>
<div class="oz_header_startagain">
  <? if ($_GET['type']=='setup') { ?>
    <a href="#" onclick="return top.Signup.NextStep()" style="float:right;margin-left:15px;">Skip to next step</a>
  <? } ?>
  <a href="#" onclick="ozStartAgain2();return false;">{{START_AGAIN}}</a>
</div>
</div>

<form method="post" name="oz_members_form" style="margin:0px;">
	<? echo ozi_render_form_snippet(); ?>
	<input type="hidden" name="oz_state" value="<? echo htmlspecialchars($_REQUEST['oz_state']) ?>"/>

<script type="text/javascript">
//<![CDATA[
function ozSelectAll(cb)
{
	var val = cb.checked;
	var frm = document.forms.oz_members_form;
	var len = frm.elements.length;
	for(var i=0 ; i<len ; i++) {
		var cb = frm.elements[i];
		if (cb.name=='oz_mid[]') cb.checked=val;
	}
	ozUpdateSelection();
}

function ozUpdateSelection() {
	var frm = document.forms.oz_members_form;
	var len = frm.elements.length;
	for(var i=0 ; i<len ; i++) {
		var cb = frm.elements[i];
		if (cb.name=='oz_mid[]') {
			ozUpdateRowStyle(cb.parentNode.parentNode,cb.checked);
		}
	}
}

function ozUpdateCb(cb) {
	var checked = cb.checked;
	ozUpdateRowStyle(cb.parentNode.parentNode,checked);	
}

function ozUpdateRowStyle(row, checked) {
	var cn = row.className;
	var hascb = cn.indexOf('oz_row_cb')!=-1;
	var evenrow = cn.indexOf('oz_row_even')!=-1;
	var cn2 = evenrow?'oz_row_even':'oz_row_odd';
	if (checked) cn2+='_selected';
	if (hascb) cn2+=' oz_row_cb';
	row.className = cn2;
}

function ozToggleRow(tr)
{
	var nl = tr.parentNode.getElementsByTagName('input');
	var checked = nl[0].checked = !nl[0].checked;

	ozUpdateCb(nl[0]);
	
//	ozUpdateRowStyle(tr.parentNode,checked);	
}

var oz_float_row=null;
//var IE = document.all?true:false

function ozGetFloatDiv() {
	var float = document.getElementById('oz_floating_image');
	if (float) return float;
	
	//Create the necessay div and floating iframe window in page
	var d = document.createElement('div');
	d.setAttribute('id','oz_floating_image');
	d.style.position='absolute';
	d.style.display='none';
	d.style.border='1px solid #FF0000';
	d.style.padding='0px';
	d.style.zIndex=10000;
	document.body.appendChild(d);
	float = document.getElementById('oz_floating_image');
	return float;
}

function ozHideImage()
{
	if (oz_float_row!=null)
	{
		var float = ozGetFloatDiv();
		float.style.display="none";
	}		
	oz_float_row=null;
}

function ozShowImage(obj)
{
	var elements = obj.getElementsByTagName('img');
	if (elements.length==0) return;
	for (var i=0; i<elements.length; i++) {
		var img = elements[i];
		if (img.className && img.className=='oz_contact_img') {
			var imgsrc=img.src;
			if (imgsrc!=undefined && imgsrc.length>0)
			{
				oz_float_row=obj;
				obj.onmouseout=ozHideImage;
				var float = ozGetFloatDiv();
				float.innerHTML='<img src="'+imgsrc+'"/>';
				float.style.display="block";
				//dropmenuobj.style.visibility="visible"
			}
		}
	}
}

function ozUpdateImagePosition(e)
{
	//Get mouse position, relative to document
	var x=0,y=0;
	if (!e) var e = window.event;
	if (e.pageX || e.pageY) {
		x=e.pageX;
		y=e.pageY;
	}
	else if (e.clientX || e.clientY) {
		x=e.clientX + document.body.scrollLeft + document.documentElement.scrollLeft;
		y=e.clientY + document.body.scrollTop + document.documentElement.scrollTop;
	}

	var float = ozGetFloatDiv();
	float.style.top = y+"px";
	float.style.left = (50+x)+"px";
}

//]]>
</script>

  <div class="oz_members_list">
  <?

$contacts = isset($_REQUEST['oz_members']) ? $_REQUEST['oz_members'] : array();



if (count($contacts)==0)
{
?>
<div id="ozpanel_nomembers">
<p align='center'>{{MEMBERS_NO_MEMBERS}}</p>
</div>
<?
}
else {
?>
  <table border="0" cellpadding="3" cellspacing="0" width="100%" class="oz_contacts_table_header">
    <tr>
      <td>
      <label>
        <input type="checkbox" name="oz_select_all" value="" onclick="ozSelectAll(this)"/>
        <span class="oz_field_label">{{MEMBERS_SELECT_ALL_NONE}}</span></label>
      </td>
    </tr>
  </table>
  <div class="oz_contacts_table">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <?
	$oz_is_email = false;
	$rowc = 0;
	foreach ($contacts as $c) 
	{
		//$cid = $c['id'];
		$mid = $c['member_id'];
		$namehtml = isset($c['x-namehtml']) ? $c['x-namehtml'] : htmlspecialchars(isset($c['name']) ? $c['name'] : '',ENT_COMPAT,'UTF-8');
		$nocb = isset($c['x-nocheckbox']);
		$image = isset($c['image']) ? $c['image'] : '';
/*		
		if (isset($c['uid']))
		{
			//Sender social network contact
			$emailhtml = isset($c['x-emailhtml']) ? $c['x-emailhtml'] : htmlspecialchars(isset($c['email']) ? $c['email'] : '',ENT_COMPAT,'UTF-8');
			echo '<tr class="'.(($rowc & 0x1)==0 ? 'oz_row_even':'oz_row_odd').($nocb?'':' oz_row_cb').'" onmouseover="ozShowImage(this)">';
			
			//Render checkbox
			echo '<td width="1" class="oz_col_cb">';
			if (!$nocb) echo '<input type="checkbox" name="oz_mid[]" value="'.htmlspecialchars($cid).'" onclick="ozUpdateCb(this);"/>';
			else echo '&nbsp;';
			echo '</td>';

			//Render image
			if (!$nocb) echo '<td width="1" class="oz_col_img" onclick="ozToggleRow(this);">';
			else echo '<td width="1" class="oz_col_img">';
			if (!empty($image)) echo '<div class="oz_contact_image"><div><img src="'.htmlspecialchars($image).'" class="oz_contact_img"/></div></div>';
			else echo '&nbsp;';				
			echo '</td>';
			
			//Render name
			if (!$nocb) echo '<td onclick="ozToggleRow(this);" class="oz_col_name">';
			else echo '<td class="oz_col_name">';
			//if (isset($c['x-profileurl'])) echo '<a href="'.$c['x-profileurl'].'">'.htmlspecialchars($name,ENT_COMPAT,'UTF-8').'</a>';
			//else echo htmlspecialchars($name,ENT_COMPAT,'UTF-8');
			if (!empty($namehtml)) echo '<div class=\'oz_name\'>'.$namehtml.'</div>';
			else echo '&nbsp;';
//			echo '</td>';

			//Render email			
//			if (!$nocb) echo '<td onclick="ozToggleRow(this);" class="oz_col_email">';
//			else echo '<td>';
			//if (isset($c['x-profileurl'])) echo '<a href="'.$c['x-profileurl'].'">'.htmlspecialchars($email,ENT_COMPAT,'UTF-8').'</a>';
			//else echo htmlspecialchars($email,ENT_COMPAT,'UTF-8');
			if (!empty($emailhtml)) echo '<div class=\'oz_email\'>'.$emailhtml.'</div>';
			else echo '&nbsp;';
			echo '</td>';

			//Render additional contact html			
			echo '<td class="oz_col_html">';
			if (isset($c['x-html'])) echo $c['x-html'];
			else echo '&nbsp;';
			echo '</td>';
			
			echo '</tr>';
		}
		else
		{
*/		
			$oz_is_email = true;
			
			//Render normal email contact
			$emailhtml = isset($c['x-emailhtml']) ? $c['x-emailhtml'] : htmlspecialchars(isset($c['email']) ? $c['email'] : '',ENT_COMPAT,'UTF-8');
			echo '<tr class="'.(($rowc & 0x1)==0 ? 'oz_row_even':'oz_row_odd').($nocb?'':' oz_row_cb').'" onmouseover="ozShowImage(this)">';
			
			//Render checkbox
			echo '<td width="1" class="oz_col_cb">';
			if (!$nocb) echo '<input type="checkbox" name="oz_mid[]" value="'.htmlspecialchars($mid).'" onclick="ozUpdateCb(this);"/>';
			else echo '&nbsp;';
			echo '</td>';

			//Render image
			if (!$nocb) echo '<td width="1" class="oz_col_img" onclick="ozToggleRow(this);">';
			else echo '<td width="1" class="oz_col_img">';
			if (!empty($image)) echo '<div class="oz_contact_image"><div><img src="'.htmlspecialchars($image).'" class="oz_contact_img"/></div></div>';
			else echo '&nbsp;';				
			echo '</td>';
			
			//Render name
			if (!$nocb) echo '<td onclick="ozToggleRow(this);" class="oz_col_name">';
			else echo '<td class="oz_col_name">';
			//if (isset($c['x-profileurl'])) echo '<a href="'.$c['x-profileurl'].'">'.htmlspecialchars($name,ENT_COMPAT,'UTF-8').'</a>';
			//else echo htmlspecialchars($name,ENT_COMPAT,'UTF-8');
			if (!empty($namehtml)) echo '<div class=\'oz_name\'>'.$namehtml.'</div>';
			else echo '&nbsp;';
//			echo '</td>';

			//Render email			
//			if (!$nocb) echo '<td onclick="ozToggleRow(this);" class="oz_col_email">';
//			else echo '<td>';
			//if (isset($c['x-profileurl'])) echo '<a href="'.$c['x-profileurl'].'">'.htmlspecialchars($email,ENT_COMPAT,'UTF-8').'</a>';
			//else echo htmlspecialchars($email,ENT_COMPAT,'UTF-8');
/*			
			if (!empty($emailhtml)) echo '<div class=\'oz_email\'>'.$emailhtml.'</div>';
			else echo '&nbsp;';
*/			
			echo '</td>';

			//Render additional contact html			
			echo '<td class="oz_col_html">';
			if (isset($c['x-html'])) echo $c['x-html'];
			else echo '&nbsp;';
			echo '</td>';
			
			echo '</tr>';
/*
		}
*/		
		$rowc++;
	}
?>
    </table>
  </div>
</div>  
  <?
}

if (count($contacts)>0) 
{
?>
  <div id="ozpanel_submitcontacts">
    <? /* if (ozi_get_config('allow_personal_message',TRUE)) { ?>
    <div><span class="oz_field_label">{{PERSONAL_MESSAGE}}</span><br/>
      <textarea name="oz_message" class="oz_field_input" style="width:100%; height: 4em"><? echo htmlspecialchars(ozi_get_param('oz_message',''),ENT_COMPAT,'UTF-8') ?></textarea>
    </div>
    <br/>
    <? } */ ?>
    <input type="submit" name="ozbtn_members" value=" {{MEMBERS_ADD_AS_FRIEND}} " class="oz_field_button"/>
    &nbsp;&nbsp;
    <input type="submit" name="ozbtn_members_skip" value=" {{MEMBERS_SKIP}} " class="oz_field_button"/>
  </div>
  <?
}
?>
<!--
<img src="http://www.octazen.com/api/usage/?sec=cl&id={#TRKCDE#}" width="1" height="1"/>
-->
</form>
<script type="text/javascript">
//<![CDATA[
<? if (ozi_get_config('select_all_contacts',FALSE)) { ?>
DomReady.ready(function() {
	document.forms.oz_members_form.oz_select_all.checked=true;
	ozSelectAll(document.forms.oz_members_form.oz_select_all);
});
<? } ?>
DomReady.ready(function() {
	ozUpdateSelection();
	document.onmousemove=ozUpdateImagePosition;
});
ozNotifyViewChange('members');
//]]>
</script>
<? 

?>