<?
/********************************************************************************
DO NOT EDIT THIS FILE!

Unified Inviter Component

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved.
WWW: http://www.octazen.com
********************************************************************************/

//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
if (!defined('_OZ_INVITER')) exit();
?>
<div class="oz_header">
<div class="oz_header_label">{{MANUAL_TITLE}}</div>
<div class="oz_header_startagain">
   <? if ($_GET['type']=='setup') { ?>
    <a href="#" onclick="return top.Signup.NextStep()" style="float:right; margin-left: 15px;">Skip to next step</a>
  <? } ?>
  <a href="#" onclick="ozStartAgain();return false;">{{START_AGAIN}}</a>
</div>
</div>
<div id="ozpanel_manual">
  <script type="text/javascript">
//<![CDATA[
function ozAddEmailRow()
{
	var ele = document.getElementById("oz_email_row");
	var newnode = ele.cloneNode(true);
	var input = newnode.getElementsByTagName('input')[0];
	input.value='';
	input.id=null;
	var lastrow = document.getElementById("oz_last_row");
	ele.parentNode.insertBefore(newnode,lastrow);
	ozNotifyResize();
}
function ozCheckEmailField(input)
{
	emailre = /^([+=&'\/\\?\\^\\~a-zA-Z0-9\._-])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-]+)+$/
	if (input.value.length==0) input.className="oz_field_input";
	else if (emailre.test(input.value)) input.className="oz_field_input oz_email_valid";
	else input.className="oz_field_input oz_email_invalid";
}
function ozOnManualSubmit(form)
{
	<? if (ozi_get_config('your_email',TRUE)) { ?>
	emailre = /^([+=&'\/\\?\\^\\~a-zA-Z0-9\._-])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-]+)+$/
	if (!emailre.test(form.oz_from_email.value)) 
	{
		alert('{{INVALID_EMAIL}}');
		form.oz_from_email.focus();
		return false;
	}
    <? } ?>
	return true;
}
//]]>
</script>
  <form method="post" name="ozform_manual" style="margin:0px;" onclick="return ozOnManualSubmit(this);">
<? echo ozi_render_form_snippet(); ?>
    <input type="hidden" name="oz_state" value="<? echo htmlspecialchars($_REQUEST['oz_state']) ?>"/>
    <input type="hidden" name="oz_service" value="manual"/>
    <p>
<? if (ozi_get_config('manual_multiple_textbox',TRUE)) { ?>
    {{MANUAL_INSTRUCTIONS}}
<? } else { ?>    
    {{MANUAL_INSTRUCTIONS2}}
<? } ?>
    </p>
        <table id="oz_manual_emails">
		    <? if (ozi_get_config('manual_multiple_textbox',TRUE)) { ?>
            <tr id="oz_email_row">
              <td align="right"><span class="oz_field_label">{{MANUAL_EMAIL}}</span></td>
              <td><input type="text" name="oz_cid[]" onchange="ozCheckEmailField(this)" class="oz_field_input" size="24"/></td>
            </tr>
            <tr>
              <td align="right"><span class="oz_field_label">{{MANUAL_EMAIL}}</span></td>
              <td><input type="text" name="oz_cid[]" onchange="ozCheckEmailField(this)" class="oz_field_input" size="24"/></td>
            </tr>
            <tr>
              <td align="right"><span class="oz_field_label">{{MANUAL_EMAIL}}</span></td>
              <td><input type="text" name="oz_cid[]" onchange="ozCheckEmailField(this)" class="oz_field_input" size="24"/></td>
            </tr>
            <tr>
              <td align="right"><span class="oz_field_label">{{MANUAL_EMAIL}}</span></td>
              <td><input type="text" name="oz_cid[]" onchange="ozCheckEmailField(this)" class="oz_field_input" size="24"/></td>
            </tr>
            <tr>
              <td align="right"><span class="oz_field_label">{{MANUAL_EMAIL}}</span></td>
              <td><input type="text" name="oz_cid[]" onchange="ozCheckEmailField(this)" class="oz_field_input" size="24"/></td>
            </tr>
            <tr id="oz_last_row">
              <td>&nbsp;</td>
              <td><a href="#" onclick="ozAddEmailRow();return false;">{{MANUAL_ADD_ANOTHER}}</a><br/></td>
            </tr>
			<? } else { ?>    
        	<tr>
            	<td valign="top" width="150" align="right"><span class="oz_field_label">{{MANUAL_EMAILS}}</span></td>
                <td><textarea name="oz_cids" class="oz_field_input" cols="50" style="height: 6em"><? echo htmlspecialchars(ozi_get_param('oz_emails',''),ENT_COMPAT,'UTF-8') ?></textarea></td>
            </tr>
		    <? } ?>
            <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
		    <? if (ozi_get_config('your_name',TRUE)) { ?>
            <tr>
		    	<td align="right"><span class="oz_field_label">{{YOUR_NAME}}</span></td>
	            <td><input type="text" name="oz_from_name" value="<? echo ozi_get_config('from_name','') ?>" size="24" class="oz_field_input" /></td>
            </tr>
		    <? } ?>
		    <? if (ozi_get_config('your_email',TRUE)) { ?>
            <tr>
		    	<td align="right"><span class="oz_field_label">{{YOUR_EMAIL}}</span></td>
	            <td><input type="text" name="oz_from_email" value="<? echo ozi_get_config('from_email','') ?>" size="24" class="oz_field_input" onchange="ozCheckEmailField(this)"/> *</td>
            </tr>
		    <? } ?>
    	    <? 
			/*
			$subject = isset($_REQUEST['oz_subject']) ? htmlspecialchars($_REQUEST['oz_subject']) :'';
			$text_body = isset($_REQUEST['oz_body']) ? htmlspecialchars($_REQUEST['oz_body']) :'';
			if (empty($subject) || empty($text_body)) {
				global $_OZI_CALLBACKS;
				$func = $_OZI_CALLBACKS['get_invite_message']	;
				$msg = $func(ozi_get_config('from_name',''),ozi_get_config('from_email',''),'');
				$subject = $msg['subject'];
				$text_body = $msg['text_body'];
				//$html_body = $msg['html_body'];
			}
			if (ozi_get_config('allow_edit_message',TRUE)) { ?>
        	<tr><td valign="top" width="150" align="right"><span class="oz_field_label">{{SUBJECT}}</span></td><td><input type="text" name="oz_from_email" value="<? echo htmlspecialchars($subject) ?>" size="50" class="oz_field_input"/></td></tr>
        	<tr><td valign="top" width="150" align="right"><span class="oz_field_label">{{MESSAGE}}</span></td><td><textarea name="oz_message" class="oz_field_input" cols="50" style="height: 8em"><? echo htmlspecialchars($text_body) ?></textarea></td></tr>
	        <? }
			*/
			?>
    	    <? if (ozi_get_config('allow_personal_message',TRUE)) { 
				$pmsg = ozi_get_param('oz_message',NULL);
				if ($pmsg===NULL) $pmsg=ozi_get_config('default_personal_message','');
			?>
        	<tr><td valign="top" width="150" align="right"><span class="oz_field_label">{{PERSONAL_MESSAGE}}</span></td><td><textarea name="oz_message" class="oz_field_input" cols="50" style="height: 4em"><? echo htmlspecialchars($pmsg,ENT_COMPAT,'UTF-8') ?></textarea></td></tr>
	        <? }?>
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
           <tr><td>&nbsp;</td><td><input type="submit" name="ozbtn_manual" value=" {{MANUAL_SEND_INVITATION}} " class="oz_field_button"/></td></tr>
           </table>
  </form>
</div>
