<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Freenet.de contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['freenet'] = array('type'=>'abi', 'label'=>'Freenet.de', 'class'=>'FreenetDeImporter');

//define('FreenetDeImporter_CONTACT_REGEX',"/<option value=\"([^\\|]*)\\|\">(.*?)\\([^\\)]*\\)<\/option>/ims");
define('FreenetDeImporter_CONTACT_REGEX',"/<tr[^>]*?class=\"miniBookRow\".*?<td[^>]*>([^<]*)<\/td>\\s*<td>([^<]*)</ims");
define('FreenetDeImporter_SIS_REGEX',"/SIS_param=([0-9A-F]*)/ims");

/////////////////////////////////////////////////////////////////////////////////////////
//FreenetdeImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class FreenetDeImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'freenet.de');
	}

	//@api
	function logout () {
		//$this->httpGet('http://email.freenet.de/login/logoff.html?code=1011');
		$this->httpGet('http://logout.freenet.de/');
	}

	//@api
	function login ($loginemail, $password) {
		$this->setOwnerEmail($loginemail);
		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		oz_set_domain($parts[1]);

		$form = new HttpForm;
		$form->action = 'http://e-tools.freenet.de/login.php3';
		$form->addField("action", "login");
		$form->addField("callback", 'http://email.freenet.de/login/index.html');
		$form->addField("world", "frn_DE");
		$form->addField("username", $login);
		$form->addField("passtext", "Passwort");
		$form->addField("password", $password);
		$form->addField("ssl", "2");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$html = $this->postForm($form);
		if (strpos($html, 'Der Login-Name oder das Passwort')!==false || strpos($html,'class="logktrot"')!==false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		$url = oz_get_refresh_url($html);
		if ($url!=null) {
			$html = $this->httpGet($url);
		}

		if (strpos($this->lastUrl,"www.freenet.de"!==FALSE) || oz_extract_form_by_name($html,"sicherform")!=NULL) {
			if (preg_match(FreenetDeImporter_SIS_REGEX,$html,$matches)==0) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find SIS_param');
			}
			$html = $this->httpGet("http://email.freenet.de/login/index.html?world=frn_DE&SIS_param="+$matches[1]);
		}

		//If we got a reminder to logout, then jump straight to page
		if (strpos($html,'Sicherheits-Hinweis')!==false)
			$html = $this->httpGet('http://email.freenet.de');

		return abi_set_success();

	}

	//@api
	function fetchContacts ($loginemail=NULL, $password=NULL) {

		if ($loginemail!=NULL) {
			$res = $this->login($loginemail,$password);
			if ($res!=_ABI_SUCCESS) return $res;
		}

		$cl = array();
		$html = $this->httpGet("http://email.freenet.de/Global/View/miniAddressBook?searchType=email&isPopup=0&callType=html");
		preg_match_all(FreenetDeImporter_CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			$name = htmlentities2utf8($val[1]);
			$email = htmlentities2utf8($val[2]);
			$cl[] = new Contact($name,$email);
		}
		$this->logout();
		return $cl;

		//Freenet's CSV export has wrong fields
		/*
		$csv = $this->httpGet('http://email.freenet.de/Contacts/Action/Export?type=csv');
		if ($loginemail!=NULL) {
			$this->logout();
		}
		return abi_extract_outlook_csv($csv,';');
		*/
	}
}


//freenet.de
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["freenet.de"] = 'FreenetDeImporter';
