<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Mail.ru contacts importer.

Note that mail.ru returns characters encoded in windows-1251 encoding.
This script tries to perform the conversion to utf-8 if iconv library is available,
but does not perform any encoding if the library is not available.

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['mailru'] = array('type'=>'abi', 'label'=>'Mail.ru', 'class'=>'MailRuImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//MailRuImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class MailRuImporter extends WebRequestor {

	//@api
	function getInfo () {
		return array('id'=>'mail.ru');
	}

	//@api
	function login ($loginemail, $password) {

		$form = new HttpForm;

		$parts = $this->getEmailParts ($loginemail);
		$login = $parts[0];
		$domain = $parts[1];

		$this->setOwnerEmail($loginemail);
		oz_set_domain($domain);

		//1 = outlook csv (but header seems to be russian!)
		//4 = outlook express csv (header in english)
		//$form->addField("page", "abexport/addressbook.csv?confirm=1&abtype=4");
		$form->addField("post", "");
		$form->addField("login_from", "");
		$form->addField("Login", $login);
		$form->addField("Domain", $domain);
		$form->addField("Password", $password);
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost("http://win.mail.ru/cgi-bin/auth", $postData,"CP1251");
		//[Caps Lock]
		//class=or_table
		if (strpos($this->lastUrl,'cgi-bin/login')!==false) {	// && strpos($html, '[Caps Lock]')!=false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
		
		return abi_set_success();
	}
	
	function _fetchCsv() {
		$form = new HttpForm;
		$form->action='/cgi-bin/abexport/addressbook.csv';
		$form->addField("confirm", "1");
		$form->addField("abtype", "4");
		$form->addField("export", "x");
		$html = $this->postForm($form, "CP1251");

		//Blank returned (no headers) if no contacts
		if (empty($html)) return array();
		return $html;
	}


	//@api
	function fetchContacts ($loginemail, $password) {
		if ($loginemail!==NULL || $password!==NULL) {
			$res = $this->login($loginemail,$password);
			if ($res!=_ABI_SUCCESS) return $res;
		}
		$html = $this->_fetchCsv();
		$res = abi_extract_outlook_csv($html);
		return $res;
	}

}

//mail.ru
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["mail.ru"] = 'MailRuImporter';
$_DOMAIN_IMPORTERS["inbox.ru"] = 'MailRuImporter';
$_DOMAIN_IMPORTERS["list.ru"] = 'MailRuImporter';
$_DOMAIN_IMPORTERS["bk.ru"] = 'MailRuImporter';
