<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Rediffmail contacts importer

You may not reprint or redistribute this code without permission from Octazen Solutions.

Copyright 2009 Octazen Solutions. All Rights Reserved
WWW: http://www.octazen.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['rediff'] = array('type'=>'abi', 'label'=>'Rediffmail', 'class'=>'RediffImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//ReddiffImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class RediffImporter extends WebRequestor {

	//var $HOSTURL_REGEX = "/(http:\/\/[^\/]*?)\/.*?&session_id=([^&]*)/ims";
	//var $EXTRACT_REGEX = "/<input type=checkbox name=\"mail_address\" value=\"([^\"]*)\">\\s*(?:&nbsp;)?\\s*([^<]*)<\/td>/i";

	//@api
	function getInfo () {
		return array('id'=>'rediff');
	}

	//@api
	function fetchContacts ($loginemail, $password) {

		$login = $this->getEmailParts($loginemail);
		$login = $login[0];
		$this->setOwnerEmail($loginemail);
		oz_set_domain($login[1]);

		//rediffmail sometimes fail couple of times
		$form = new HttpForm;
		$form->action = "http://mail.rediff.com/cgi-bin/login.cgi";
		$form->addField("FormName", "existing");
		$form->addField("login", $login);
		$form->addField("passwd", $password);
		$form->addField("proceed", "Sign in");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$html = $this->postForm($form);
		if (strpos($html, 'Your login failed')!==false) {
			$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
		
		$url = oz_get_refresh_url($html);
		if ($url===NULL) {
			$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find redirection url');
		}
		$html = $this->httpGet($url);

		$html = $this->httpGet("/prism/exportaddrbook?service=moutlook");
		return abi_extract_outlook_csv($html);

/*
		if (preg_match($this->HOSTURL_REGEX,$this->lastUrl,$matches)==0) {
			if (preg_match($this->HOSTURL_REGEX,$html,$matches)==0) {
				$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find email host');
			}
		}

		$host = $matches[1];
		$sessionId = $matches[2];
		$location = $host."/iris/Main?do=popaddr&login=".urlencode($login)."&session_id=".$sessionId."&field=to&formname=Compose";
		$html = $this->httpGet($location);

		/////////////////////////////////////////////////////
		//EXTRACT!
		/////////////////////////////////////////////////////
		$al = array();
		preg_match_all($this->EXTRACT_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			$email = htmlentities2utf8(trim($val[1]));
			$name = htmlentities2utf8(trim($val[2]));
			if (!empty($email)) {
				$contact = new Contact($name, $email);
				$al[] = $contact;
			}
		}
		$this->close();
		return $al;
*/		
	}
}

// Rediff
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["rediffmail.com"]='RediffImporter';
$_DOMAIN_IMPORTERS["rediff.com"]='RediffImporter';
